## 随机变量 
当执行随机实验时，我们并不总是对实验结果的全部细节都感兴趣，我们仅对由结果确定的某些 **数值量**（*numerical quantity*）的值感兴趣。例如，在抛骰子时，对于每个骰子的点数而言，我们并不感兴趣；我们通常对两个骰子的点数之和感兴趣。也就是说，我们可能想知道点数总和是 7 的情况，而并不关心实际结果是否是：（1, 6）、（2, 5）、（3, 4）、（4, 3）、（5, 2）、（6, 1）。此外，对于土木工程师而言，他们可能不关心水库水位的日常涨落（我们可以将水库水位的日常涨落数据视为实验结果），他们只关心雨季结束时的水位。由实验结果确定的我们感兴趣的这些 **量化指标**（*quantities*），我们称为 **随机变量**（*random variables*）。

因为 **随机变量** 的值是由实验结果确定的，因此，对于 **随机变量** 的可能的值，我们可以对其给与概率赋值。

::: {#exm-4_1_a}
令 $X$ 表示随机变量：抛 2 个骰子的点数之和，则：

$$
\begin{align}
P\{X=2\} &= P(\{(1,1)\}) = \frac{1}{36} \\
P\{X=3\} &= P(\{(1,2), (2,1)\}) = \frac{2}{36} \\
P\{X=4\} &= P(\{(1,3), (2,2), (3,1)\}) = \frac{3}{36} \\
P\{X=5\} &= P(\{(1,4), (2,3), (3,2), (4,1)\}) = \frac{4}{36} \\
P\{X=6\} &= P(\{(1,5), (2,4), (3,3), (4,2), (5,1)\}) = \frac{5}{36} \\
P\{X=7\} &= P(\{(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)\}) = \frac{6}{36} \\
P\{X=8\} &= P(\{(2,6), (3,5), (4,4), (5,3), (6,2)\}) = \frac{5}{36} \\
P\{X=9\} &= P(\{(3,6), (4,5), (5,4), (6,3)\}) = \frac{4}{36} \\
P\{X=10\} &= P(\{(4,6), (5,5), (6,4)\}) = \frac{3}{36} \\
P\{X=11\} &= P(\{(5,6), (6,5)\}) = \frac{2}{36} \\
P\{X=12\} &= P(\{(6,6)\}) = \frac{1}{36}
\end{align}
$$ {#eq-4_1_001}
:::

换句话说，随机变量 $X$ 的取值为 2~12 之间的任何整数值，其每个取值的概率由 @eq-4_1_001 给出。由于 $X$ 必须为某个取值，因此我们必有：

$$
1 = P(S) = P\Bigg( \bigcup_{i=2}^{12}{\{X=i\}} \Bigg) = \sum_{i=2}^{12}{P\{X=i\}}
$$ {#eq-4_1_002}

利用 @eq-4_1_001 可以非常简单的验证 @eq-4_1_002。

在这个实验中，我们感兴趣的另一个 **随机变量** 是第一个骰子的点数。令 $Y$ 表示 **随机变量**：抛两个骰子时第一个骰子的点数。则 $Y$ 的取值为 1~6 之间的任何值。也就是说：

$$
P\{Y=i\} = \frac{1}{6}, i=1,2,3,4,5,6
$$ {#eq-4_1_003}

::: {#exm-4_1_b}
假设一个人购买了两个电子元器件，每个电子元器件或者有缺陷（用 *d* 表示）或者没有缺陷（用 *a* 表示）。则这两个电子元器件有四种可能的结果：(d, d)、(d, a)、(a, d)、(a, a)，**假设**这四种结果的概率分别为：0.09、0.21、0.21、0.49（其中 (d, d) 表示两个元器件都有缺陷，(d, a) 表示第一个元器件有缺陷、第二个元件没有缺陷，依此类推）。
:::

我们令 $X$ 表示购买的两个电子元器件中没有缺陷的元器件数量，那么 $X$ 是一个 **随机变量**，且其取值为 0、1、2 中的一个：

$$
\begin{align}
P\{X=0\} &= 0.09 \\
P\{X=1\} &= 0.42 \\
P\{X=2\} &= 0.49 
\end{align}
$$ {#eq-4_1_004}

如果我们主要关注这两个电子元器件是否至少有一个没有缺陷，则我们可以对 **随机变量** $I$ 作如下定义：

$$
I = \begin{cases}
1, \quad & if \ X=1, 2 \\
0, \quad & if \ X=0
\end{cases}
$$ {#eq-4_1_005}

如果 $A$ 表示事件：至少一个元器件没有缺陷，则根据 $A$ 是否发生，$I$ 将等于 1 或 0。因此，我们称 **随机变量** $I$ 为 **事件** $A$ 的 **指示随机变量**（*indicator random variable*）。$I$ 的可能取值的概率为：

$$
\begin{align}
&P\{I=1\}=0.91 \\
&P\{I=0\}=0.09
\end{align}
$$ {#eq-4_1_006}

在 @exm-4_1_a 和 @exm-4_1_b 这两个例子中，我们感兴趣的 **随机变量** 的可能取值的数量是有限的。对于那些取值可以写成有限序列 $x_1,..., x_n$ 或者无限序列 $x1,...$ 的 **随机变量** 称为 **离散随机变量**（*discrete random variables*）。例如，一个取值集合为非负整数的 **随机变量** 就是 **离散随机变量**。然而，也存在取值为连续数值的 **随机变量**，我们称这种 **随机变量** 为 **连续随机变量**（*continous random variables*）。例如，假定汽车的寿命位于某个区间 $(a,b)$ 时，表示汽车寿命的 **随机变量** 就是 **连续随机变量**。

**随机变量** $X$ 的累积分布函数（*cumulative distribution function*）$F$ 的定义如下：

$$
F(x) = P\{X \le x\}
$$ {#eq-4_1_007}

也就是说，$F(x)$ 是 **随机变量** $X$ 取值小于或等于 $x$ 的概率。

::: {.callout-note}
**随机变量** 的累积分布函数也可简称为 **分布函数**（*distribution function*）。
:::

::: {.callout-tip}
我们将使用 $X \thicksim F$ 来表示 $F$ 是 **随机变量** $X$ 的分布函数。
:::

我们可以用 **随机变量** $X$ 的分布函数 $F$ 来回答所有关于 $X$ 的概率问题。例如，假如我们想计算 $P\{a \lt X \le b\}$。要计算该概率，我们首先注意到 **事件** ${X \le b}$ 可以表示为两个 **互斥事件** ${X \le a}$ 和 ${a \lt X \le b}$ 的并集。因此，根据 **公理3**（@sec-3_4），我们得到：

$$
\begin{align}
P\{X \le b\}&=P\{X \le a\} + P\{a \lt X \le b\} \\
\therefore P\{a \lt X \le b\} &= F(b) - F(a)
\end{align}
$$ {#eq-4_1_008}

::: {#exr-4_1_c}
假设 **随机变量** $X$ 的分布函数为：

$$
F(x) = \begin{cases}
0, \quad & x \le 0 \\
1-e^{-x^2}, \quad & x \gt 0
\end{cases}
$$

计算 $P\{X \gt 1\}$？
:::

::: {#sol-4_1_c}
$$
\begin{align}
P\{X \gt 1\} &= 1 - P\{X \le 1\} \\
&= 1 - F(1) \\
&= e^{-1} \\
&= 0.368
\end{align}
$$
:::