## 习题 {.unnumbered}

1. 根据考试成绩对 5 名男性和 5 名女性进行排名。假设所有人的分数都不相同，并且所有的 $10!$ 种可能的排名的可能性都相等。令 $X$ 表示女性获得的最高名次（例如，如果排名第 1 的是男性，而排名第 2 的是女性，则 $X=2$）。找出 $P\{X=i\}, i=1,2,3,...,8,9,10$。
2. 设 $X$ 表示抛 $n$ 次硬币得到的正面向上的次数和反面向上的次数之差，则 $X$ 的可能值是多少？
3. 在习题 2 中，如果假设硬币是公平的，对于 $n=3$，则 $X$ 可能取值的对应的概率是多少？
4. 随机变量 $X$ 的分布函数为：
    $$
    F(x) = \begin{cases}
    0, \quad & x \lt 0  \\
    \frac{x}{2}, \quad & 0 \le x \lt 1 \\
    \frac{2}{3}, \quad & 1 \le x \lt 2 \\
    \frac{11}{12}, \quad & 2 \le x \lt 3 \\
    1, \quad & 3 \le x \\
    \end{cases}
    $$

    * 画出分布函数的图
    * 计算 $P\{X \gt \frac{1}{2}\}$？
    * 计算 $P\{2 \lt X \le 4\}$？
    * 计算 $P\{X \le 3\}$？
    * 计算 $P\{X = 1\}$？

5. 假设随机变量 $X$ 的概率密度函数为：
    $$
    f(x) = \begin{cases}
    cx^3, \quad & 0 \le x \le 1 \\
    0, \quad & 其他
    \end{cases}
    $$

    * 计算 $c$ 的值？
    * 计算 $P\{0.4 \lt X \lt 0.8\}$？

6. 计算机在故障前运行的小时数是一个连续随机变量，其概率密度函数为：

    $$
    f(x) = \begin{cases}
    \lambda e^{-\frac{x}{100}}, \quad & x \ge 0 \\
    0, \quad & x \lt 0
    \end{cases}
    $$

    * 一台计算机在故障前工作了 50 到 150 小时的概率是多少？
    * 工作不到 100 小时的概率是多少？

7. 收音机中某种电子管的寿命（以小时为单位）是一个随机变量，其概率密度函数为：

    $$
    f(x) = \begin{cases}
    0, \quad & x \le 100 \\
    \frac{100}{x^2}, \quad & x \gt 100
    \end{cases}
    $$

    一台收音机中的 5 个这样的电子管中恰有 2 个必须在 150 小时内更换的概率是多少？假设在这段时间内，必须更换第 $i$ 个电子管的 **事件** $E_i, i=1,2,3,4,5$ 是独立的。

8. 如果 $X$ 的概率密度函数为：

    $$
    f(x) = \begin{cases}
    ce^{-2x}, \quad & 0 \lt x \lt \infty \\
    0, \quad & x \lt 0
    \end{cases}
    $$

    * 计算 $c$？
    * 计算 $P\{X \gt 2\}$？

9. 我们要检测 5 个晶体管，我们以随机的顺序每次检测 1 个晶体管，并检查哪一个晶体管有缺陷。假设 5 个晶体管中有 3 个有缺陷，令 $N_1$ 表示发现第 1 个缺陷晶体管时我们检测的次数，让 $N_2$ 表示发现第 2 个缺陷晶体管时额外增加的检测次数。计算 $N_1$ 和 $N_2$ 的联合概率质量函数。

10. $X$ 和 $Y$ 的联合概率密度函数为：

    $f(x,y)=\frac{6}{7}\big(x^2 + \frac{xy}{2}\big), \ 0 \lt x \lt 1, \ 0 \lt y \lt 2$

    * 验证这确实是一个联合密度函数？
    * 计算 $X$ 的边缘密度函数？
    * 计算 $P\{X \gt Y\}$？

11. 令 $X_1, X_2, ..., X_n$ 是符合 $U(0,1)$ 的均匀分布的独立随机变量。令 $M = max(X_1, X_2, ...,X_n)$，则 $M$ 的分布函数为：

    $F_M(x) = x^n, \ 0 \le x \le 1$

    计算 $M$ 的概率密度函数？

12. $X$、$Y$ 的联合密度函数为：

    $f(x,y)=\begin{cases} xe^{-(x+y)}, \quad & x \gt 0, y \gt 0 \\ 0, \quad & 其它 \end{cases}$

    * 计算 $X$ 的边缘密度函数？
    * 计算 $Y$ 的边缘密度函数？
    * $X$ 和 $Y$ 是独立的吗？

13. $X$、$Y$ 的联合概率密度函数为：

    $f(x,y)=\begin{cases} 2, \quad & 0 \lt x \lt y, 0 \lt y \lt 1 \\ 0, \quad & 其它 \end{cases}$

    * 计算 $X$ 的边缘密度函数？
    * 计算 $Y$ 的边缘密度函数？
    * $X$ 和 $Y$ 是独立的吗？

14. 如果 $X$ 和 $Y$ 的联合密度函数可以分解为仅依赖于 $x$ 的部分和仅依赖于 $y$ 的部分，则 $X$ 和 $Y$ 是独立的。如果：

    $f(x,y)=k(x)h(y), \ -\infty \lt x \lt \infty, \ -\infty \lt x \lt \infty$

    证明，$X$、$Y$ 是相互独立的。

15. 习题 14 与习题 12 和习题 13 的结果一致吗？

16. 假设 $X$、$Y$ 是独立的连续随机变量，证明：

    * $P\{X + Y \le a\} = \int_{-\infty}^{\infty}{F_X(a-y)f_Y(y)\mathrm{d} y}$
    * $P\{X \le Y\} = \int_{-\infty}^{\infty}{F_X(y)f_Y(y)\mathrm{d} y}$

    其中，$f_Y$ 是 $Y$ 的边缘概率密度函数，$F_X$ 是 $X$ 的边缘分布函数。

17. 当电流 $I$（单位为安培）流过电阻 $R$ 时（单位为欧姆），产生的功率（单位为瓦特）为 $W=I^2R$。 假设 $I$ 和 $R$ 是独立随机变量且其概率密度函数为：

    $f_I(x) = 6x(1-x), \quad 0 \le x \le 1$

    $f_R(x) = 2x, \quad 0 \le x \le 1$

    计算 $W$ 的概率密度函数？

18. 在 @exm-4_3_b 中，计算所选择的家庭有 2 个女孩的条件概率质量函数？

19. 计算 $X$ 在 $Y=y$ 时的条件概率密度函数：
    
    * $X$、$Y$ 的联合概率密度函数如习题 10
    * $X$、$Y$ 的联合概率密度函数如习题 13

20. 证明 $X$、$Y$ 是独立随机变量当且仅当：

    * $X$、$Y$ 是离散随机变量且 $P_{X|Y}(x|y)=p_X(x)$
    * $X$、$Y$ 是连续随机变量且 $f_{X|Y}(x|y)=f_X(x)$

21. 计算习题 1 中随机变量的期望？

22. 计算习题 3 中随机变量的期望？

23. 每天晚上，不同的气象学家会预测第二天下雨的“概率”。为了判断这些人的预测水平，我们将按如下的规则给他们打分：如果气象学家预测明天下雨的概率为 $p$，那么他们的得分为：

    * 如果明天确实下雨了，得分为：$1 - (1 - p)^2$
    * 如果明天没有下雨，得分为：$1 - p^2$

    对于这些打分，我们将跟踪一定的时间，并得出结论：平均打分最高的气象学家就是最佳天气预测者。现在，假设某个气象学家已经了解到了打分的规则，并希望最大化自己的打分。如果该气象学家真的相信明天下雨的概率为 $p^*$，那么为了最大化自己的打分，他预测明天下雨的概率 $p$ 应该是多少？

24. 一家保险公司有一种保单，大意是：如果某个事件 $E$ 在一年内发生，则他们必须支付一笔钱 $A$。如果保险公司估计 $E$ 在一年内发生的概率为 $p$，保险公司应该向客户收取多少费用，以使得他们的预期利润将是 $A$ 的 10%？

25. 4 辆载有来自同一所学校的 148 名学生的公共汽车来到一个足球场。公共汽车的载客量分别为：40名、33名、25名和50名。随机选择一名学生，令 $X$ 表示随机选择的这个学生所在的公共汽车上的学生数量。对于 4 辆车的 4 名司机，随机选择 1 名司机，令 $Y$ 表示该司机驾驶的公共汽车上的学生数量。

    * 你认为 $E[X]$ 和 $E[Y]$ 哪一个更大？为什么？
    * 计算 $E[X]$ 和 $E[Y]$。

26. 在一场多局游戏比赛中，两个参赛队伍中，如果有一个首先赢得 $i$ 局游戏，则游戏结束。假设每一局比赛都是独立的，且 $A$ 队获胜概率是 $p$。当 $i=2$ 时：

    * 计算游戏局数的期望？
    * 证明当 $p=\frac{1}{2}$ 时，该期望值最大？

27. $X$ 的概率密度函数为：

    $f(x)=\begin{cases} a + bx^2, \quad & 0 \le x \le 1\\ 0, \quad & 其它 \end{cases}$

    如果 $E[X] = \frac{3}{5}$，计算 $a$ 和 $b$。

28. 某电子管的寿命（单位为小时）是一个随机变量，其概率密度函数为：

    $f(x) = a^2xe^{-ax}, \quad x \ge 0$

    计算该电子管的寿命的期望？

29. 令 $X_1, X_2,...,X_n$ 是独立同分布的随机变量，其概率密度函数为：

    $f(x) = \begin{cases} 1, \quad & 0 \lt x \lt 1\\ 0, \quad & 其它 \end{cases}$

    计算：
    
    * $E[Max(X_1, X_2, ..., X_n)]$
    * $E[Min(X_1, X_2, ..., X_n)]$

30. 假设 $X$ 的概率密度函数为：
    
    $f(x)=\begin{cases} 1, \quad & 0 \lt x \lt 1\\ 0, \quad & 其它 \end{cases}$

    根据如下的要求计算 $E[X^n]$：

    * 先计算 $X^n$ 的概率密度，然后根据期望的定义计算 $E[X^n]$
    * 利用 @prp-4_5_1 计算 $E[X^n]$

31. 修理个人电脑所需的时间（以小时为单位）是一个随机变量，其密度函数为：

    $f(x)=\begin{cases} \frac{1}{2}, \quad & 0 \lt x \lt 2\\ 0, \quad & 其它 \end{cases}$

    修理的费用取决于修理所需的时间，当修理所需时间为 $x$ 时，费用为 $40 + 30 \sqrt{x}$。计算修理个人电脑的费用的期望。

32. 如果 $E[X] = 2$，$E[X^2] = 8$，计算：

    * $E[(2 + 4X)^2]$？
    * $E[X^2 + (X+1)^2]$？

33. 从包含 17 个白球和 23 个黑球的盒子中随机选择 10 个球。令 $X$ 表示所选白球的数量。利用如下的方式计算 $E[X]$：

    * 定义适当的指示随机变量 $X_i, i=1,...,10$，以满足 $X = \sum_{i=1}^{10}{X_i}$。
    * 定义适当的指示随机变量 $Y_i, i=1,...,17$，以满足 $X = \sum_{i=1}^{17}{Y_i}$。

34. 如果 $X$ 是具有分布函数 $F$ 的连续随机变量，则其中位数（*median*）的定义为令 $F(m)=\frac{1}{2}$ 的 $m$ 的值。如果随机变量的概率密度函数如下所示，计算其中位数：

    * $f(x) = e^{-x}, \quad x \ge 0$。
    * $f(x) = 1, 0 \le x \le 1$。

35. 在预测随机变量的值方面，中位数和均值一样都是很重要的概念。如前所述（@eq-4_5_005），随机变量的均值是从最小化误差平方的期望的角度所得到的最佳预测器。而中位数则是通过最小化绝对误差的期望所得到的最佳预测器。也就是说，当 $c$ 是 $X$ 的分布函数的中位数时，$E[|X − c|]$ 的值最小。当 $X$ 是连续随机变量，且其分布函数和密度函数分别为 $F$ 和 $f$ 时，请证明如上的关于中位数的结论。提示：

    $$
    \begin{align}
    E[|X-c|] &= \int_{-\infty}^{\infty}{|x-c|f(x)\mathrm{d} x} \\
    &= \int_{-\infty}^{c}{|x-c|f(x)\mathrm{d} x} + \int_{c}^{\infty}{|x-c|f(x)\mathrm{d} x} \\
    &= \int_{-\infty}^{c}{(c-x)f(x)\mathrm{d} x} + \int_{c}^{\infty}{(x-c)f(x)\mathrm{d} x} \\
    &= cF(c) - \int_{-\infty}^{c}{xf(x)\mathrm{d} x} + \int_{c}^{\infty}{xf(x)\mathrm{d} x} - c[1 - F(c)]
    \end{align}
    $$

    然后利用微积分求 $c$ 的最小值。

36. 对于随机变量的分布函数 $F$，如果有 $F(m_p)=p$，则我们称 $m_p$ 为 $100p$-百分位数。如果一个随机变量的概率密度函数为：

    $f(x)=2e^{-2x}, \quad x \ge 0$

    求 $m_p$。

37. 一个社区由 100 对已婚夫妇组成。如果这个社区有 50 人去世了，那么剩下的 50 人中包含的夫妻数量的期望是多少？假设去世的人群随机来 $\left(\begin{array}{cc}  200 \\  50 \end{array}\right)$ 中的任何一组。提示：对于 $i=1,...,100$，令 

    $X_i = \begin{cases}1, \quad & 夫妻中没有人去世\\0, \quad & 其它\end{cases}$

38. 某个试验的成功概率为 $p$，如果独立执行 $n$ 次试验，计算其成功次数的期望和方差？计算中，试验之间的独立性是有必要的吗？

39. 假设 $X$ 取值 1、2、3、4 中的任何一个数的概率都是一致的，计算：
    
    * $E[X]$。
    * $Var(X)$。

40. 令 $p_i=P\{X=i\}$，假设 $p_1+p_2+p_3=1$。如果 $E[X]=2$，求：

    * $p_1$、$p_2$、$p_3$的最大值？
    * $Var(X)$ 的最小值？

41. 抛 3 次硬币，计算其正面向上的次数的期望和方差？

42. 该题涉及到 @exm-4_6_c 所示的友谊悖论。我们随机选择一个人 $X$，并从 $X$ 的好友中随机选择一个人 $W$。也就是说，在 $X$ 的 $n$ 位好友中，$W$ 是 $X$ 的好友的概率是 $\frac{1}{n}$。在 @exm-4_6_c 中，已经证明了 $E[f(W)] \ge E[f(X)]$，即随机选择的某个人的平均朋友数不大于其随机选择的朋友的平均朋友数。使用 @fig-4_5 给出的朋友圈证明该结论是正确的。

43. 某种零件的重量是一个随机变量 $X$，其概率密度函数为：

    $f(z)=\begin{cases} z-8, \quad & 8 \le z \le 9 \\ 10-z, \quad & 9 \lt z \le 10 \\ 0, \quad & 其它 \end{cases}$

    * 计算随机变量 $X$ 的期望和方差？
    * 工厂以 2 元的固定价格出售该零件，并且工厂保证：任何购买该零件的客户，如果发现该零件的重量低于 8.25，他们将退还货款。工厂生产该零件的成本与零件的重量关系为 $\frac{x}{15} + 0.35$。计算每个零件的预期利润？

44. 在某次给定的选举中，令随机变量 $X_i$ 表是对候选人 $i$ 的投票支持率，假设 $X_1$ 和 $X_2$ 的概率密度函数为：

    $f_{X_1, X_2}(x,y)=\begin{cases} 3(x+y), \quad & x \ge 0, y \ge 0, 0 \le x +y \le 1\\ 0, \quad & 其它 \end{cases}$

    * 计算 $X_1$ 和 $X_2$ 的边缘密度函数？
    * 对于 $i=1,2$，计算 $E[X_i]$ 和 $\textup{Var}(X_i)$？

45. 我们会根据产品的缺陷数量和生产厂家对产品进行分类。设随机变量 $X_1$ 表示单位产品的缺陷量（取值为 0，1，2，3），随机变量 $X_2$ 表示工厂编号（取值为 1，2）。随机选择一个产品，其联合概率质量函数如下表所示：

    |           | $X_2$ = 1      | $X_2$ = 2      |
    |-----------|----------------|:---------------|
    | $X_1$ = 0 | $\frac{1}{8}$  | $\frac{1}{16}$ |
    | $X_1$ = 1 | $\frac{1}{16}$ | $\frac{1}{16}$ |
    | $X_1$ = 2 | $\frac{3}{16}$ | $\frac{1}{8}$  |
    | $X_1$ = 3 | $\frac{1}{8}$  | $\frac{1}{4}$  |

    * 计算 $X_1$、$X_2$ 的边缘概率分布？
    * 计算 $E[X_1]$，$E[X_2]$，$\textup{Var}(X_1)$，$\textup{Var}(X_2)$，$\textup{Cov}(X_1, X_2)$？

46. 计算 习题 44 中的随机变量的相关性 $\textup{Corr}(X_1, X_2)$？

47. 验证 @eq-4_7_004？

48. 用数学归纳法证明 @eq-4_7_005_475？

49. 令 $X$ 的方差为 $\sigma_x^2$，$Y$ 的方差为 $\sigma_y^2$。
    
    * 当 $0 \le \textup{Var}(\frac{X}{\sigma_x} + \frac{Y}{\sigma_y})$ 时，有 $-1 \le \textup{Corr}(X,Y)$。
    * 当 $0 \le \textup{Var}(\frac{X}{\sigma_x} - \frac{Y}{\sigma_y})$ 时，有 $-1 \le \textup{Corr}(X,Y) \le 1$。
    * 当 $\textup{Var}(Z) = 0$ 时意味着 $Z$ 是一个常数。

    证明：
    
    * 当 $Y=ax +b$ 时，$\textup{Corr}(X,Y)$ 等于 1 或者 -1？
    * 当 $a > 0$ 时，$\textup{Corr}(X,Y) = 1$，当 $a < 0$ 时，$\textup{Corr}(X,Y) = -1$？

50. 一个试验的结果取值为 1、2、3，并且各自的概率为 $p_1,p_2,p_3$，并且 $sum_{i=1}^{3} = 1$。对于 $n$ 次这样的相互独立的试验，令 $N_i$ 表示实验结果为 $i$ 的次数，证明：

    * $\textup{Cov}(N_1, N_2) = -np_1p_2$?
    * 请解释为什么如上的协方差是负数？

    提示：对于 $i=1,...,n$， 

    令 $X_i=\begin{cases} 1, \quad & 第 i 次试验的结果为 1\\ 0, \quad & 第 i 次试验的结果不为 1 \end{cases}$。

    同理，令 $Y_j=\begin{cases} 1, \quad & 第 j 次试验的结果为 2\\ 0, \quad & 第 j 次试验的结果不为 2 \end{cases}$。

    然后证明 $N_1 = \sum_{i=1}^{n}X_i$，$N_2 = \sum_{j=1}^{n}Y_i$，然后利用 @prp-4_7_2 和 @thm-4_7_4 来证明 $\textup{Cov}(N_1, N_2)$。

51. 对于 @exr-4_5_f，计算 $\textup{Cov}(X_i,X_j)$，并用该结果证明 $\textup{Var}(X) = 1$。

52. 如果 $X_1$ 和 $X_2$ 的概率分布函数相同，证明：$\textup{Cov}(X_1 - X_2, X_1 + X_2) = 0$（注意，此处没有假定 $X_1$ 和 $X_2$ 相互独立）。

53. 假设 $X$ 的概率密度函数为：$f(x)=e^{-x}, \ x \gt 0$。

    * 计算 $X$ 的矩生成函数，并用结果来确定 $X$ 的均值和方差。
    * 直接根据概率密度函数计算 $X$ 的均值并用来该值来校验上一步中得出的结果。

54. 如果 $X$ 的概率密度函数为：$f(x) = 1, \ 0 \lt x \lt 1$。

    * 计算 $E[e^{tX}]$。
    * 对 $E[e^{tX}]$ 求 $n$ 阶导数以得到 $E[X^n]$，并校验结果。

55. 假设随机变量 $X$ 的均值和方差都是 20，计算 $P\{0 \le X \le 40\}$？

56. 根据过去的经验，教授知道学生期末考试的成绩是一个随机变量，并且其平均值为 75。
    
    * 学生考试成绩超过 85 的最大概率是多少？
    * 假设教授知道学生考试成绩的方差为 25，那么学生成绩在 65 到 85 之间的概率如何？
    * 最少有多少学生参加考试，才能确保该班级的平均水平在 70 到 80 之间的概率至少为 0.9？

57. 令 $X$ 的分布函数为 $F_X$，$Y$ 的分布函数为 $F_Y$，假设对于常数 $a > 0$，$b > 0$，有 

    $F_X(x) = F_Y\bigg(\frac{x-a}{b}\bigg)$

    * 用 $E[Y]$ 来确定 $E[X]$？
    * 用 $\textup{Var}(Y)$ 来确定 $\textup{Var}(X)$？

    提示：$X$ 与哪个随机变量的分布相同？