## 联合分布
对于一个给定的实验，我们不仅对单个 **随机变量** 的概率分布函数感兴趣；对两个或多个 **随机变量** 之间的关系，我们同样感兴趣。例如，在一项关于癌症可能原因的实验中，我们可能对每天平均吸烟数量与个体患癌症年龄之间的关系感兴趣。同样，工程师可能对钢板样品的抗剪强度和点焊直径之间的关系感兴趣。

为了描述两个 **随机变量** 之间的关系，我们定义 $X$ 和 $Y$ 的联合累积概率分布函数（*joint cumulative probability distribution function*）：

$$
F(x,y) = P\{X \le x,Y \le y\}
$$ {#eq-4_3_001}

至少在理论上，可以根据联合概率分布函数来计算任何关于 $X$ 和 $Y$ 的概率。例如，可以从 $X$ 和 $Y$ 的联合分布函数 $F$ 中得到 $X$ 的分布函数 $F_X$：

$$
\begin{align}
F_X(x) &= P\{X \le x\} \\
&= P\{X \le x, Y \le \infty \} \\
&= F(x, \infty)
\end{align}
$$ {#eq-4_3_002}

同理，$Y$ 的累积分布函数为 $F_Y(y) = F(\infty, y)$。

如果 $X$ 和 $Y$ 都是 **离散随机变量**，且其可能的取值分别为：$x_1, x_2, ...$ 和 $y_1, y_2, ...$，定义 $X$ 和 $Y$ 的联合概率质量函数（*joint probability mass function*）$p(x_i, y_j)$ 为：

$$
p(x_i, y_j) = P\{X = x_i, Y = y_j\}
$$ {#eq-4_3_003}

由于 $Y$ 必须取某个值 $y_j$，并且所有的 $y_j$ 之间都是 **互斥事件**，因此 **事件** $\{X = x_i\}$ 可以写作 $\{X = x_i, Y = Y_j\}$ 在所有 $j$ 上的并集。即：

$$
\{X = x_i\} = \bigcup_{all\ j}{\{X = x_i, Y = y_j\}}
$$ {#eq-4_3_004}

根据 **公理3**（@sec-3_4），有：

$$
\begin{align}
P\{X = x_i\} &= P\bigg(\bigcup_{all\ j}{\{X = x_i, Y = y_j\}}\bigg) \\
&= \sum_{all \ j}{P\{X = x_i, Y = y_j\}} \\
&= \sum_{all \ j}{p(x_i, y_j)}
\end{align}
$$ {#eq-4_3_005}

同理，我们可以得到 $P\{Y = y_j\}$：

$$
\begin{align}
P\{Y = y_i\} &= \sum_{all \ i}{P\{X = x_i, Y = y_j\}} \\
&= \sum_{all \ i}{p(x_i, y_j)}
\end{align}
$$ {#eq-4_3_006}

因此，**随机变量** 的联合概率质量函数总是可以决定单个 **随机变量** 的概率质量函数。然而，需要注意的是：反之，并不成立。即，即便知道 $P\{X = x_i\}$ 和 $P\{Y = y_j\}$ 的值也不能决定 $P\{X = x_i, Y = y_j\}$ 的值。

::: {#exm-4_3_a}
假设共有 12 块电池，其中包含 3 块新电池、4 块用过的但还有电量的电池、5 块没有电量的电池。现在，我们从这 12 块电池中随机抽取 3 块。令 $X$ 为抽取的电池中的新电池的数量，令 $Y$ 为抽取的电池中用过但还有电量的电池的数量。则 $X$ 和 $Y$ 的联合概率质量函数 $p(i, j) = P\{X = i, Y = j\}$ 为：

$$
p(i, j) = \frac{\left(\begin{array}{cc}  3 \\ i  \end{array}\right) \left(\begin{array}{cc}  4 \\ j  \end{array}\right) \left(\begin{array}{cc}  5 \\ 3 - i -j  \end{array}\right) }{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)}
$$

从 12 块电池里随机抽取 3 块电池的抽取方式为 $\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)$。根据 @sec-3_5_1 中的 **计数基本原理**，抽取的 3 块电池中恰好有 $i$ 块新电池、$j$ 块用过但还有电量的电池、$3 - i - j$ 块没有电量的电池的抽取方式为 $\left(\begin{array}{cc}  3 \\ i  \end{array}\right) \left(\begin{array}{cc}  4 \\ j  \end{array}\right) \left(\begin{array}{cc}  5 \\ 3 - i -j  \end{array}\right)$。因此：

$$
\begin{align}
p(0, 0) &= \frac{\left(\begin{array}{cc}  5 \\ 3  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{10}{220} \\
p(0, 1) &= \frac{\left(\begin{array}{cc}  4 \\ 1  \end{array}\right) \left(\begin{array}{cc}  5 \\ 2  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{40}{220} \\
p(0, 2) &= \frac{\left(\begin{array}{cc}  4 \\ 2  \end{array}\right) \left(\begin{array}{cc}  5 \\ 1  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{30}{220} \\
p(0, 3) &= \frac{\left(\begin{array}{cc}  4 \\ 3  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{4}{220} \\
p(1, 0) &= \frac{\left(\begin{array}{cc}  3 \\ 1  \end{array}\right) \left(\begin{array}{cc}  5 \\ 2  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{30}{220} \\
p(1, 1) &= \frac{\left(\begin{array}{cc}  3 \\ 1  \end{array}\right) \left(\begin{array}{cc}  4 \\ 1  \end{array}\right) \left(\begin{array}{cc}  5 \\ 1  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{60}{220} \\
p(1, 2) &= \frac{\left(\begin{array}{cc}  3 \\ 1  \end{array}\right) \left(\begin{array}{cc}  4 \\ 2  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{18}{220} \\
p(2, 0) &= \frac{\left(\begin{array}{cc}  3 \\ 2  \end{array}\right) \left(\begin{array}{cc}  5 \\ 1  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{15}{220} \\
p(2, 1) &= \frac{\left(\begin{array}{cc}  3 \\ 2  \end{array}\right) \left(\begin{array}{cc}  4 \\ 1  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{12}{220} \\
p(3, 0) &= \frac{\left(\begin{array}{cc}  3 \\ 3  \end{array}\right)}{\left(\begin{array}{cc}  12 \\ 3  \end{array}\right)} = \frac{1}{220}
\end{align}
$$

可以通过 @tbl-4_1 的表格格式来更简单的表示如上的概率。

|          | $j$ = 0 | $j$ = 1 | $j$ = 2 | $j$ = 3 | $P\{X = i\}$ |
|----------|-------|:------|:------|:------|:---------|
| $i$ = 0    |$\frac{10}{220}$|$\frac{40}{220}$|$\frac{30}{220}$|$\frac{4}{220}$|$\frac{84}{220}$ |
| $i$ = 1    |$\frac{30}{220}$|$\frac{60}{220}$|$\frac{10}{220}$|0|$\frac{108}{220}$|
| $i$ = 2    |$\frac{15}{220}$|$\frac{12}{220}$|0|0|$\frac{27}{220}$|
| $i$ = 3    |$\frac{1}{220}$|0|0|0|$\frac{1}{220}$|
| $P\{Y = j\}$ |$\frac{56}{220}$|$\frac{112}{220}$|$\frac{48}{220}$|$\frac{4}{220}$|          |

: $P\{X=i, Y=j\}$ {#tbl-4_1}

读者应该注意，通过计算行的和所得到的 $X$ 的概率质量函数和 @eq-4_3_005 的结果是一致的；同时，通过计算列的和所得到的 $Y$ 的概率质量函数和 @eq-4_3_006 的结果也是一致的。因为 $X$ 和 $Y$ 的各自的概率质量函数出现在 @tbl-4_1 所示的联合概率分布表的边缘（*margin*），因此，我们又常常称 $X$ 和 $Y$ 的各自的概率质量函数为 **边缘概率质量函数**（*marginal probability mass function*）。应该注意的是，为了检查类似 @tbl-4_1 这样的表的正确性，我们可以对表中的最后一行（或最右一列）求和，并验证其结果是否为 1。（为什么最后一行或最右一列的和必须等于 1？）  $\blacksquare$
:::

::: {#exm-4_3_b}
假设某个社区中，15% 的家庭没有孩子，20% 的家庭有 1 个孩子，35% 的家庭有 2 个孩子，30% 的家庭有 3 个孩子。又假设对于每个家庭而言，每个孩子是男孩或女孩的可能性相等并且独立。

如果从这个社区中随机选择一个家庭，那么这个家庭中男孩的数量 $B$ 和女孩的数量 $G$ 具有 @tbl-4_2 所示的联合概率质量函数。

|          | $j$ = 0 | $j$ = 1 | $j$ = 2 | $j$ = 3 | $P\{B = i\}$ |
|----------|-------|:------|:------|:------|:---------|
| $i$ = 0    |0.15|0.10|0.0875|0.0375|0.3750|
| $i$ = 1    |0.10|0.175|0.1125|0|0.3875|
| $i$ = 2    |0.0875|0.1125|0|0|0.2000|
| $i$ = 3    |0.0375|0|0|0|0.0375|
| $P\{G = j\}$ |0.3750|0.3875|0.2000|0.0375|          |

: $P\{B=i, G=j\}$ {#tbl-4_2}

于是，我们可以得到如下的概率：

$$
\begin{align}
P\{B=0, G=0\} &= P\{没有孩子\} = 0.20 \cdot \frac{1}{2} = 0.15 \\
P\{B=0, G=1\} &= P\{有 1 个孩子且为女孩\} = 0.35 \cdot (\frac{1}{2})^2 = 0.1 \\
P\{B=0, G=3\} &= P\{有 3 个孩子且都为女孩\} = = 0.30 \cdot (\frac{1}{2})^3 = 0.0375 \\
\end{align}
$$

您可以验证 @tbl-4_2 的其余部分，通过 @tbl-4_2 我们可以知道，所选择的家庭至少有一个女孩的概率为 0.625（$1-P\{B=i, G=0\}$）。$\blacksquare$
:::

$X$ 和 $Y$ 是两个连续 **随机变量**，对于 $x \in (-\infty, \infty)$ 和 $y \in (-\infty, \infty)$，对于任何一个 $x$ 和 $y$ 构成的 *数据对* 集合 $C$（$C$ 是一个二维平面中的集合），如果存在函数 $f(x,y)$，使得：

$$
P\{(X,Y) \in C\} = \iint_{(x,y) \in C}{f(x,y)\mathrm{d} x \mathrm{d} y}
$$ {#eq-4_3_007_433}

我们称 $X$ 和 $Y$ 是联合连续随机变量，称函数 $f(x,y)$ 为 $X$ 和 $Y$ 的 **联合概率密度函数**（*joint probability density function*）。如果令 $A$ 和 $B$ 为两个实数集，并令 $C = \{(x,y): x \in A, y \in B\}$，则 @eq-4_3_007_433 可以写作：

$$
P\{X \in A, Y \in B\} = \int_{B} \int_{A} {f(x,y)\mathrm{d} x \mathrm{d} y}
$$ {#eq-4_3_008_434}

因为：

$$
\begin{align}
F(a,b) &= P\{X \in (-\infty, a], Y \in (-\infty, b]\} \\
&= \int_{-\infty}^{b} \int_{-\infty}^{a} {f(x,y)\mathrm{d} x \mathrm{d} y}
\end{align}
$$ {#eq-4_3_009}

所以，对 @eq-4_3_009 两边微分得到：

$$
\frac{\partial^{2}{F(a,b)}}{\partial a \ \partial b} = f(a,b)
$$ {#eq-4_3_010}

也就是说，联合概率密度函数 $f(\cdot)$ 是联合概率分布函数 $F(\cdot)$ 的偏微分。根据 @eq-4_3_008_434，我们有：

$$
\begin{align}
P\{a \lt X \lt a + \Delta a, b \lt Y \lt b + \Delta b\} &= \int_{b}^{b + \Delta b} \int_{a}^{a + \Delta a} {f(x,y)\mathrm{d} x \mathrm{d} y} \\ 
&\approx f(a,b) \Delta a \Delta b
\end{align}
$$ {#eq-4_3_011}

因为 $\Delta a$ 和 $\Delta b$ 都是非常小的数，并且 $f(x,y)$ 在 $(a,b)$ 处是连续的。因此 $f(a,b)$ 是对 $(X,Y)$ 靠近 $(a,b)$ 的可能性大小的一种度量。

如果 $X$ 和 $Y$ 是联合连续随机变量，则 $X$ 和 $Y$ 各自都是连续随机变量，则 $X$ 的概率密度函数为：

$$
\begin{align}
P\{X \in A\} &= P\{X \in A, Y \in (-\infty, \infty)\} \\
&= \int_{A} \int_{-\infty}^{\infty} {f(x,y) \mathrm{d} y\mathrm{d} x} \\
&= \int_{A}{f_X{(x)\mathrm{d} x}} \\
其中\ f_X{(x)} &= \int_{-\infty}^{\infty}{f(x,y) \mathrm{d} y}
\end{align}
$$ {#eq-4_3_012_435}

同理，$Y$ 的概率密度函数为：

$$
\begin{align}
P\{Y \in B\} &= P\{X \in (-\infty, \infty), Y \in B\} \\
&= \int_{B} \int_{-\infty}^{\infty} {f(x,y)\mathrm{d} x \mathrm{d} y} \\
&= \int_{B}{f_Y{(y) \mathrm{d} y}} \\
其中\ f_Y{(y)} &= \int_{-\infty}^{\infty}{f(x,y)\mathrm{d} x}
\end{align}
$${#eq-4_3_013_436}

::: {#exr-4_3_c}
$X$ 和 $Y$ 的联合概率密度函数如下：

$$
f(x,y) = \begin{cases}
2e^{-x}e^{-2y}, \quad & 0 \lt x \lt \infty, 0 \lt y \lt \infty \\
0, \quad & otherwise
\end{cases}
$$

计算：

* $P\{X \gt 1, Y \lt 1\}$
* $P\{X \lt Y\}$
* $P\{X \lt a\}$
:::

::: {#sol-4_3_c}

::: {.callout-tip title="$P\\{X \gt 1, Y \lt 1\\}$"}
$$
\begin{align}
P\{X \gt 1, Y \lt 1\} &= \int_{0}^{1} \int_{1}^{\infty} {2e^{-x}e^{-2y}\mathrm{d} x \mathrm{d} y} \\
&= \int_{0}^{1}{2e^{-2y}(-e^{-x} \big |_{1}^{\infty})} \mathrm{d} y \\
&= e^{-1}\int_{0}^{1}2e^{-2y} \mathrm{d} y \\
&= e^{-1}(1-e^{-2})
\end{align}
$$
:::

::: {.callout-tip title="$P\\{X \lt Y\\}$"}
$$
\begin{align}
P\{X \lt Y\} &= \iint_{(x,y):x \lt y}{2e^{-x}e^{-2y}\mathrm{d} x \mathrm{d} y} \\
&= \int_{0}^{\infty} \int_{0}^{y} {2e^{-x}e^{-2y}\mathrm{d} x \mathrm{d} y} \\
&= \int_{0}^{\infty}{2e^{-2y}(1-e^{-y}) \mathrm{d} y} \\
&= \int_{0}^{\infty}{2e^{-2y} \mathrm{d} y} - \int_{0}^{\infty}{2e^{-3y} \mathrm{d} y} \\
&= 1-\frac{2}{3} \\
&= \frac{1}{3}
\end{align}
$$
:::

::: {.callout-tip title="$P\\{X \lt a\\}$"}
$$
\begin{align}
P\{X \lt a\} &= \int_{0}^{a} \int_{0}^{\infty}{2e^{-2y}e^{-x} \mathrm{d} y\mathrm{d} x} \\
&= \int_{0}^{a}{e^{-x}\mathrm{d} x} \\
&= 1-e^{-a} 
\end{align}
$$
:::

$\blacksquare$
:::

### 独立随机变量
对于任意的两个实数集 $A$ 和 $B$，如果随机变量 $X$ 和 $Y$ 满足 @eq-4_3_014_437，我们称 $X$ 和 $Y$ 是相互独立的。

$$
P\{X \in A, Y \in B\} = P\{X \in A\}P\{Y \in B\}
$$ {#eq-4_3_014_437}

换句话说，对于所有的 $A$、$B$，如果事件 $E_A={X \in A}$ 和 $E_B={Y \in B}$ 是相互独立的，那么 **随机变量** $X$ 和 $Y$ 也是相互独立的。

根据 @sec-3_4 中的概率论 **三大公理**，对于所有的 $a$、$b$，@eq-4_3_014_437 满足：

$$
P\{X \le a, Y \le b\} = P\{X \le a\}P\{Y \le b\}
$$ {#eq-4_3_015}

因此，就 $X$ 和 $Y$ 的联合分布函数 $F$ 而言，如果 $F(a,b) = F_X(a)F_Y(b)$，则 $X$ 和 $Y$ 是独立的。

当 $X$ 和 $Y$ 是离散随机变量时，@eq-4_3_014_437 等价于：

$$
p(x,y)=p_X{(x)}p_Y{(y)} \quad for \ all \ x,y
$$ {#eq-4_3_016_438}

其中，$p_X$ 和 $p_Y$ 分别为 $X$ 和 $Y$ 的概率质量函数。

如果 @eq-4_3_014_437 成立，那么我们令 $A={x}$，$B={y}$，于是我们能够得到 @eq-4_3_016_438。此外，如果 @eq-4_3_016_438 成立，那么对于任何集合 $X \in A$、$Y \in B$，都有：

$$
\begin{align}
P\{X \in A, Y \in B\} &= \sum_{y \in B}\sum_{x \in A}{p(x,y)} \\
&= \sum_{y \in B}\sum_{x \in A}{p_X{(x)}p_Y{(y)}} \\
&= \sum_{y \in B}{p_Y{(y)}} \sum_{x \in A}{p_X{(x)}} \\
&= P\{Y \in B\}P\{X \in A\} \\
&= P\{X \in A\}P\{Y \in B\}
\end{align}
$$

即，@eq-4_3_016_438 成立也意味着 @eq-4_3_014_437 成立。因此，@eq-4_3_014_437 和 @eq-4_3_016_438 是等价的。

同理，当 $X$ 和 $Y$ 是连续随机变量时，@eq-4_3_014_437 等价于：对于所有的 $x$、$y$，都有 $f(x,y) = f_X(x)f_Y(y)$。如果一个随机变量 $X$ 的取值不会改变另一个随机变量 $Y$ 的分布，那么我们可以大致认为 $X$ 和 $Y$ 是独立的。不独立的随机变量称为 **依赖随机变量**。

::: {#exr-4_3_d}
假设 $X$ 和 $Y$ 是两个独立随机变量，其概率密度函数均为：

$$
f(x)=\begin{cases}
e^{-x}, \quad & x \gt 0 \\
0, \quad & otherwise
\end{cases}
$$

求 随机变量 $\frac{X}{Y}$ 的概率密度函数？
:::

::: {#sol-4_3_d}
首先，求 $\frac{X}{Y}$ 的概率分布函数 $F$：

$$
\begin{align}
\forall a & \gt 0, \\ 
F_{\frac{X}{Y}}{(a)} &= P\{\frac{X}{Y} \le a\} \\
&= \iint_{\frac{x}{y} \le a}{f(x,y)\mathrm{d} x \mathrm{d} y} \\
&= \iint_{\frac{x}{y} \le a}{e^{-x}e^{-y}\mathrm{d} x \mathrm{d} y} \\
&= \int_{0}^{\infty} \int_{0}^{ay} {e^{-x}e^{-y}\mathrm{d} x \mathrm{d} y} \\
&= \int_{0}^{\infty} {(1-e^{-ay})e^{-y} \mathrm{d} y} \\
&= \bigg(-e^{-y} + \frac{e^{-(a+1)y}}{a+1}\bigg) \bigg | _{0}^{\infty} \\
&= 1 - \frac{1}{a+1}
\end{align}
$$

对 $F_{\frac{X}{Y}}{(a)}$ 求导得到 $f_{\frac{X}{Y}(a)} = \frac{1}{(1+a)^2}$。 $\blacksquare$
:::

我们可以用定义 2 个 **随机变量** 的联合概率分布函数的方式来定义 $n$ 个 **随机变量**的联合概率分布函数。对于 $n$ 个 **随机变量** $X_1,X_2,...,X_n$，其联合累积概率分布函数 $F(a_1,a_2,...,a_n)$ 为：

$$
F(a_1,a_2,...,a_n) = P\{X_1 \le a_1, X_2 \le a_2,..., X_n \le a_n\}
$$ {#eq-4_3_017}

对于离散随机变量，则其联合概率质量函数 $p(x_1,x_2,...,x_n)$ 为：

$$
p(x_1,x_2,...,x_n) = P\{X_1=x_1, X_2=x_2,..., X_n=x_n\}
$$ {#eq-4_3_018}

此外，对于 $n$ 维空间中的集合 $C$，如果存在一个函数 $f(\cdot)$ 使得：

$$
P\{(X_1,X_2,...,X_n) \in C\} = \idotsint_{(x_1,...,x_n) \in C}{f(x_1,...,x_n)\mathrm{d} x_1 \cdots \mathrm{d} x_n} 
$$ {#eq-4_3_019}

我们称 $f(x_1,...,x_n)$ 为这 $n$ 个联合连续随机变量的联合概率密度函数。

特殊的，对于任意的 $n$ 个实数集 $A_1,A_2,...,A_n$：

$$
\begin{align}
P\{X_1 \in A_1, X_2 \in A_2, ..., X_n \in A_n\} &= \\
\int_{A_n} \int_{A_{n-1}} \cdots \int_{A_1}{f(x_1,...,x_n)\mathrm{d} x_1\mathrm{d} x_2 \cdots \mathrm{d} x_n} &
\end{align}
$$ {#eq-4_3_020}

当然，也可以为两个之上的 **随机变量** 定义独立性。一般来的，对于 $n$ 个 **随机变量** $X_1,X_2,...,X_n$，如果对于所有实数集 $A_1,A_2,...,A_n$ 都有：

$$
P\{X_1 \in A_1, X_2 \in A_2, ..., X_n \in A_n\} = \Pi_{i=1}^{n}{P\{X_i \in A_i\}}
$$ {#eq-4_3_021}

则我们称这 $n$ 个随机变量时相互独立的。正如 @eq-4_3_014_437 和 @eq-4_3_016_438 所述，@eq-4_3_021 等价于 @eq-4_3_022：

$$
P\{X_1 \le a_1, X_2 \le a_2, ..., X_n \le a_n\} = \Pi_{i=1}^{n}{P\{X_i \in a_i\}}
$$ {#eq-4_3_022}

对于一个随机变量的无限集合 $S$，如果 $S$ 的所有的子集中的 **随机变量** 均是独立的，我们说 $S$ 中的所有随机变量之间是相互独立的。（@def-3_8_002 的一般形式）

::: {#exm-4_3_e}
假设某支股票的股价的连续每日变化是一个独立且同分布的随机变量，其概率质量函数为：

$$
P\{第 i 日变化\} = \begin{cases}
-3, \quad &概率为 0.05 \\
-2, \quad &概率为 0.10 \\
-1, \quad &概率为 0.20 \\
0, \quad &概率为 0.30 \\
1, \quad &概率为 0.20 \\
2, \quad &概率为 0.10 \\
3, \quad &概率为 0.05
\end{cases}
$$

令 $X_i$ 表示第 $i$ 天的股价变化，那么，这只股票在未来的连续 3 天里，股价分别上涨 1%、2%、0% 的概率为：

$$
P\{X_1=1, X_2=2, X_3=0\} = 0.20 \cdot 0.10 \cdot 0.30 = 0.006 \quad \blacksquare
$$
:::

### 条件分布
对于两个 **随机变量**，通常可以利用其中一个变量在另一个变量的给定值的情况下的条件分布来确定这两个 **随机变量** 之间的关系。回顾一下，对于任意两个事件 $E$ 和 $F$，只要 $P(F)>0$，则在给定 $F$ 条件下 $E$ 的条件概率为：

$$
P(E|F)=\frac{P(EF)}{P(F)}
$$

因此，如果 $X$ 和 $Y$ 是两个离散随机变量，那么在给定 $Y=y$ 的条件下，$X$ 的条件概率质量函数为：

$$
\begin{align}
p_{X|Y}(x|y) &= P\{X=x | Y=y\} \\
&= \frac{P\{X=x, Y=y\}}{P\{Y=y\}} \\
&= \frac{p(x,y)}{p_Y(y)}
\end{align}
$$

其中，对于所有的 $y$，$p_Y(y) \gt 0$。

::: {#exr-4_3_f}
在 @exm-4_3_b 中，如果我们知道所选择的这个家庭有 1 个女孩，计算该家庭的小孩中男孩数量的条件概率质量函数。
:::

::: {#sol-4_3_f}
首先，根据 @tbl-4_2，$P\{G=1\}=0.3875$，因此，

$$
\begin{align}
P\{B=0 | G=1\} &= \frac{P\{B=0, G=1\}}{P\{G=1\}} = \frac{0.10}{0.3875} = \frac{8}{31} \\
P\{B=1 | G=1\} &= \frac{P\{B=1, G=1\}}{P\{G=1\}} = \frac{0.175}{0.3875} = \frac{14}{31} \\
P\{B=2 | G=1\} &= \frac{P\{B=2, G=1\}}{P\{G=1\}} = \frac{0.1125}{0.3875} = \frac{9}{31} \\
P\{B=3 | G=1\} &= \frac{P\{B=3, G=1\}}{P\{G=1\}} = 0 \\
\end{align}
$$

因此，在有 1 个女孩的条件下，该家庭至少有 1 个男孩的概率为 $\frac{23}{31}$。$\blacksquare$
:::

::: {#exr-4_3_g}
假设 **随机变量** $X$、$Y$ 的联合概率质量函数 $p(x,y)$ 为：

$$
p(0,0)=0.4, \quad p(0,1)=0.2, \quad p(1,0)=0.1, \quad p(1,1)=0.3
$$

计算 $P\{X|Y=1\}$？
:::

::: {#sol-4_3_g}
$$
\begin{align}
\because\ P\{Y = 1\} &= \sum_{x}p(x,1) = p(0,1) + p(1,1) = 0.5 \\
\therefore\ P\{X=0|Y=1\} &= \frac{p(0,1)}{P\{Y=1\}} = \frac{2}{5} \\
P\{X=1|Y=1\} &= \frac{p(1,1)}{P\{Y=1\}} = \frac{3}{5} \qquad \blacksquare
\end{align}
$$
:::

如果 $X$ 和 $Y$ 的联合概率密度函数为 $f(x,y)$，则在 $Y=y$ 的条件下，$X$ 的条件概率密度函数为：

$$
f_{X|Y}(x|y) = \frac{f(x,y)}{f_Y{(y)}}, \quad \forall y: \ f_Y(y) \gt 0
$$ {#eq-4_3_023}

在 @eq-4_3_023 的左边乘以 $\Delta x$，右边乘以 $\frac{\Delta x \Delta y}{\Delta y}$ 得到：

$$
\begin{align}
f_{X|Y}(x|y) \Delta x &= \frac{f(x,y) \Delta x \Delta y}{f_Y{(y)} \Delta y} \\
& \approx \frac{P\{x \le X \le x + \Delta x, y \le Y \le y + \Delta y\}}{P\{y \le Y \le y + \Delta y\}} \\
&= P\{x \le X \le x + \Delta x\ | y \le Y \le y + \Delta y\}
\end{align}
$$ {#eq-4_3_024}

也就是说，对于非常小的 $\Delta x$ 和 $\Delta y$ ，$f_{X|Y}(x|y) \Delta x$ 表示在 $Y \in [y, y + \Delta y]$ 的条件下，$X \in [x, x + \Delta x]$ 的条件概率。

我们可以使用条件概率密度函数来定义：在给定一个随机变量的值下，另一个随机变量的条件概率。也就是说，如果 $X$ 和 $Y$ 都是连续 **随机变量**，那么，对于任何集合 $A$，都有：

$$
P\{X \in A, Y=y\} = \int_{A}f_{X|Y}(x|y)\mathrm{d} x
$$

::: {#exr-4_3_h}
$X$ 和 $Y$ 的联合概率密度函数为：

$$
f(x,y) = \begin{cases}
\frac{12}{5}x(2-x-y), \quad & 0 \lt x \lt 1, 0 \lt y \lt 1\\
0, \quad & otherwise
\end{cases}
$$

计算 $Y=y: 0 \lt y \lt 1$ 下，$X$ 的条件密度函数 $f_{X|Y}(x|y)$。
:::

::: {#sol-4_3_h}
对于 $0 \lt x \lt 1$，$0 \lt y \lt 1$，我们有：

$$
\begin{align}
f_{X|Y}(x|y) &= \frac{f(x,y)}{f_Y(y)} \\
&= \frac{f(x,y)}{\int_{-\infty}^{\infty}{f(x,y)\mathrm{d} x}} \\
&= \frac{x(2-x-y)}{\int_0^1{x(2-x-y)\mathrm{d} x}} \\
&= \frac{x(2-x-y)}{\frac{2}{3} - \frac{y}{2}} \\
&= \frac{6x(2-x-y)}{4-3y} \quad \blacksquare
\end{align}
$$
:::
