## 方差
给定一个 **随机变量** $X$ 及其概率分布函数，如果我们能够定义某些合适的度量并用来总结质量函数的基本特征，那将是非常有用的。**期望** $E[X]$ 就是其中的一个度量。虽然 $E[X]$ 生成了 $X$ 的可能值的加权平均数，但 $E[X]$ 却没有告诉我们 $X$ 的这些可能值的变化。例如，当 **随机变量**  $W$、$Y$、$Z$ 的概率质量函数分别为：

$W=0 \quad 概率为 1$

$Y=\begin{cases} -1, \quad & 概率为 \frac{1}{2}\\ 1, \quad & 概率为 \frac{1}{2} \end{cases}$

$Y=\begin{cases} -100, \quad & 概率为 \frac{1}{2}\\ 100, \quad & 概率为 \frac{1}{2} \end{cases}$

虽然这三个 **随机变量** 的期望都是 0，但是 $Y$ 的变化幅度比 $W$ 要大，同时 $Z$ 的变化幅度比 $Y$ 也要大。

因为我们期望 $X$ 在其平均值 $E[X]$ 附近取值，所以可以利用 $X$ 的实际取值与 $E[X]$ 之间的距离来测量 $X$ 的变化。可以同过量化 $E[|X − \mu|]$ 来计算 $X$ 的实际取值与 $E[X]$ 之间的距离，其中 $\mu = E[X]$，$|X − \mu|$ 代表 $X - \mu$ 的绝对值。然而，事实证明，在数学上处理 $E[|X − \mu|]$ 极其麻烦。因此，我们通常会用一个更容易处理的数据——即 $X$ 与其平均值之差的平方的期望。

::: {#def-4_6_001}
如果 $X$ 是一个均值为 $\mu$ 的 **随机变量**，则 $X$ 的 **方差**（*variance*）$\textup{Var}(X)$ 为：$\textup{Var}(X) = E[(X - \mu)^2]$。
:::

于是，我们有如下的推导：

$$
\begin{align}
\textup{Var}(X) &= E[(X - \mu)^2] \\
&= E[X^2 - 2 \mu X + \mu ^2] \\
&= E[X^2] - 2 \mu E[X] + \mu ^2 \\
&= E[X^2] - (E[X])^2 \quad \because E[X] = \mu \\
\end{align}
$$ 

所以有：

$$
\textup{Var}(X) = E[X^2] - (E[X])^2
$$ {#eq-4_6_001_461}

换句话说，$X$ 的方差等于 $X$ 的平方的期望减去 $X$ 的期望的平方。实际上，通常，@eq-4_6_001_461 是计算 $\textup{Var}(X)$ 的最简单的方法。

::: {#exr-4_6_a}
令 $X$ 为抛一个骰子的点数，计算 $\textup{Var}(X)$。
::: 

::: {#sol-4_6_a}
因为 $P\{X=i\}=\frac{1}{6}$，$i=1,2,...,6$，因此：

$E[X^2] = \sum_{i=1}^{6}{i^2 \cdot P\{X=i\}} = \frac{91}{6}$。

在 @exr-4_4_a 中，我们知道 $E[X]=\frac{7}{2}$，根据 @eq-4_6_001_461：

$\textup{Var}(X)=E[X^2] - (E[X])^2 = \frac{91}{6} - (\frac{7}{2})^2 = \frac{35}{12}$。$\blacksquare$
::: 

::: {#exm-4_6_b}
**指示随机变量的方差**，对于事件 $A$，指示随机变量 $I$ 为：

$I = \begin{cases} 1, \quad & 如果 A 发生\\ 0, \quad & 如果 A 不发生 \end{cases}$

根据 @exm-4_4_b 有，$E[I] = P(A)$，所以有：
$$
\begin{align}
\textup{Var}(I) &= E[I^2] - (E(I))^2 \\
&= E[I] - (E[I])^2 \quad \because I^2=I \\
&= E[I](1-E[I]) \\
&= P(A)(1-P(A)) \qquad \blacksquare
\end{align}
$$
:::

因为 $(X - \mu)^2 \ge 0$，因此，$\textup{Var}(X) = E[(X - \mu)^2] \ge 0$，根据 @eq-4_6_001_461 有：

$$
E[X^2] \ge \mu^2
$$ {#eq-4_6_002}

也就是说，一个 **随机变量** 的平方的 **期望** 至少与其 **期望** 的平方一样大。

::: {#exm-4_6_c}
**友谊悖论**（*friendship paradox*）表明：平均而言，你的朋友的朋友数量比你的朋友数量要更多。更正式地，假设某个人群中有 $n$ 个人，标记为 $1,2,...,n$，这些人中的某些人之间是朋友。这个 *朋友网络* （*friendship network*）可以用 **图**（*graphic*）来表示：用顶点表示每个人，然后用顶点与顶点之间的连线表示这些人是朋友。例如，如 @fig-4_5 所示，该社区中有 4 个人，第 1 个人和第 2 个人是朋友，第 1 个人和第 3 个人是朋友，第 1 个人和第 4 个人是朋友，第 2 个人和第 4 个人是朋友。

```{r}
#| label: fig-4_5
#| fig-cap: "一个朋友网络图"
#| warning: false
#| 

library(igraph)
 
vertices <- c(1, 2, 3, 4)  
edges <- cbind(c(1, 1, 1, 2), c(3, 2, 4, 4))  
g <- graph_from_edgelist(edges, directed = FALSE)  
V(g)$label <- vertices

plot(g, vertex.label.cex = 1.5)
```

令 $f(i)$ 表示第 $i$ 个人的朋友数，令 $f=\sum_{i=1}^{n}{f(i)}$。在 @fig-4_5 中，$f(1)=3$，$f(2)=2$，$f(3)=1$，$f(4)=2$，$f = 8$。

我们随机选择一个人，并用 $X$ 表示，$X$ 可以是 $1,2,...,n$ 中的任何一个，并且选取到的概率是一致的。也就是说，

$P(X=i)=\frac{1}{n}$

根据 @prp-4_5_1，$X$ 的朋友数量的期望 $E[f(X)]$ 为：

$E[f(X)] = \sum_{i=1}^{n}{f(i)P(X=i)}=\sum_{i=1}^{n}{\frac{f(i)}{n}} = \frac{f}{n}$

假设这 $n$ 个人中的每个人都将他所有朋友的名字分别写在了一张单独的纸上（一个名字一张纸）。因此，一个有 $k$ 个朋友的人将使用 $k$ 张纸。因为第 $i$ 个人有 $f(i)$ 个朋友，因此总共会有 $\sum_{i=1}^{n{f(i)}}$ 张纸来记录名字。

现在随机选择一张纸，令 $Y$ 表示纸上的名字，并计算所选纸上的人的朋友数量的期望 $E[f(Y)]$。

* 首先，因为第 $i$ 个人有 $f(i)$ 个朋友， 所以有 $f(i)$ 张纸上的名字写的是 $i$，因此，所选择的纸上的名字为 $i$ 的概率为 $\frac{f(i)}{f}$，即：
  
  $P(Y=i)=\frac{f(i)}{f}, i = 1,...,n$
* 于是，$E[f(Y)] = \sum_{i=1}^{n}{f(i)P(Y=i)} = \frac{\sum_{i=1}^{n}{f^2(i)}}{f}$。
* 因为 $P(X=i)=\frac{1}{n}$，$E[f(X)] = \frac{f}{n}$，所以 $f = \frac{E[f(x)]}{P(X=i)}$，所以有：
  
  $$
  \begin{align}
  E[f(Y)] &= \frac{\sum_{i=1}^{n}{f^2(i)}}{f} \\
  &= \frac{\sum_{i=1}^{n}{f^2(i)P(X=i)}}{E[f(X)]} \\
  &= \frac{E[f^2(X)]}{E[f(X)]} \\
  &\ge E[f(X)], \ \because E[X^2] \ge \mu^2
  \end{align}
  $$

因此，$E[f(X)] \le E[f(Y)]$，这表明随机选择的某个人的平均朋友数量小于或等于其朋友的平均朋友数量。

::: {.callout-tip title="备注"}
从直觉上讲，友谊悖论的原因在于：

* 选择 $X$ 的概率是相同的（$X$ 为 $n$ 个人中的任何一个的概率是相同）。
* 选择 $Y$ 的概率与其朋友数量成正比。
* 所以，一个人拥有的朋友越多，这个人就越有可能是 $Y$。因此，$Y$ 偏向于拥有大量朋友的那个人。
* 因此，$Y$ 拥有的平均朋友数量大于 $X$ 拥有的平均朋友数量也就不足为奇了。
:::

::: {.callout-note}
“友谊悖论”（friendship paradox）这一现象由社会学家斯科特·费尔德（Scott L. Feld）于1991年发现，其原因在于，那些在社交网络中连接较为广泛的人（即拥有较多朋友的人）更容易被其他人选为朋友，从而使得在统计上呈现出这样看似矛盾的结果。
:::

$\blacksquare$
:::


对于任意的常数 $a$、$b$，有：

$$
\textup{Var}(aX + b) = a^2 \textup{Var}(X)
$$ {#eq-4_6_003_462} 

::: {.proof}
令 $\mu = E[X]$，根据 @cor-4_5_2 有 $E[aX + b] = a \mu + b$，根据方差的定义 @def-4_6_001 有：

$$
\begin{align}
\textup{Var}(aX + b) &= E[(aX + b - E[aX + b])^2] \\
&= E[(aX + b - a \mu - b)^2] \\
&= E[(aX - a \mu)^2] \\
&= E[a^2(X - \mu)^2] \\
&= a^2E[(X - \mu)^2] \\
&= a^2\textup{Var}(X)
\end{align}
$$ 
:::

@eq-4_6_003_462 中，对于特定的 $a$ 和 $b$ 可以导出其他的推论。例如，如果 $a=0$，则有：

$\textup{Var}(b) = 0$

即：常数的方差为 0（这符合直觉吗？）。类似的，令 $a = 1$，则有：

$\textup{Var}(X + b) = \textup{Var}(X)$

也就是说，**随机变量** 加一个常数的方差等于该 **随机变量** 的方差。最后，令 $b=0$，则有：

$\textup{Var}(aX) = a^2\textup{Var}(X)$

$\sqrt{\textup{Var}(X)}$ 称为 $X$ 的标准差（*standard deviation*）。**随机变量** 的标准差和均值具有相同的单位。

::: {.callout-tip title="备注"}
与 **均值** 是质量分布的 **重心** 的概念类似，在力学中，**方差** 代表 **惯性矩**（*the moment of inertia*）。
:::

::: {.callout-note title="惯性矩"}
在力学中，惯性矩（又称转动惯量）是一个用于描述物体绕轴转动时惯性大小的物理量。

具体来说，它衡量了物体对于绕某一特定轴转动的抵抗能力。惯性矩越大，物体绕该轴转动就越困难，也就越不容易改变其转动状态；反之，惯性矩越小，物体就相对更容易改变其转动状态。

其数学定义通常是对于质量分布为 $m_i$、距离转动轴为 $r_i$ 的多个质点组成的物体，惯性矩等于各质点质量与该质点到转动轴距离平方的乘积之和，即 $I=\sum m_ir_i^2$。

例如，对于一个均匀圆盘，其绕中心轴的惯性矩与圆盘的质量和半径的平方有关；对于一个细长的直杆，绕垂直于杆且通过一端的轴转动时，其惯性矩也有特定的表达式。惯性矩在研究物体的转动运动、机械设计等方面都有着重要的应用。

方差和惯性矩有一定的相似性，但不能简单地说方差就是惯性矩。方差主要是用来描述一组数据离散程度的统计量。它反映了数据相对于均值的偏离程度。而惯性矩是在力学中用于衡量物体绕轴转动时惯性大小的物理量。

从某种意义上来说，它们有一些相似之处。比如两者都涉及到对“差异”或“偏离”的一种度量。在惯性矩中，是质量分布相对于转动轴的偏离程度；在方差中，是数据点相对于均值的偏离程度。
:::
