## 协方差以及随机变量的和的方差
在 @sec-4_5 中，我们证明了任意数量的 **随机变量** 之和的 **期望** 等于它们各自 **期望** 的和（@eq-4_5_002_452）。但是，对于 **方差** 而言，却并非如此。例如：

$$
\begin{align}
Var(X+X) &= Var(2X) \\
&= 2^2 Var(X) \\
&= 4 Var(X) \\
& \ne Var(X) + Var(X)
\end{align}
$$

然而，当这些 **随机变量** 是独立的条件时，**随机变量** 的和的 **方差** 等于这些 **随机变量** 各自的方差的和。但是，在证明这一点之前，我们先定义两个 **随机变量** 的 **协方差**（*covariance*） 的概念。

::: {#def-4_7_001}
两个 **随机变量** $X$、$Y$ 的 **协方差** $\textup{Cov}(X,Y)$ 的定义如下：

$\textup{Cov}(X,Y) = E[(X - \mu_x)(Y - \mu_y)]$，其中 $\mu_x$ 和 $\mu_y$ 分别为 $X$ 和 $Y$ 的均值。
:::

对 @def-4_7_001 中的等式右边进行展开，则有：

$$
\begin{align}
\textup{Cov}(X,Y) &= E[XY - \mu_x Y -\mu_y X + \mu_x \mu_y] \\
&= E[X,Y] - \mu_xE[Y] - \mu_yE[X] + \mu_x \mu_y \\
&= E[XY] - \mu_x \mu_y - \mu_y \mu_x + \mu_x \mu_y \\
&= E[XY] - E[X]E[Y]
\end{align}
$$ {#eq-4_7_001}

根据 @def-4_7_001，我们可以知道 **协方差** 满足如下的性质：

::: {.callout-tip}
$$
\textup{Cov}(X,Y) = \textup{Cov}(Y,X)
$$ {#eq-4_7_002}

$$
\textup{Cov}(X,X) = \textup{Var}(X)
$$ {#eq-4_7_003}

$$
\textup{Cov}(aX, Y) = a \textup{Cov}(X, Y)
$$ {#eq-4_7_004}
:::

与 **期望** 一样，**协方差** 也具有加和性（*additive property*）。

::: {#lem-4_7_1}
$\textup{Cov}(X_1 + X_2, Y) = \textup{Cov}(X_1, Y) + \textup{Cov}(X_2,Y)$
:::

::: {.proof}
$$
\begin{align}
\textup{Cov}(X_1 + X_2,Y) &= E[(X_1+X_2)Y] - E[X_1+X_2]E[Y] \\
&= E[X_1Y] + E[X_2Y]-(E[X_1] + E[X_2])E[Y] \\
&= E[X_1Y] - E[X_1]E[Y] + E[X_2Y] - E[X_2]E[Y] \\
&= \textup{Cov}(X_1,Y) + \textup{Cov}(X_2,Y) \quad \blacksquare
\end{align}
$$
:::

@lem-4_7_1 的一般形式如下：

$$
\textup{Cov}\bigg( \sum_{i=1}^{n}{X_i},Y \bigg) = \sum_{i=1}^{n}{\textup{Cov}(X_i,Y)}
$$ {#eq-4_7_005_475}

::: {#prp-4_7_2}
$$
\textup{Cov}\bigg( \sum_{i=1}^{n}{X_i},\sum_{j=1}^{m}{Y_j} \bigg) = \sum_{i=1}^{n} \sum_{j=1}^{m} {\textup{Cov}(X_i,Y_j)}
$$
:::

::: {.proof}
$$
\begin{align}
\textup{Cov}\bigg( \sum_{i=1}^{n}{X_i},\sum_{j=1}^{m}{Y_j} \bigg) &= \sum_{i=1}^{n}{\textup{Cov}\bigg(X_i, \sum_{j=1}^{m}{Y_j}\bigg)} \\
&= \sum_{i=1}^{n}{\textup{Cov}\bigg(\sum_{j=1}^{m}{Y_j}, X_i\bigg)} \\
&= \sum_{i=1}^{n} \sum_{j=1}^{m} {\textup{Cov}(Y_j,X_i)} \\
&= \sum_{i=1}^{n} \sum_{j=1}^{m} {\textup{Cov}(X_i,Y_j)} \quad \blacksquare
\end{align}
$$
:::

使用 @eq-4_7_003 可以得到 **随机变量** 之和的方差的公式。

::: {#cor-4_7_3}
$$
\textup{Var}\bigg( \sum_{i=1}^{n}{X_i} \bigg) = \sum_{i=1}^{n}{\textup{Var}(X_i)} + \sum_{i=1}^{n} \sum_{\begin{align} &j=1 \\ &j \ne i \end{align}}^{n} {\textup{Cov}(X_i, X_j)}
$$
:::

::: {.proof}
因为 $\textup{Cov}(X, X) = \textup{Var}(X)$（@eq-4_7_003），根据 @prp-4_7_2 有：

$$
\begin{align}
\textup{Var}\bigg( \sum_{i=1}^{n}{X_i} \bigg) &= \textup{Cov}\bigg( \sum_{i=1}^{n}{X_i}, \sum_{j=1}^{n}{X_j} \bigg) \\
&= \sum_{i=1}^{n} \sum_{j=1}^{n} {\textup{Cov}(X_i, X_j)} \\
&= \sum_{i=1}^{n} \bigg( \sum_{j \ne i}{\textup{Cov}(X_i, X_j)} + \textup{Cov}(X_i, X_i)\bigg) \\
&= \sum_{i=1}^{n} \sum_{j \ne i} {\textup{Cov}(X_i, X_j)} + \sum_{i=1}^{n}{\textup{Cov}(X_i, X_i)} \\
&= \sum_{i=1}^{n} \sum_{j \ne i} {\textup{Cov}(X_i, X_j)} + \sum_{i=1}^{n}{\textup{Var}(X_i)} \quad \blacksquare
\end{align}
$$
:::

当 $n = 2$ 时，@cor-4_7_3 变为：

$\textup{Var}(X+Y) = \textup{Var}(X) + \textup{Var}(Y) + \textup{Cov}(X,Y) + \textup{Cov}(Y,X)$

根据 @eq-4_7_002 有：

$$
\textup{Var}(X+Y) = \textup{Var}(X) + \textup{Var}(Y) + 2\textup{Cov}(X,Y)
$$ {#eq-4_7_006_476}

::: {#thm-4_7_4}
如果 $X$ 和 $Y$ 是独立 **随机变量**，则 $\textup{Cov}(X,Y) = 0$。

更一般的，如果 $X_1,...,X_n$ 是相互独立的 **随机变量**，则 $\textup{Var}\bigg( \sum_{i=1}^{n}{X_i} \bigg)=\sum_{i=1}^{n}{\textup{Var}(X_i)}$。

::: {.proof}
要证明 $\textup{Cov}(X,Y) = 0$，根据 @eq-4_7_001 可知，我们需要证明：

$E[XY] = E[X]E[Y]$

如果 $X$、$Y$ 为独立离散随机变量，则有：

$$
\begin{align}
E[XY] &= \sum_{j}^{} \sum_{i}^{} {x_i y_i P\{X=x_i, Y=y_j\}} \\
&= \sum_{j}^{} \sum_{i}^{} {x_i y_i P\{X=x_i\}P\{Y=y_j\}} \quad \because X,Y 相互独立 \\
&= \sum_{y}^{}{y_jP\{Y=y_j\}} \cdot \sum_{j}^{}{x_iP\{X=x_i\}} \\
&= E[Y]E[X]
\end{align}
$$

故而有 $\textup{Cov}(X,Y)=E[XY] - E[X]E[Y] = 0$。对于连续随机变量而言，该等式依然成立。所以 @thm-4_7_4 得证。
:::
:::

::: {#exr-4_7_a}
抛 10 次骰子，计算这 10 次获得的点数之和的 **方差**。
:::

::: {#sol-4_7_a}
令 $X_i$ 表示第 $i$ 次的点数，则根据 @exr-4_6_a 有，$\textup{Var}(X_i) = \frac{35}{12}$，所以：
$$
\begin{align}
\textup{Var}\bigg( \sum_{i=1}^{10}{X_i} \bigg) &= \sum_{i=1}^{10}{\textup{Var}(X_i)} \\
&= 10 \frac{35}{12} \\
&= \frac{175}{6} \quad \blacksquare
\end{align}
$$
:::

::: {#exr-4_7_b}
抛 10 次硬币，计算正面向上的次数的 **方差**。
:::

::: {#sol-4_7_b}
令 $I_j = \begin{cases} 1, \quad & 第 j 次结果为正面向上\\ 0, \quad & 第 j 次结果为反面向上 \end{cases}$，

则 正面向上的总次数为 $\sum_{j=1}^{10}{I_j}$。

根据 @thm-4_7_4 有：$\textup{Var}\bigg( \sum_{j=1}^{10}{I_j} \bigg) = \sum_{j=1}^{10}{\textup{Var}(I_j)}$。

现在，由于 $I_j$ 是概率为 \frac{1}{2} 的 **事件** 的指示 **随机变量**，从 @exm-4_6_b 可知：

$\textup{Var}(I_j) = \frac{1}{2}(1-\frac{1}{2}) = \frac{1}{4}$，因此：

$\textup{Var}\bigg( \sum_{j=1}^{10}{I_j} \bigg) = \frac{10}{4}$。$\blacksquare$
:::

::: {.callout-important}
两个 **随机变量** 的 **协方差** 可以作为一个重要指标以衡量它们之间的关系。例如，考虑 $X$ 和 $Y$ 是 **事件** $A$ 和 **事件** $B$ 是否发生的指标随机变量，即：

$X = \begin{cases} 1, \quad & 如果 A 发生\\ & \\ 0, \quad & 如果 A 不发生 \end{cases},  \quad Y = \begin{cases} 1, \quad & 如果 B 发生\\ & \\ 0, \quad & 如果 B 不发生 \end{cases}$

并且：

$XY = \begin{cases} 1, \quad & 如果 X=1, Y=1\\ & \\ 0, \quad & 其他 \end{cases}$

因此：

$\begin{align} \textup{Cov}(X,Y) &= E[XY] - E[X]E[Y] \\ &= P\{X=1,Y=1\} - P\{X=1\}P\{Y=1\} \end{align}$

故而：

$\begin{align} \textup{Cov}(X,Y) \gt 0 & \Leftrightarrow P\{X=1,Y=1\} \gt P\{X=1\}P\{Y=1\} \\ & \Leftrightarrow \frac{P \{X=1,Y=1\}}{P\{X=1\}} \gt P\{Y=1\} \\ & \Leftrightarrow P\{Y=1|X=1\} \gt P\{Y=1\} \end{align}$

如果 $X=1$ 时，$Y=1$ 的可能性更小，而 $Y=0$ 的可能性更大，则 $\textup{Cov}(X,Y) \lt 0$ 。（根据 **协方差** 的交换律，当 $X$ 和 $Y$ 互换时，如上的内容仍然正确。）
:::

::: {.callout-tip title="相关系数"}
一般来说，$\textup{Cov}(X,Y) \gt 0$ 表明 $Y$ 会随着 $X$ 的增加而增加，而 $\textup{Cov}(X,Y) \lt 0$ 表明 $Y$ 会随着 $X$ 的增加而减少。可以用 $X$ 和 $Y$ 之间的相关性来表示 $X$ 和 $Y$ 之间关系的强度。$X$ 和 $Y$ 之间的相关性是其 **协方差** 除以其各自 **标准差** 的乘积得到的 **无量纲量**（*dimensionless*）。即：

$$
\textup{Corr}(X,Y) = \frac{\textup{Cov}(X,Y)}{\sqrt{\textup{Var}(X) \textup{Var}(Y)}}
$$ {#eq-4_7_007}

可以证明，$\textup{Corr}(X,Y)$ 的值总是介于 −1 和 +1 之间。
::: 
