project:
  type: book
  output-dir: public

lang: zh

book:
  title: "Introduction to Probability and Statistics for Engineers and Scientists（中文版）"
  favicon: favicon.png
  author: "王伟（17哥）"
  open-graph: true
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  repo-url: https://github.com/wangwei1237/introduction_to_probability_and_statistics
  repo-actions: [edit, issue]
  search: true
  page-footer: Copyright Wang Wei. All Rights Reserved.
  chapters:
    - index.qmd
    - preface_17.qmd
    - preface.qmd
    - chapter_1/1.qmd
    - chapter_2/2.qmd
    - chapter_3/3.qmd
    - chapter_4/4.qmd
    - chapter_5/5.qmd
    - chapter_6/6.qmd
    - chapter_7/7.qmd
    - chapter_8/8.qmd
    - chapter_9/9.qmd
    - chapter_10/10.qmd
    - chapter_11/11.qmd
    - chapter_12/12.qmd
    - chapter_13/13.qmd
    - chapter_14/14.qmd
    - chapter_15/15.qmd
    - chapter_16/16.qmd
    - test.qmd
    - references.qmd
  appendices: 
    - appendices.qmd
  site-url: https://wangwei1237.github.io/introduction_to_probability_and_statistics/
  navbar:
    search: true
    logo: favicon.png
    left:
      - text: "博客"
        icon: "house-fill"
        href: "https://wangwei1237.github.io/"
      - text: "书籍"
        icon: "bookshelf"
        menu: 
          - text: "动手学深度学习"
            href: "https://zh.d2l.ai/"
          - text: "Learn Prompting"
            href: "https://learnprompting.org/zh-Hans/docs/intro"
          - text: "Stabel Diffusion 提示词手册"
            href: "https://pan.baidu.com/s/1dciwgbhO-lfKyRo8lOqW9Q?pwd=cm9q"
      - text: "关于"
        icon: "person-badge-fill"
        href: "https://wangwei1237.github.io/aboutme/"

bibliography: references.bib
csl: acm-sig-proceedings.csl

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    code-fold: true
    cover-image: cover.png

comments:
  utterances:
    repo: wangwei1237/introduction_to_probability_and_statistics
    label: comment