## 超几何随机变量 {#sec-5_3}

一个箱子中包含 $N + M$ 节电池，其中 $N$ 节质量合格，$M$ 节为次品。随机抽取（无放回抽样）一个大小为 $n$ 的样本，这里的抽样是指从 $N+M$ 个子集中等可能地抽取任意一个大小为 $n$ 的子集。如果我们令 $X$ 表示样本中合格电池的数量，那么：

$$
P\{X = i\} = \frac{\binom{N}{i} \binom{M}{n-i}}{\binom{N+M}{n}}, \quad i = 0, 1, \dots, \min(N, n)
$$ {#eq-5_3_1}

任何概率质量函数由 @eq-5_3_1 给出的随机变量 $X$ 都被称为参数为 $N, M, n$ 的**超几何随机变量**（*hypergeometric random variable*）。

::: {#exr-5_3_1}
一个由 6 个组件组成的系统，其组件是从一箱 20 个旧组件中随机选取的。如果这 20 个组件中有 15 个处于工作状态，且系统中至少有 4 个组件处于工作状态时系统才能正常运行，那么系统正常运行的概率是多少？
:::

::: {#sol-5_3_1}
如果 $X$ 是所选出的工作组件的数量，那么 $X$ 是参数为 $15, 5, 6$ 的超几何随机变量。系统正常运行的概率为：

$$
\begin{align}
P\{X \geq 4\} &= \sum_{i=4}^6 P\{X = i\} \\
&= \frac{\binom{15}{4} \binom{5}{2} + \binom{15}{5} \binom{5}{1} + \binom{15}{6} \binom{5}{0}}{\binom{20}{6}} \\
&\approx .8687
\end{align}
$$ $\blacksquare$
:::

为了计算概率质量函数由 @eq-5_3_1 给出的超几何随机变量的均值和方差，我们可以设想电池是按顺序抽取的，并令：

$$
X_i = 
\begin{cases} 
1, & \text{如果第 } i \text{ 次抽取的电池是合格的} \\
0, & \text{否则}
\end{cases}
$$

现在，由于第 $i$ 次抽取等可能地选中 $N + M$ 节电池中的任意一节，而其中 $N$ 节是合格的，因此：

$$
P\{X_i = 1\} = \frac{N}{N + M}
$$ {#eq-5_3_2}

此外，对于 $i \neq j$：

$$
\begin{align}
P\{X_i = 1, X_j = 1\} &= P\{X_i = 1\} P\{X_j = 1 | X_i = 1\} \\
&= \frac{N}{N + M} \frac{N - 1}{N + M - 1}
\end{align}
$$ {#eq-5_3_3}

这是因为，已知第 $i$ 次抽取的电池是合格的，那么第 $j$ 次抽取将等可能地从剩下的 $N + M - 1$ 节电池中抽取，而其中 $N - 1$ 节是合格的。

为了计算样本大小为 $n$ 时合格电池数量 $X$ 的均值和方差，我们利用表示式：

$$
X = \sum_{i=1}^n X_i
$$

得到：

$$
E[X] = \sum_{i=1}^n E[X_i] = \sum_{i=1}^n P\{X_i = 1\} = \frac{nN}{N + M}
$$ {#eq-5_3_4}

此外，利用独立随机变量和的方差公式（见 @cor-4_7_3）：

$$
Var(X) = \sum_{i=1}^n Var(X_i) + 2 \sum_{1 \leq i < j \leq n} Cov(X_i, X_j)
$$ {#eq-5_3_5}

由于 $X_i$ 是伯努利随机变量，因此：

$$
Var(X_i) = P\{X_i = 1\} (1 - P\{X_i = 1\}) = \frac{N}{N + M} \frac{M}{N + M}
$$ {#eq-5_3_6}

此外，对于 $i < j$：

$$
Cov(X_i, X_j) = E[X_i X_j] - E[X_i] E[X_j]
$$

由于 $X_i$ 和 $X_j$ 都是伯努利（即 0-1）随机变量，因此 $X_i X_j$ 也是伯努利随机变量，所以：

$$
\begin{align}
E[X_i X_j] &= P\{X_i X_j = 1\} \\
&= P\{X_i = 1, X_j = 1\} \\
&= \frac{N(N - 1)}{(N + M)(N + M - 1)} \quad (\text{由 @eq-5_3_3 得出})
\end{align}
$$ {#eq-5_3_7}

因此，从 @eq-5_3_2 和前述内容我们可以看到，对于 $i \neq j$：

$$
\begin{align}
Cov(X_i, X_j) &= \frac{N(N - 1)}{(N + M)(N + M - 1)} - \left(\frac{N}{N + M}\right)^2 \\
&= \frac{-NM}{(N + M)^2 (N + M - 1)}
\end{align}
$$

由于 @eq-5_3_5 的右侧第二个求和项共有 $\binom{n}{2}$ 项，由 @eq-5_3_6 得到：

$$
\begin{align}
Var(X) &= \frac{nNM}{(N + M)^2} - \frac{n(n - 1)NM}{(N + M)^2 (N + M - 1)} \\
&= \frac{nNM}{(N + M)^2} \left(1 - \frac{n - 1}{N + M - 1}\right)
\end{align}
$$ {#eq-5_3_8}

如果我们令 $p = N/(N + M)$ 表示箱子中合格电池的比例，那么我们可以将 @eq-5_3_4 和 @eq-5_3_8 改写如下：

$$
E[X] = np
$$
$$
Var(X) = np(1 - p) \left[1 - \frac{n - 1}{N + M - 1}\right]
$$

应当指出，对于固定的 $p$，随着 $N + M \to \infty$，$Var(X)$ 会收敛到 $np(1 - p)$，即参数为 $(n, p)$ 的二项随机变量的方差。（为什么这是预料之中的？）

::: {#exr-5_3_2}
假设某地区栖息着未知数量 $N$ 的动物。为了获得关于种群规模的信息，生态学家经常进行如下实验：他们首先捕获数量为 $r$ 的动物，给它们做上某种标记，然后放掉。在标记过的动物有时间分散到整个地区之后，再次捕获数量为 $n$ 的动物。令 $X$ 表示第二次捕获中带标记动物的数量。如果我们假设该地区动物种群在两次捕获期间保持不变，并且每次捕获动物时，任何尚未被捕获的动物被捕获的可能性都是相等的，那么 $X$ 是一个超几何随机变量，使得：

$$
P\{X = i\} = \frac{\binom{r}{i} \binom{N-r}{n-i}}{\binom{N}{n}} \equiv P_i(N)
$$
:::

::: {#sol-5_3_2}
现在假设观察到 $X$ 等于 $i$。也就是说，第二次捕获的动物中带标记的比例为 $i/n$。将此作为该地区带标记动物比例 $r/N$ 的近似，我们得到种群规模的估计值 $rn/i$。例如，如果最初捕获了 $r = 50$ 只动物并做了标记放回，随后捕获了 $n = 100$ 只动物中发现 $X = 25$ 只有标记，那么我们会估计该地区的动物数量约为 200。 $\blacksquare$
:::

二项随机变量和超几何分布之间存在一种关系，这对于我们在后续章节中开发涉及两个二项总体（*populations*）的统计检验非常有用。

::: {#exr-5_3_3}
令 $X$ 和 $Y$ 是参数分别为 $(n, p)$ 和 $(m, p)$ 的独立二项随机变量。在已知 $X + Y = k$ 的条件下，$X$ 的条件概率质量函数如下：

$$
\begin{align}
P\{X = i | X + Y = k\} &= \frac{P\{X = i, X + Y = k\}}{P\{X + Y = k\}} \\
&= \frac{P\{X = i, Y = k - i\}}{P\{X + Y = k\}} \\
&= \frac{P\{X = i\} P\{Y = k - i\}}{P\{X + Y = k\}} \\
&= \frac{\binom{n}{i} p^i (1 - p)^{n-i} \binom{m}{k-i} p^{k-i} (1 - p)^{m-(k-i)}}{\binom{n+m}{k} p^k (1 - p)^{n+m-k}} \\
&= \frac{\binom{n}{i} \binom{m}{k-i}}{\binom{n+m}{k}}
\end{align}
$$

其中，倒数第二个等号利用了 $X + Y$ 是参数为 $(n + m, p)$ 的二项分布的事实。因此，我们看到在已知 $X + Y$ 值的条件下，$X$ 的条件分布是超几何分布。
:::

::: {#sol-5_3_3}
值得注意的是，上述结果是非常直观的。假设进行了 $n + m$ 次独立试验，每次试验成功的概率相同；令 $X$ 为前 $n$ 次试验中的成功次数，并令 $Y$ 为最后 $m$ 次试验中的成功次数。已知 $n + m$ 次试验中共有 $k$ 次成功，那么这 $k$ 次成功的试验子集等可能地由 $n + m$ 次试验中的任何 $k$ 个试验组成。也就是说，$k$ 次成功试验分布在从 $n + m$ 次试验中随机选出的 $k$ 个位置，因此属于前 $n$ 次试验的数量服从超几何分布。 $\blacksquare$
:::

超几何概率可以使用 R 来计算，`dhyper(i, N, M, n)` 和 `phyper(i, N, M, n)` 分别给出参数为 $(N, M, n)$ 的超几何随机变量分别等于 $i$ 或小于等于 $i$ 的概率。因此，从一个包含 8 个红球和 22 个蓝球的瓮中随机选取 10 个球，包含恰好 4 个红球以及最多 4 个红球的概率可以通过如下方式获得：

```R
> dhyper(4, 8, 22, 10)
[1] 0.1738362
> phyper(4, 8, 22, 10)
[1] 0.943682
```

因此，选中恰好 4 个红球的概率约为 17.38%，选中最多 4 个红球的概率约为 94.37%。
