## 引言 {#sec-10_1}
目前市面上有 4 款软件来教授用户学习一门新的变成语言，某大公司正在考虑大规模购买这 4 款软件中的一款。公司内部一些资深人士声称，这几款软件没有太大的区别，它们对用户的最终学习效果影响很小。为了检验这一假设，公司决定选择 160 名工程师，并将他们分成 4 组，每组 40 人。第 $i$ 组的工程师使用第 $i$（$i = 1, 2, 3, 4$）款软件来学习新的语言。当所有工程师完成学习后，参与学习的所有工程师将进行一次全面考试。公司希望使用这次考试的结果来确定不同的教学软件是否真的可以互换。该公司需要怎么做才能实现这一点？

在回答这个问题之前，我们需要明确，显然我们希望得出这样的结论：当所有分组的平均成绩相似时，可以认为这几款软件确实是可以互换的；而当不同分组的平均成绩之间有很大差异时，可以认为这几款软件在本质上是存在区别的。要得出这样的结论，我们必须注意到：将这 160 名工程师分成 4 组的方法至关重要。例如，假设第一组的成员成绩显著高于其他组，我们能从中得出什么结论？具体来说，这个结果是由于 第 1 款软件的教学效果更好，还是第一组的工程师的学习能力更好？为了能够得出这几款软件是否可以互换的结论，需要一种合理的分组方式以保证不同分组的工程师不会存在显著的差异，这一点至关重要。以完全随机的方式将工程师分成 4 组是久经考验的一种方法。也就是说，完全随机的分组方式可以使得所有可能的分组组合都有相同的概率，从而保障任何一组明显优于其他组的可能性非常小。假设我们确实使用“随机”的方式对工程师分组，虽然目前还不清楚如何才能做到。一种有效的方法是首先对这 160 名工程师进行 1~160 的编号，然后生成 1~160 的随机排列，并将排列中的前 40 名工程师放分到 第 1 组，排列中的第 41 到 80 名工程师分到 第 2 组，以此类推。

现在，我们可以合理的假设：每一位工程师的考试成绩应该大致服从正态分布，该分布的参数取决于他所使用的教学软件。同样，也可以合理的假设：尽管工程师的平均考试成绩取决于他所使用的教学软件，但考试成绩的变异性（*variability*）将源自 160 名工程师的内在变异（*inherent variation*），而不是来自所使用的软件。因此，如果我们令 $X_{ij},\ i=1,...4, \ j=1,...,40$ 表示第 $i$ 组中第 $j$ 名工程师的考试成绩。一个合理的模型可能是假设 $X_{ij}$ 是独立的随机变量，其中 $X_{ij}$ 服从均值为 $\mu_i$ 且方差为 $\sigma^2$ 的正态分布。不同的教学软件可以互换的假设相当于对原假设 $H_0: \mu_1 = \mu_2 = \mu_3 = \mu_4$ 进行检验。

::: {.callout-note title="变异量"}
正如在 @sec-9_5 中对 **变异** 这个术语的解释，此处再次做如下的强调。

**变异量**（*the amount of variation*）是指一组数据中的变异性，即数据的波动或分散程度。这种波动可以是由多种因素引起的，包括个体差异、测量误差、随机误差等。在后续的翻译章节中，我们会根据具体的场景交叉使用 **变异量** 和 **数据波动**，如无特殊说明，这些指的都是一个概念。

同时，我们会避免使用 **数据差异**（*difference*） 来指代 **变异量** 的概念，因为在数学中，**数据差异** 更多指代两个数据之间的差值，因此和我们所讨论的数据的波动和分布程度并不是一个概念。
:::

在本章中，我们将介绍一种技术可以用来检验如上案例中的假设。这种技术非常通用，可以用于推断与总体均值相关的大量参数，这种技术称之为 **方差分析**（*ANOVA, analysis of variance*）。