## 综述 {#sec-10_2}
> 本章内容还需要继续修改。

在 @sec-8_4、@sec-8_5_1、@sec-8_6_1、@sec-8_7_1 章节中，我们研究了关于两个总体均值的假设检验。在本章中，我们将研究关于多个总体均值的假设检验。

在 @sec-10_3 中，假设我们有来自 $m$ 个不同总体的样本，每个样本的大小为 $n$，我们希望使用这些数据来检验 $m$ 个总体均值相等的假设。对于这种场景，由于随机变量的均值仅取决于一个因素——即随机变量来自哪个样本——因此称这种情况为 **单因素方差分析**（*one-way analysis of variance*）。在 @sec-10_3_2 中，我们展示了如何获得 $\binom{m}{2}$ 对总体均值之间的 **多重比较**（*multiple comparisons*）。在第 @sec-10_3_3 中展示了当 $m$ 个样本之间的样本大小不同时，如何检验总体均值相等的假设。

在 @sec-10_4 和 @sec-10_5 中，我们将介绍由两个因素决定因变量均值的模型。在这些模型中，我们可以把自变量排列在一个矩阵中，在这个矩阵中，每一行和每一列都代表着一个因素或条件，矩阵中的元素代表着自变量的观测数据。此时，某个因变量的均值同时依赖于矩阵中的行和列。这种模型称为 **双因素方差分析**（*two-way analysis of variance*）。我们假设因变量的均值受到自变量的 **加性方式**（*additive fashion*）影响，具体地，第 $i$ 行、第 $j$ 列的变量对应的响应均值可以表示为 $\mu + \alpha_i + \beta_j$。在 @sec-10_4 中，我们将介绍如何估计 $\alpha_i$、$\beta_j$。在 @sec-10_5 中将介绍如何进行检验假设，即某个特定因素不会影响结果的均值。

在 @sec-10_6 中，我们将介绍因变量的均值允许以非线性方式取决于自变量所在的行和列的情况，从而允许两个因素之间存在 **交互作用**（*interaction*）。我们还将介绍如何检验不存在交互作用的假设，以及关于不存在行效应和列效应对因变量均值影响的假设。

在本章中，我们假设所有的数据都服从正态分布，并且都具有相同（虽然未知）的方差 $\sigma^2$。使用 ANOVA 来检验和总体均值有关的多个参数的原假设 $H_0$，需要基于从共同的总体方差 $ \sigma^2 $ 中推导出的两个估计量。第一个估计量是 $\sigma^2$ 的估计量，并且无论原假设是否为真，该估计量都是 $\sigma^2$ 的有效估计量。第二个估计量也是 $\sigma^2$ 的估计量，只是仅在 $H_0$ 为真时，该估计量才是 $\sigma^2$ 的有效估计量。此外，当 $H_0$ 不成立时，第二个估计量往往会超过 $\sigma^2$。检验方法就是比较这两个估计量的值，并在第二个估计量与第一个估计量的比率足够大时拒绝 $H_0$。换句话说，当 $H_0$ 为真时，这两个估计量应彼此接近（因为它们在这种情况下都是 $\sigma^2$ 的估计量），而当 $H_0$ 不为真时，第二个估计量通常应比第一个大，因此当第二个估计量显著大于第一个时，拒绝 $H_0$ 是自然的选择。

我们将使用和卡方随机变量有关的事实来获得方差 $\sigma^2$ 的估计量。假设 $X_1, \dots, X_N$ 是独立的正态分布随机变量，它们可能具有不同的均值但却具有相同的方差 $\sigma^2$，并且设 $\mu_i = E[X_i]$，其中 $i = 1, \dots, N$。

由于随机变量

$Z_i = (X_i - \mu_i)/\sigma, \quad i = 1, \dots, N$

服从标准正态分布，因此根据卡方分布随机变量的定义可知：

$$
\sum_{i=1}^{N} Z_i^2 = \sum_{i=1}^{N} \frac{(X_i - \mu_i)^2}{\sigma^2}
$$ {#eq-10_2_1}

是一个自由度为 $N$ 的卡方分布随机变量。假设每一个 $\mu_i, \ i = 1, \dots, N$ 都可以表示为 $k$ 个未知参数的线性函数。同时，假设我们可以确定这 $k$ 个参数的估计量，从而给出 $\mu_i$ 的估计量。如果我们用 $\hat{\mu}_i$ 表示 $\mu_i, \ i=1,...,N$ 的估计量，那么可以证明：

$\sum_{i=1}^{N} \frac{(X_i - \hat{\mu}_i)^2}{\sigma^2}$

服从自由度为 $N - k$ 的卡方分布。

换句话说，

$\sum_{i=1}^{N} \frac{(X_i - E[X_i])^2}{\sigma^2}$

是一个自由度为 $N$ 的卡方分布随机变量。

如果我们用 $k$ 个参数的线性函数来表示每个 $E[X_i]$，并用这 $k$ 个参数的估计量来替换这 $k$ 个参数，那么我们得到的表达式仍然是卡方分布，但是其自由度将因为每个参数由其估计量来代替而减少 1。

为了说明如上的结论，我们考虑所有均值已知并且相等的情况，即：

$E[X_i] = \mu, \quad i = 1, \dots, N$

因为此时只有一个需要估计的参数，因此 $k = 1$。把公共均值 $\mu$ 的估计量 $\overline{X}$ 代入 @eq-10_2_1 得到如下的量：

$$
\sum_{i=1}^{N} \frac{(X_i - \overline{X})^2}{\sigma^2}
$$ {#eq-10_2_2}

则 @eq-10_2_2 是一个自由度为 $N - 1$ 的卡方分布随机变量。

在所有均值都相等的情况下，数据 $X_1, \dots, X_N$ 均来自同一个正态分布总体，因此 @eq-10_2_2 等价与 $(N - 1)S^2/\sigma^2$，其中 $S^2$ 是样本方差。换句话说，在这种场景下的结论就是：$(N - 1)S^2/\sigma^2$ 是自由度为 $N - 1$ 的卡方分布随机变量（参见 @thm-6_5_1）。