## 双因素方差分析：引言和参数估计 {#sec-10_4}
虽然我们可以用 @sec-10_3 中的模型研究数据集中的单个因素的影响，但我们还可以研究多个因素的影响。在本节中，我们假设每个数据值都受到两个因素的影响。

::: {#exm-10_4_a}
对 5 名学生进行了 4 种不同标准的阅读测试，测试的结果如下表所示。表中的 20 个数据受到两个因素的影响：考试因素和学生因素。考试因素有 4 个可能的取值或 **水平**（*levels*），学生因素有 5 个可能的取值或 **水平**（*levels*）。

| 考试标准 | 学生 1 | 学生 2 | 学生 3 | 学生 4 | 学生 5 |
|------|-----------|-----------|-----------|-----------|-----------|
| 1    | 75        | 73        | 60        | 70        | 86        |
| 2    | 78        | 71        | 64        | 72        | 90        |
| 3    | 80        | 69        | 62        | 70        | 85        |
| 4    | 73        | 67        | 63        | 80        | 92        |

通常情况下，我们假设第一个因素有 $m$ 个可能的 **水平**，第二个因素有 $n$ 个可能的 **水平**。令 $X_{ij}$ 表示当第一个因素处于第 $i$ 个水平，第二个因素处于第 $j$ 个水平时获得的值。我们经常将数据集表示为如下的数组：

$$
\begin{matrix}
X_{11} & X_{12} & \dots & X_{1j} & \dots & X_{1n} \\
X_{21} & X_{22} & \dots & X_{2j} & \dots & X_{2n} \\
\vdots & \vdots & \dots & \vdots & \dots & \vdots \\
X_{i1} & X_{i2} & \dots & X_{ij} & \dots & X_{in} \\
\vdots & \vdots & \dots & \vdots & \dots & \vdots \\
X_{m1} & X_{m2} & \dots & X_{mj} & \dots & X_{mn}
\end{matrix}
$$

因此，我们称第一个因素为 “行” 因素，称第二个因素为 “列” 因素。

如 @sec-10_3 中，我们假设数据 $X_{ij}, i = 1, \dots, m; j = 1, \dots, n$ 是具有相同方差 $\sigma^2$ 的独立正态分布随机变量。然而，在第 @sec-10_3 中，我们假设，只有一个因素（即它所属样本的均值）会影响数据点的均值。而在本节中，我们则假设，数据点的均值以 **加性方式**（*additive manner*）取决于其所在的行和列。

在 @sec-10_3 的模型中，我们令 $X_{ij}$ 表示第 $i$ 个样本中第 $j$ 个成员的值，那么模型可以符号化表示为：

$E[X_{ij}] = \mu_i$

如果我们令 $\mu$ 表示 $\mu_i$ 的平均值，即

$\mu = \frac{1}{m} \sum_{i=1}^{m} \mu_i$

那么我们可以将模型重写为

$E[X_{ij}] = \mu + \alpha_i$

其中 $\alpha_i = \mu_i - \mu$。根据 $\alpha_i$ 的定义：$\mu_i$ 相对于平均值 $\mu$ 的偏差，我们很容易得到：

$\sum_{i=1}^{m} \alpha_i = 0$

一个 **双因素加性模型** 也可以用行偏差和列偏差来表示。如果我们令 $\mu_{ij} = E[X_{ij}]$，则加性模型假设对于某些常数 $a_i$（$i = 1, \dots, m$）和 $b_j$（$j = 1, \dots, n$）有：

$\mu_{ij} = a_i + b_j$

令：

$\mu_{i.} = \frac{1}{n} \sum_{j=1}^{n} \mu_{ij}, \quad \mu_{.j} = \frac{1}{m} \sum_{i=1}^{m} \mu_{ij}, \quad \mu_{..} = \frac{1}{mn} \sum_{i=1}^{m} \sum_{j=1}^{n} \mu_{ij}$

同样地，我们定义

$a_{.} = \frac{1}{m} \sum_{i=1}^{m} a_i, \quad b_{.} = \frac{1}{n} \sum_{j=1}^{n} b_j$

因为：

$\mu_{i.} = \frac{1}{n} \sum_{j=1}^{n} (a_i + b_j)/n = a_i + b_{.}$

同理，

$\mu_{.j} = a_{.} + b_j, \quad \mu_{..} = a_{.} + b_{.}$

如果我们令：

$\mu = \mu_{..} = a_{.} + b_{.}$

$\alpha_i = \mu_{i.} - \mu = a_i - a_{.}$

$\beta_j = \mu_{.j} - \mu = b_j - b_.$

则我们有：

$\mu_{ij} = E[X_{ij}] = \mu + \alpha_i + \beta_j$

其中，$\sum_{i=1}^{m}{\alpha_i} = \sum_{j=1}^{n}{\beta_j} = 0$

我们称 $\mu$ 被为 **总均值**（*the grand mean*），$\alpha_i$ 为由第 $i$ 行导致的相对于 **总均值** 的偏差，$\beta_j$ 为由第 $j$ 列导致的相对于 **总均值** 的偏差。

接下来，我们确定参数 $\mu, \alpha_i, \beta_j$（$i = 1, \dots, m$, $j = 1, \dots, n$）的估计量。

令

$X_{i.} = \frac{1}{n} \sum_{j=1}^{n} X_{ij} \quad \text{表示第} i \text{行中的值的平均值}$

$X_{.j} = \frac{1}{m} \sum_{i=1}^{m} X_{ij} \quad \text{表示第} j \text{列中的值的平均值}$

$X_{..} = \frac{1}{nm} \sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij} \quad \text{表示所有数据值的平均值}$

则：

$$
\begin{align}
E[X_{i.}] &= \frac{1}{n} \sum_{j=1}^{n} E[X_{ij}] \\
&= \mu + \frac{1}{n} \sum_{j=1}^{n} \alpha_i + \frac{1}{n} \sum_{j=1}^{n} \beta_j \\
&= \mu + \alpha_i \quad \because \sum_{j=1}^{n} \beta_j = 0
\end{align}
$$


同理有：

$E[X_{.j}] = \mu + \beta_j$

$E[X_{..}] = \mu$

因为上述等式等价于：

$$
\begin{align}
E[X_{..}] &= \mu \\
E[X_{i.} - X_{..}] &= \alpha_i \\
E[X_{.j} - X_{..}] &= \beta_j
\end{align}
$$

我们发现，参数 $\mu, \alpha_i, \beta_j$ 的无偏估计量，记作 $\hat{\mu}, \hat{\alpha_i}, \hat{\beta_j}$ 为：

$$
\begin{align}
\hat{\mu} &= X_{..} \\
\hat{\alpha_i} &= X_{i.} - X_{..} \\
\hat{\beta_j} &= X_{.j} - X_{..}
\end{align}
$$

$\blacksquare$
:::

::: {#exr-10_4_b}
下表的数据来自 @exm-10_4_a，请使用这些数据估计模型的参数。

| 考试       | 学生 1  | 学生 2 | 学生 3 | 学生 4 | 学生 5 | 行总计| $X_{i.}$ |
|---|---|---|---|---|---|---|---|
| 1          | 75     | 73     | 60     | 70     | 86     | 364           | 72.8          |
| 2          | 78     | 71     | 64     | 72     | 90     | 375           | 75            |
| 3          | 80     | 69     | 62     | 70     | 85     | 366           | 73.2          |
| 4          | 73     | 67     | 63     | 80     | 92     | 375           | 75            |
| 列总计      | 306    | 280    | 249    | 292    | 353    | 1480 (grand total) |               |
| $X_{.j}$   | 76.5   | 70     | 62.25  | 73     | 88.25  |  $X_{..} = \frac{1480}{20} = 74$ |               |
:::

::: {#sol-10_4_b}
估计量为：

$\hat{\mu} = 74$

$\hat{\alpha_1} = 72.8 - 74 = -1.2 \quad \hat{\beta_1} = 76.5 - 74 = 2.5$

$\hat{\alpha_2} = 75 - 74 = 1 \quad \hat{\beta_2} = 70 - 74 = -4$

$\hat{\alpha_3} = 73.2 - 74 = -0.8 \quad \hat{\beta_3} = 62.25 - 74 = -11.75$

$\hat{\alpha_4} = 75 - 74 = 1 \quad \hat{\beta_4} = 73 - 74 = -1$

$\hat{\beta_5} = 88.25 - 74 = 14.25$

因此，如果随机选择一名学生并随机指定一场考试，那么我们对其平均分的估计是 $\hat{\mu} = 74$。如果我们知道该学生选择了考试 $i$，则这会使我们对其平均分的估计增加 $\hat{\alpha_i}$；如果我们知道学生的编号是 $j$，则这会使我们对其平均分的估计增加 $\hat{\beta_j}$。

例如，我们会估计第 1 场考试中第 2 名学生的分数是一个随机变量，其均值为：

$\hat{\mu} + \hat{\alpha_1} + \hat{\beta_2} = 74 - 1.2 - 4 = 68.8$

$\blacksquare$
:::