## 双因素方差分析：检验假设 {#sec-10_5}
考虑一个双因素模型，数据为 $X_{ij}$，$i = 1, \dots, m$，$j = 1, \dots, n$。假设 $X_{ij}$ 是具有共同方差 $\sigma^2$ 的独立正态分布随机变量，且其均值满足以下条件：

$E[X_{ij}] = \mu + \alpha_i + \beta_j$

其中，

$\sum_{i=1}^{m} \alpha_i = \sum_{j=1}^{n} \beta_j = 0$

在本节中，我们将关注检验如下的假设：

$H_0: \text{所有的} \ \alpha_i = 0 \quad vs \quad H_1: \text{并非所有的} \ \alpha_i \ \text{都等于} 0$

该原假设表明 $X_{ij}$ 不存在行效应，即某个数据的值不受其所在行的因素水平的影响。

类似的，我们还将关注有关列的假设，即

$H_0: \text{所有的} \ \beta_j = 0 \quad vs \quad H_1: \text{并非所有的} \ \beta_j \ \text{都等于} 0$

我们将使用 **方差分析**（*analysis of variance*） 的方法来检验上述原假设。在 **方差分析** 中，我们会得到方差 $\sigma^2$ 的两个不同的估计量：

* 第一个估计量总是有效估计量。
* 第二个估计量只有在原假设为真时才是有效估计量。
* 此外，当原假设不为真时，第二个估计量往往大于 $\sigma^2$。

为了获得 $\sigma^2$ 的第一个估计量，我们需要基于如下的事实：

$\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - E[X_{ij}])^2}{\sigma^2} = \sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - \mu - \alpha_i - \beta_j)^2}{\sigma^2}$

是自由度为 $nm$ 的卡方随机变量。如果用未知参数的估计量替换对应的未知参数 $\mu, \alpha_1, \alpha_2, \dots, \alpha_m, \beta_1, \beta_2, \dots, \beta_n$，则结果仍然是一个卡方分布随机变量，但其自由度将随着估计参数的增加而对应的减少（每估计一个参数，自由度减 1）。由于 $\sum_{i=1}^{m} \alpha_i = \sum_{j=1}^{n} \beta_j = 0$，这意味着当我们估计了 $m-1$ 个 $\alpha_i$ 后，最后一个 $\alpha_i$ 也随之确定；同理，我们仅需要估计 $n-1$ 个 $\beta_j$ 就可以确定所有的 $\beta_j$。最后，因为 $\mu$ 也需要估计，所以需要估计的参数总数为：

$1 + m - 1 + n - 1 = n + m - 1$

因此，

$\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - \hat{\mu} - \hat{\alpha_i} - \hat{\beta_j})^2}{\sigma^2}$

是一个自由度为 $nm - (n + m - 1) = (n-1)(m-1)$ 的卡方分布随机变量。

因为 $\hat{\mu} = X_{..}, \hat{\alpha_i} = X_{i.} - X_{..}, \hat{\beta_j} = X_{.j} - X_{..}$，所以有：

$$
\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - X_{i.} - X_{.j} + X_{..})^2}{\sigma^2}
$$ {#eq-10_5_1}

是一个自由度为 $(n-1)(m-1)$ 的卡方分布随机变量。

::: {#def-10_5_1}
**误差平方和**（*error sum of squares*）

我们称统计量 $SS_e$ 为 **误差平方和**：

$SS_e = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_{i.} - X_{.j} + X_{..})^2$ $\blacksquare$
:::

如果我们认为某个值与我们所估计的均值之间的差异是“误差”（*error*），那么 $SS_e$ 就等于这些误差的平方的总和。由于 $SS_e / \sigma^2$ 就是 @eq-10_5_1，所以我们知道 $SS_e / \sigma^2$ 是一个自由度为 $(n-1)(m-1)$ 的卡方分布随机变量。因为卡方分布随机变量的期望值等于其自由度，所以：

$E[SS_e/\sigma^2] = (n-1)(m-1)$

即：

$E\left[\frac{SS_e}{(n-1)(m-1)}\right] = \sigma^2$

所以：

$\frac{SS_e}{(n-1)(m-1)}$ 是 $\sigma^2$ 的无偏估计量。

假设我们现在想要检验 *不存在行效应* 的原假设，即我们想要检验

$H_0: \text{所有的} \alpha_i = 0 \quad vs \quad  H_1: \text{并不是所有的} \alpha_i \text{都为 0}$

为了获得 $\sigma^2$ 的第二个估计量，考虑行均值 $X_{i.}$，$i = 1, \ldots, m$。当 $H_0$ 为真时，每个 $\alpha_i = 0$，因此

$E[X_{i.}] = \mu + \alpha_i = \mu$

因为每个 $X_{i.}$ 是 $n$ 个随机变量的均值，而每个随机变量的方差为 $\sigma^2$，因此有

$\text{Var}(X_{i.}) = \frac{\sigma^2}{n}$

因此当 $H_0$ 为真时：

$\sum_{i=1}^{m}(X_{i.} - E[X_{i.}])^2 / \text{Var}(X_{i.}) = n \sum_{i=1}^{m}(X_{i.} - \mu)^2 / \sigma^2$

将服从自由度为 $m$ 的卡方分布。如果我们现在用 $X_{..}$ （$\mu$ 的估计量）代替 $\mu$，那么得到的表达式仍将是卡方分布，但自由度会减少 1。因此，当 $H_0$ 为真时，有以下结论：

$n \sum_{i=1}^{m}(X_{i.} - X_{..})^2 / \sigma^2$

服从自由度为 $m-1$ 的卡方分布。

::: {#def-10_5_2}
**行平方和**（*row sum of squares*）

我们称统计量 $SS_r$ 为 **行平方和**：

$SS_r = n \sum_{i=1}^{m}(X_{i.} - X_{..})^2$
:::

当 $H_0$ 为真时，$\frac{SS_r}{\sigma^2}$ 服从自由度为 $m-1$ 的卡方分布。因此，当 $H_0$ 为真时，有

$E[SS_r / \sigma^2] = m-1$

即：

$E[SS_r / (m-1)] = \sigma^2$

此外，可以证明，当 $H_0$ 不为真时，$\frac{SS_r}{(m-1)}$ 的值将大于 $\sigma^2$。

因此，我们再次获得了 $\sigma^2$ 的两个估计量：

* 无论原假设是否为真，第一个估计量 $\frac{SS_e}{(n-1)(m-1)}$ 都是有效估计量。
* 而仅在 $H_0$ 为真时，第二个估计量 $\frac{SS_r}{(m-1)}$ 才是有效估计量；当 $H_0$ 不为真时，$\frac{SS_r}{(m-1)}$ 将大于  $\sigma^2$。

基于 $\sigma^2$ 的两个估计量（$SS_e$ 和 $SS_r$）的比值对 $H_0$ 进行检验。具体来说，我们使用如下的检验统计量：

$TS = \frac{SS_r/(m-1)}{SS_e/[(n-1)(m-1)]}$

可以证明，当 $H_0$ 为真时，估计量是独立的，所以在显著性水平为 $\alpha$ 下的检验为：

$\begin{align} \text{拒绝} \quad &H_0, \quad \text{如果} \ TS \geq F_{\alpha, m-1, (n-1)(m-1)} \\ \text{不拒绝} \quad &H_0, \quad \text{否则}\end{align}$

或者，可以通过计算检验统计量 $v$ 的 $p-\text{value}$ 来进行检验：

$p-\text{value} = P(F_{m-1,(n-1)(m-1)} \geq v)$

类似的，我们同样可以使用如上的方法检验列效应的原假设，即检验所有的 $\beta_j = 0$ 的原假设。@tbl-10_2 和 @tbl-10_3 对本节介绍的 **行效应** 和 **列效应** 的假设检验方法进行了总结。同时，可以使用 R 来计算相关的 $p-\text{value}$。

|       | 平方和 | 自由度 |
|-------|-------|-------|
| 行    | $SS_r = n \sum_{i=1}^{m} (X_{i.} - X_{..})^2$ | $m - 1$ |
| 列    | $SS_c = m \sum_{j=1}^{n} (X_{.j} - X_{..})^2$ | $n - 1$ |
| 误差   | $SS_e = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_{i.} - X_{.j} + X_{..})^2$ | $(n - 1)(m - 1)$ |

: 行平方和，列平方和以及误差平方和 {#tbl-10_2}


| 原假设 | 检验统计量 | 显著性水平 $\alpha$ 下的检验 | $TS=v$ 时的 $p-\text{value}$ |
|---|---|---|---|
| 所有 $\alpha_i = 0$ | $\frac{SS_r/(m-1)}{SS_e/N}$ | 若 $TS \geq F_{\alpha,m-1,N}$，则拒绝 $H_0$ | $P\{F_{m-1,N} \geq v\}$ |
| 所有 $\beta_j = 0$ | $\frac{SS_c/(n-1)}{SS_e/N}$ | 若 $TS \geq F_{\alpha,n-1,N}$，则拒绝 $H_0$ | $P\{F_{n-1,N} \geq v\}$ |

: 双因素方差分析（*Two-Factor ANOVA*），$N = (n-1)(m-1)$ {#tbl-10_3}

::: {#exm-10_5_a}
以下数据表示在热排放附近的 6 个站点收集的、大型无脊椎动物的不同种类的数量，数据收集的时间为 1970 年至 1977 年。

::: {.callout-note}
热排放通常是指来自工业设施（如发电厂、工厂或其他热力系统）的废热，通常以温水或蒸汽的形式排放到附近的水体或空气中。因为水温的上升可能改变栖息地的条件，影响物种的多样性和数量，所以这种排放可能会对周围的环境、生态系统以及水生生物产生影响。
:::

| Year | Station 1 | Station 2 | Station 3 | Station 4 | Station 5 | Station 6 |
|------|-----------|-----------|-----------|-----------|-----------|-----------|
| 1970 | 53        | 35        | 31        | 37        | 40        | 43        |
| 1971 | 36        | 34        | 17        | 21        | 30        | 18        |
| 1972 | 47        | 37        | 17        | 31        | 45        | 26        |
| 1973 | 55        | 31        | 17        | 23        | 43        | 37        |
| 1974 | 40        | 32        | 19        | 26        | 45        | 37        |
| 1975 | 52        | 42        | 20        | 27        | 26        | 32        |
| 1976 | 39        | 28        | 21        | 21        | 36        | 28        |
| 1977 | 40        | 32        | 21        | 21        | 36        | 35        |

我们使用 R 来检验以下假设：

* (a) 数据是否随时间变化
* (b) 数据是否在各站点之间变化

```{r}
#| code-fold: false
#| warning: false

v1 <- c(53, 36, 47, 55, 40, 52, 39, 40)
v2 <- c(35, 34, 37, 31, 32, 42, 28, 32)
v3 <- c(31, 17, 17, 17, 19, 20, 21, 21)
v4 <- c(37, 21, 31, 23, 26, 27, 21, 21)
v5 <- c(40, 32, 45, 43, 45, 26, 36, 36)
v6 <- c(43, 18, 26, 37, 37, 32, 28, 35)
X <- matrix(c(v1, v2, v3, v4, v5, v6), 8, 6)
H <- sweep(X, 1, rowMeans(X)) + mean(X)
C <- sweep(H, 2, colMeans(X))
SSe <- sum(C^2)
D <- rowMeans(X) - mean(X)
SSr <- ncol(X) * sum(D^2)
E <- colMeans(X) - mean(X)
SSc <- nrow(X) * sum(E^2)
N <- (nrow(X) - 1) * (ncol(X) - 1)
TSrow <- (SSr / (nrow(X) - 1)) / (SSe / N)
TSrow

1 - pf(TSrow, nrow(X) - 1, N)

TScol = (SSc / (ncol(X) - 1)) / (SSe / N)
TScol

1 - pf(TScol, ncol(X) - 1, N)
```

因此，数据分布是否不依赖于年份的 F 统计量的值为 3.602，其对应的 $p-\text{value}$ 为 0.005；数据分布是否不依赖于站点的 F 统计量的值为 22.67，其对应的 $p-\text{value}$ 为 $4 \times 10^{-10}$。因此，在几乎所有的显著性水平下，这两个原假设我们都将拒绝。 $\blacksquare$
:::