## 双样本问题 {#sec-12_4}
假设某种具有可测量特性的产品的生产方式有两种不同的方法，我们正在研究这两种不同的生产方法，以确定这两种生产方法所生产的产品是否在统计上是一致的。

为了解决这个问题，令 $X_1, \ldots, X_n$ 表示使用方法 1 生产的 $n$￼个产品的测量值样本，类似地，令 $Y_1, \ldots, Y_m$￼表示使用方法 2 生产的 $m$￼个产品的测量值样本。如果我们令 $F$￼和 $G$￼分别表示这两个样本的分布函数，并假设它们都是连续的，那么我们需要检验的假设为：$H_0 : F = G$。

可以使用秩和检验（*rank sum test*）检验——又称为 Mann-Whitney 检验或 Wilcoxon 检验——来检验 $H_0$。

* 首先对 $n+m$￼个数据值 $X_1, \ldots, X_n, Y_1, \ldots, Y_m$ 进行排序。
* 由于我们假设 $F$￼和 $G$￼是连续的，所以不会出现两个相同的测量值，因此排序的结果是唯一的。我们令最小的数据值的秩为 1，次小的数据值的秩为 2，以此类推，第 $n+m$ 小的数据值的秩为 $n+m$。
* 对于 $i=1,...,n$，令 $R_i = \text{数据值 } X_i \text{ 的秩}$。

秩和检验则利用第一个样本中的数据的秩的总和作为检验统计量 $T$，即：$T = \sum_{i=1}^n R_i$。

::: {#exm-12_4_a}
为对比两种防腐处理方式的效果，我们设计了一个实验，并对这两种处理下的金属样本进行了对应的测量，测量结果如下：

* 处理 1：65.2, 67.1, 69.4, 78.2, 74, 80.3
* 处理 2：59.4, 72.1, 68, 66.2, 58.5

如上的数据表示金属样本上的腐蚀坑的最大深度，单位为千分之一英寸。我们对数据进行升序排序得到：

$58.5, 59.4, 65.2^*, 66.2, 67.1^*, 68, 69.4^*, 72.1, 74^*, 78.2^*, 80.3^*$

带星号 (*) 的数据表示该数据来自样本 1。因此，检验统计量的值为：

$T = 3 + 5 + 7 + 9 + 10 + 11 = 45$ $\blacksquare$
:::

假设我们希望在显著性水平 $\alpha$ 下检验 $H_0$。如果检验统计量 $T$ 的观察值为 $T = t$，则如果满足 @eq-12_4_1，我们就应当拒绝 $H_0$：

$$
P_{H_0}\{T \leq t\} \leq \frac{\alpha}{2} \quad \text{或} \quad P_{H_0}\{T \geq t\} \leq \frac{\alpha}{2}
$$ {#eq-12_4_1}

也就是说，如果第一组样本的秩的总和 $T$ 的值太小或太大，以至于从随机性角度来解释时他们发生的概率非常小，则应当拒绝假设 $H_0$。

对于整数 $t$：

$P\{T \geq t\} = 1 - P\{T < t\} = 1 - P\{T \leq t - 1\}$

根据 @eq-12_4_1，可知，在以条件下需要拒绝 $H_0$：

$$
P_{H_0}\{T \leq t\} \leq \frac{\alpha}{2} \quad \text{或} \quad P_{H_0}\{T \leq t - 1\} \geq 1 - \frac{\alpha}{2}
$$ {#eq-12_4_2}

为了计算 @eq-12_4_2 中的概率，设 $P(N, M, K)$ 表示在样本大小分别为 $N$ 和 $M$ 且 $H_0$ 为真时，第一个样本的秩的总和小于或等于 $K$ 的概率。现在我们将推导 $P(N, M, K)$ 的递归公式，这将帮助我们计算所需的概率值：$P(n, m, t) = P_{H_0}\{T \le t\}$ 和 $P(n, m, t - 1)$。

在 $N$ 和 $M$ 为样本大小且 $H_0$ 为真时，为了计算第一个样本的秩的总和小于或等于 $K$ 的概率，我们需要考虑这 $N+M$ 个数据中的最大值是来自第一个样本还是来自第二个样本。

* 如果最大值来自第一个样本，那么第一个样本的秩的总和等于 $N+M$ 加上第一个样本中剩余的 $N-1$ 个值的秩的总和。因此 $P(N, M, K)$ 等价于这 $N-1$ 个值的秩的总和小于或等于 K-(N+M)。但是因为除了最大值外，剩余的 $N-1+M$ 个数据来自同一个分布（当 $H_0$ 为真时），因此，第一个样本中剩余 $N-1$ 个值的秩的总和小于或等于 $K-(N+M)$ 的概率为 $P(N-1, M, K-N-M)$。
* 同样的，如果最大值来自第二个样本，则 $P(N, M, K)$$ 的值为 P(N, M-1, K)。

此外，由于最大值在所有 $N+M$ 个数据中的概率是相同的，所以最大值来自第一个样本的概率为 $\frac{N}{N+M}$，于是我们得到：

$$
P(N, M, K) = \frac{N}{N+M} P(N-1, M, K - N - M) + \frac{M}{N+M} P(N, M-1, K)
$$ {#eq-12_4_3}

根据初始条件：

$$
P(1, 0, K) =
\begin{cases}
0 & \text{若 } K \leq 0, \\
1 & \text{若 } K > 0,
\end{cases}
\quad
P(0, 1, K) =
\begin{cases}
0 & \text{若 } K < 0, \\
1 & \text{若 } K \geq 0
\end{cases}
$$

通过 @eq-12_4_3 的递归公式，可以求解 $P(n, m, t - 1)$ 和 $P(n, m, t)$。

::: {#exm-12_4_b}
假设我们希望计算 $P(2, 1, 3)$。我们使用 @eq-12_4_3 进行计算：


$P(2, 1, 3) = \frac{2}{3} P(1, 1, 0) + \frac{1}{3} P(2, 0, 3)$

$P(1, 1, 0) = \frac{1}{2} P(0, 1, -2) + \frac{1}{2} P(1, 0, 0) = 0$

$P(2, 0, 3) = P(1, 0, 1) = P(0, 0, 0) = 1$

因此，

$P(2, 1, 3) = \frac{1}{3}$

为了使两个 $X$ 值的秩的总和小于或等于 3，$X_1, X_2, Y_1$ 中最大的值必须是 $Y_1$。在 $H_0$ 为真的情况下，$P(2, 1, 3)$ 为 $\frac{1}{3}$。 $\blacksquare$
:::

由于秩和检验要求在以下任一条件成立时拒绝 $H_0$：

$2P(n, m, t) \leq \alpha \quad \text{或} \quad \alpha \geq 2[1 - P(n, m, t - 1)]$

因此，当 $T = t$ 时，检验统计量的 $p-\text{value}$ 为：

$p-\text{value} = 2 \min \{P(n, m, t), 1 - P(n, m, t - 1)\}$

可以使用 R 语言来获得检验统计量 $T$ 的值（在 R 中称检验统计量为 $W$）以及对应的 $p-\text{value}$。可以按照如下的步骤使用秩和检验（在 R 中称之和检验为 Wilcoxon 秩和检验）来检验数据集 $x_1, \ldots, x_n$ 和 $y_1, \ldots, y_m$ 是否来自同一分布：

```{.r}
x <- c(x1, ..., xn)
y <- c(y1, ..., ym)
wilcox.test(x, y)
```

如上代码将输出检验的 $p-\text{value}$。例如，对于 @exm-12_4_a 而言，我们可以得到如下的结果：

```{r}
#| code-fold: false
#| warning: false

x <- c(65.2,67.1,69.4,78.2,74,80.3)
y <- c(59.4,72.1,68,66.2,58.5)
wilcox.test(x, y)
```

### 检验多个概率分布是否一致 {#sec-12_4_1}
尽管前几节已经介绍了如何检验两个总体分布是否相同，但我们有时会遇到总体个数大于两个的情况。因此，假设有 $k$ 个总体，并且 $F_i$ 表示某个可测量变量在总体 $i$ 上的分布函数，我们希望检验如下的原假设：

$H_0: F_1 = F_2 = \cdots = F_k \quad vs \quad H_1: \text{并非所有的 } F_i \text{ 都相等}$

为检验上述原假设，假设从这 $k$ 个总体中独立抽取样本。令 $n_i$ 表示从总体 $i$ 中抽取的样本量 ($i = 1, \ldots, k$)，并令 $N = \sum_{i=1}^k n_i$ 表示所有样本的总数。现在，将这 $N$ 个样本值从小到大排序，并令 $R_i$ 表示从总体 $i$ 中抽取的 $n_i$ 个样本值的秩之和 ($i = 1, \ldots, k$)。

当 $H_0$ 成立时，任何一个样本值的秩都可能是 $1, \ldots, N$ 中的任意一个，因此样本值的秩的期望为：

$\overline{r} = \frac{1 + 2 + \cdots + N}{N} = \frac{N + 1}{2}$

因此，当 $H_0$ 成立时，总体 $i$ 的 $n_i$ 个样本值的秩的总和的期望为：

$E[R_i] = n_i \bar{r}$

根据拟合优度检验的启发，我们考虑如下的检验统计量：

$T = \sum_{i=1}^k \frac{(R_i - n_i \bar{r})^2}{n_i \bar{r}}$

当 $T$ 很大时，我们拒绝原假设 $H_0$。

$$
\begin{align}
T &= \frac{1}{\bar{r}} \sum_{i=1}^k \frac{R_i^2 - 2 R_i n_i \bar{r} + n_i^2 \bar{r}^2}{n_i} \\
&=\frac{1}{\bar{r}} \left( \sum_{i=1}^k \frac{R_i^2}{n_i} - 2 \sum_{i=1}^k R_i \bar{r} + \bar{r}^2 \sum_{i=1}^k n_i \right) \\
&=\frac{1}{\bar{r}} \sum_{i=1}^k \frac{R_i^2}{n_i} - N \bar{r}
\end{align}
$$

其中，最后一步的推理使用了以下性质：

$\sum_{i=1}^k R_i = 1 + 2 + \cdots + N = \frac{N(N + 1)}{2} = N \bar{r}$

因此，当 $T$ 很大时拒绝 $H_0$ 等价于当 $\sum_{i=1}^k \frac{R_i^2}{n_i}$ 很大时拒绝 $H_0$。因此，可以将检验统计量定义为：

$TS = \sum_{i=1}^k \frac{R_i^2}{n_i}$

为了确定适当的显著性水平 $\alpha$，我们需要确定当 $H_0$ 成立时 $TS$ 的分布。虽然 $T_S$ 的确切分布较为复杂，但当 $H_0$ 成立且所有 $n_i \geq 5$ 时，$\frac{12}{N(N+1)} TS - 3(N+1)$ 的分布近似为自由度为 $k-1$ 的卡方分布 $\chi^2_{k-1}$。因此，在显著性水平 $\alpha$ 下原假设 $H_0$ 的近似检验是：

$拒绝 H_0 当且仅当：\frac{12}{N(N+1)} TS - 3(N+1) \geq \chi^2_{k-1, \alpha}$

如上的检验称为 **Kruskal-Wallis 检验**。

::: {#exr-12_4_c}
以下数据为洛杉矶某中等规模的图书馆在周二、周三、周四这三天的连续 10 周的访客数量：

* 周二访客：721, 660, 622, 738, 820, 707, 672, 589, 902, 688
* 周三访客：604, 626, 744, 802, 691, 665, 711, 715, 661, 729
* 周四访客：642, 480, 705, 584, 713, 654, 704, 522, 683, 708

这些数据是否支持这三天的访客数量的分布相同的假设？
:::

::: {#sol-12_4_c}
对 $N = 30$ 个数据进行排序，得到三个样本的秩的总和分别为：

$R_1 = 176, \quad R_2 = 175, \quad R_3 = 114$

因此，

$\frac{12}{N(N+1)} TS - 3(N+1) = \frac{12}{30 \cdot 31} \left(\frac{176^2}{10} + \frac{175^2}{10} + \frac{114^2}{10}\right) - 93 = 3.254$


由于 $\chi^2_{2, 0.05} = 5.99$，因此在  5% 的显著性水平下，不能拒绝原假设 $H_0$（三天访客数量的分布相同）。

实际的 $p-\text{value}$ 为：

$\text{p-value} = P(\chi^2 \geq 3.254) = 1 - \text{pchisq}(3.254, 2) = 0.1965182$ $\blacksquare$
:::