## 随机性的游程检验 {#sec-12_5}
统计学中的一个基本假设就是：数据集由某总体的随机样本构成。然而，有时候，数据并非通过真正的随机过程产生，而是可能遵循某种趋势或循环模式。在本节中，我们将考虑一种名为 **游程检验**（*runs test*）的检验方法，**游程检验** 可用于检验给定的数据集是否为随机样本的原假设 $H_0$。

假设每个数据的取值要么是 0，要么是 1。也就是说，我们假设每个数据的值可以二分为成功（1）或失败（0）。令 $X_1, \ldots, X_N$ 表示数据集。任意连续的 1 或 0 的序列称为一个 **游程**（*run*）。例如，以下数据集：


$1 \ 0 \ 0 \ 1 \ 1 \ 1 \ 0 \ 0 \ 1 \ 0 \ 1 \ 1 \ 1 \ 1 \ 0 \ 1 \ 0 \ 0 \ 0 \ 0 \ 1 \ 1$

包含 11 个 **游程**：6 个 1 的 **游程** 和 5 个 0 的 **游程**。假设数据集 $X_1, \ldots, X_N$ 包含 $n$ 个 1 和 $m$ 个 0，其中 $n + m = N$，令 $R$ 表示 **游程** 的数量。

如果 $H_0$ 成立，那么 $X_1, \ldots, X_N$ 是 $n$ 个 1 和 $m$ 个 0 的所有 $N!/(n!m!)$ 种排列中的任何一种。因此，当 $H_0$ 成立时，**游程** 数量 $R$ 的概率质量函数为：

$P_{H_0}\{R = k\} = \frac{\text{使 \(n\) 个 \(1\) 和 \(m\) 个 \(0\) 形成 \(k\) 个游程的排列数量}}{\binom{n+m}{n}}$

可以显式确定这些排列的数量，并证明如下公式成立：

$$
\begin{align}
P_{H_0}\{R = 2k\} &= 2 \frac{\binom{m-1}{k-1} \binom{n-1}{k-1}}{\binom{m+n}{n}} \\
P_{H_0}\{R = 2k+1\} &= \frac{\binom{m-1}{k-1} \binom{n-1}{k}}{\binom{m+n}{n}} + \frac{\binom{m-1}{k} \binom{n-1}{k-1}}{\binom{m+n}{n}}
\end{align}
$$ {#eq-12_5_1}

如果数据包含 $n$ 个 1 和 $m$ 个 0，**游程检验** 在观察到的 **游程** 数量太大或太小以至于无法通过随机性解释时，则会拒绝数据为随机样本的原假设。具体而言，若观察到的 **游程** 数量为 $r$，则 **游程检验** 的 $p-\text{value}$ 为：

$p-\text{value} = 2 \min \{P_{H_0}\{R \geq r\}, P_{H_0}\{R \leq r\}\}$

当样本规模不大时，可以使用 @eq-12_5_1 来精确的计算出 $p-\text{value}$。

::: {#exm-12_5_a}
以下是某球队最近 30 场比赛的结果，其中 $W$ 表示胜利，$L$ 表示失败。

$W \, W \, W \, L \, W \, W \, L \, W \, W \, L \, W \, L \, W \, W \, W \, W \, W \, L \, W \, L \, L \, W \, W \, W \, L \, W \, L \, W \, L \, L$

这些数据是纯随机产生的吗？
:::

::: {#sol-12_5_a}
为了检验随机性假设，需要注意以下事实：该数据包含 20 次 $W$ 和 10 次 $L$，并且有 20 个 **游程**（*run*）。为了在 5% 的显著性水平下判断是否拒绝数据是纯随机的这一假设，我们可以使用先前的公式计算 $p-\text{value}$。经计算，我们得到 $p-\text{value}= 0.01845$，因此，在 5% 的显著性水平下，可以拒绝随机性的原假设。

值得注意的是，这些数据中一个显著的特点是：每当该队输掉一场比赛后，他们总能在下一场比赛中获胜。如果胜利和失败的概率均等，则包含 20 次胜利和 10 次失败的所有结果中，如上数据发生的可能性则非常低。$\blacksquare$
:::

当数据值不是 0 和 1 的情况下，我们仍然可以用 **游程检验** 来检验数据的随机性。为了检验数据 $X_1, \ldots, X_N$ 是否构成一个随机样本，令 $s\text{-med}$ 表示样本中位数。同时，令 $n$ 表示小于等于 $s\text{-med}$ 的数据值的数量，$m$ 表示大于 $s\text{-med}$ 的数据值的数量。（因此，如果 $N$ 是偶数并且所有数据值互不相同，那么 $n$ = $m$ = $N / 2$。）

定义 $I_1, \ldots, I_N$ 为：

$$
I_j =
\begin{cases}
1, & \text{如果 } X_j \leq s\text{-med} \\
0, & \text{否则}
\end{cases}
$$

如果原始数据构成一个随机样本，那么 $I_1, \ldots, I_N$ 中的 **游程**（*runs*）的数量的概率质量函数如 @eq-12_5_1 所示。因此，我们可以使用 **游程检验**（*runs test*）对数据值 $I_1, \ldots, I_N$ 进行检验，以判断原始数据是否是随机数据。

::: {#exm-12_5_b}
某电池生产线上连续生产的 19 块电池的寿命如下：

$145, 152, 148, 155, 176, 134, 184, 132, 145, 162, 165, 185, 174, 198, 179, 194, 201, 169, 182$

样本的中位数是第 10 个最小的值——即 169。根据数据值是小于等于还是大于 169，可得到如下数据：

$1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0$

因此，**游程**（*runs*）的数量为 8。根据 @eq-_12_5_1，可得：

$p\text{-value} = 0.357$

因此，我们接受数据是随机数据的假设。$\blacksquare$
:::

当 $n$ 和 $m$ 都很大并且原假设 $H_0$ 成立时，**游程** 数量 $R$ 近似服从正态分布并且其均值、标准差分别为：

$$
\begin{align}
\mu &= \frac{2nm}{n + m} + 1 \\
\sigma &= \sqrt{\frac{2nm(2nm - n - m)}{(n + m)^2(n + m - 1)}}
\end{align}
$$ {#eq-12_5_2}

因此，当 $n$ 和 $m$ 都很大时，

$$
\begin{align}
P_{H_0}\{R \leq r\} &= P_{H_0}\left\{\frac{R - \mu}{\sigma} \leq \frac{r - \mu}{\sigma}\right\} \\
&\approx P\left\{Z \leq \frac{r - \mu}{\sigma}\right\}, \quad Z \sim N(0, 1) \\
&= \Phi\left(\frac{r - \mu}{\sigma}\right)
\end{align}
$$

因此，$P_{H_0}\{R \geq r\} \approx 1 - \Phi\left(\frac{r - \mu}{\sigma}\right)$

因此，当 $n$ 和 $m$ 都很大时，**游程检验** 的 $p-\text{value}$ 近似为：

$\text{p-value} \approx 2 \min \left\{\Phi\left(\frac{r - \mu}{\sigma}\right), 1 - \Phi\left(\frac{r - \mu}{\sigma}\right)\right\}$

其中，$\mu$ 和 $\sigma$ 的值由 @eq-12_5_2 给出，$r$ 是观测到的 **游程** 数量。

::: {#exm-12_5_c}
假设一个序列包含 60 个 1 和 60 个 0，该序列中的 **游程**（*runs*）数量为 75。由于

$\mu = 61, \quad \sigma = \sqrt{\frac{3540}{119}} = 5.454$

因此，$p-\text{value}$ 近似为：

$$
\begin{align}
p\text{-value} &\approx 2 \min\{\Phi(2.567), 1 - \Phi(2.567)\} \\
&= 2 \times (1 - 0.9949) \\
&= 0.0102
\end{align}
$$

另一方面，可以证明，$p-\text{value}$ 的精确值为：

$p\text{-value} = 0.0130$


如果 **游程**（*runs*）数量不是 75，而是 70，那么 $p-\text{value}$ 的近似值将为：

$p\text{-value} \approx 2[1 - \Phi(1.650)] = 0.0990$

而 $p-\text{value}$ 的精确值为：

$p\text{-value} = 0.1189$ $\blacksquare$
:::