## 置换检验 {#sec-15_4}

假设我们想要检验原假设 $H_0$ ：数据 $X_1, \ldots, X_N$ 是来自某个未指定分布的样本。**置换检验** (*permutation tests*) 是对该假设的一种检验，其中 $p$ 值的计算是在已知观测到的数据值集合 $S$ 但不知道具体哪个数据值对应 $X_1$ 、哪个对应 $X_2$ 等的前提下进行的。例如，若 $N = 3$ 且 $X_1 = 5, X_2 = 7, X_3 = 2$ ，那么 $p$ 值的计算条件是已知数据值集合 $S = \{2, 5, 7\}$ 。$p$ 值的计算利用了这样一个事实：在原假设为真时，给定数据值集合 $S$ ，将这 $N$ 个值分配给原始数据的 $N!$ 种可能方式中的每一种都是等可能的。也就是说，假设 $N = 3$ 且数据值集合如前所述为 $S = \{2, 5, 7\}$ 。现在原假设 $H_0$ 指出 $X_1, X_2, X_3$ 是独立同分布的。因此，如果 $H_0$ 为真，那么在给定数据集 $S$ 的情况下，向量 $(X_1, X_2, X_3)$ 等于值 $2, 5, 7$ 的 $3!$ 种置换中的任何一种的概率都是相等的。

置换检验的实施过程如下。根据备择假设，选择一个检验统计量 $T(X_1, \ldots, X_N)$ 。暂时假设检验统计量的较大值是备择假设的证据。然后观测数据值，设 $X_i = x_i, i = 1, \ldots, N$ ，并计算 $T(x_1, \ldots, x_N)$ 的值。令 $S = \{x_1, \ldots, x_N\}$ 为由 $N$ 个观测值组成的无序集合。那么，如果检验统计量的值为 $T(x_1, \ldots, x_N) = t$ ，则由这些数据产生的原假设的 $p$ 值为：

$$ p\text{-value} = P_{H_0}(T(X_1, \ldots, X_N) \geq t \mid S = \{x_1, \ldots, x_N\}) $$ {#eq-15_4_1}

现在，在 $H_0$ 下，$X_1, \ldots, X_N$ 等可能地等于 $x_1, \ldots, x_N$ 的 $N!$ 种置换中的任何一种。因此，令 $I_1, \ldots, I_N$ 为一个随机向量，它等可能地取 $1, \ldots, N$ 的 $N!$ 种置换中的任何一种，我们可以将上述 $p$ 值写为：

$$
\begin{align*}
p\text{-value} &= P(T(x_{I_1}, x_{I_2}, \ldots, x_{I_N}) \geq t) \\
&= \frac{\text{满足 } T(x_{i_1}, x_{i_2}, \ldots, x_{i_N}) \geq t \text{ 的置换 } (i_1, \ldots, i_N) \text{ 的个数}}{N!}
\end{align*}
$$ {#eq-15_4_2}

为了说明，假设要在 $N$ 周内观测数据，其中 $X_i$ 是在第 $i$ 周观测到的数据值，并且我们想要检验原假设：

$H_0$ ：$X_1, \ldots, X_N$ 是独立同分布的

对抗备择假设：

$H_1$ ：$X_i$ 随 $i$ 的增加而呈现增加趋势

现在，如果原假设为真且数据是独立同分布的，那么在已知值集合 $\{X_1, \ldots, X_N\}$ 但不知道哪个值对应 $X_1$ 或哪个对应 $X_2$ 等的情况下，统计量 $\sum_{j=1}^N j X_j$ 的分布就好像我们随机配对了两个数据集 $\{1, \ldots, N\}$ 和 $\{X_1, \ldots, X_N\}$ 然后对这 $N$ 对配对值的乘积求和。另一方面，如果备择假设为真，那么 $\sum_{j=1}^N j X_j$ 往往比我们仅仅随机配对值时的趋势更大。这是因为两个同等大小集合的配对值之和在最大值与最大值配对、次大值与次大值配对等情况下达到最大。（在统计学术语中，当 $X_j$ 随 $j$ 增加而增加时，数据对 $(j, X_j), j = 1, \ldots, N$ 的相关系数较大。）因此，$H_0$ 对抗 $H_1$ 的一种可能的置换检验是：

1. 观测数据值——设 $X_j = x_j, j = 1, \ldots, N$ 。
2. 令 $t = \sum_{j=1}^N j x_j$ 。
3. 确定由下式给出的 $p$ 值：
   $$ p\text{-value} = P\left(\sum_{j=1}^N I_j x_j \geq t\right) $$ {#eq-15_4_3}
   其中 $I_1, \ldots, I_N$ 等可能地为 $1, \ldots, N$ 的 $N!$ 种置换中的任何一种。

上述 $p$ 值可以通过使用 @exm-15_2_b 的方法生成随机置换进行模拟近似。

::: {#exm-15_4_a}
为了确定 DVD 播放机的周销量是否呈下降趋势，一家大型电子商店的经理记录了过去 12 周的此类销量，从第 1 周到第 12 周（本周）的结果如下：
$$22, 24, 20, 18, 16, 14, 15, 15, 13, 17, 12, 14$$
这些数据是否足够强大，足以拒绝销量分布随时间不变的原假设，从而使经理能够得出销量呈下降趋势的结论？

**解** ：令原假设为销量分布随时间不变，备择假设为销量呈下降趋势。因此，如果备择假设为真，那么第 $j$ 周的销量 $X_j$ 与 $j$之间将存在负相关。因此，$\sum_{j=1}^{12} j X_j$ 的相对较小值将是支持备择假设的证据。现在，设 $x_j$ 为 $X_j$ 的观测值，销售数据给出：
$$ \sum_{j=1}^{12} j x_j = 1178 $$
因此，数据来自同一分布的原假设对抗数据随时间递减的备择假设的置换检验的 $p$ 值由下式给出：
$$ p\text{-value} = P\left(\sum_{j=1}^{12} I_j x_j \leq 1178\right) $$
其中 $I_1, \ldots, I_{12}$ 等可能地为 $1, \ldots, 12$ 的 $12!$ 种置换中的任何一种。使用 $10^5$ 次运行进行的模拟得出：
$$ p\text{-value} \approx .00039 $$
这引导我们拒绝销量分布随时间不变的原假设。
$\blacksquare$
:::

虽然 $\sum_{j=1}^N j X_j$ 是最常用于检验 $X_1, \ldots, X_n$ 独立同分布原假设对抗 $X_j$ 随 $j$ 增加而增加的备择假设的检验统计量，但它并不是唯一的可能性。实际上，我们可以选择任何形式为 $\sum_{j=1}^N a_j X_j$ 的检验统计量，其中 $a_1 < a_2 < \ldots < a_n$ 。（例如，我们可以选择 $a_j = j^2$ 。）与前述类似，首先确定统计量的值，设其为 $t$ 。因为当备择假设为真时，较大的 $a_j$ 值往往会与较大的数据值配对，从而使得 $\sum_{j=1}^N a_j X_j$ 趋向于变得更大。因此，当 $t$ 较大时，我们同样希望拒绝原假设。于是，所得的 $p$ 值为：
$$ p\text{-value} = P\left(\sum_{j=1}^N a_{I_j} x_j \geq t\right) $$ {#eq-15_4_4}
其中 $I_1, \ldots, I_N$ 等可能地为 $1, \ldots, N$ 的 $N!$ 种置换中的任何一种。

根据备择假设的不同，我们可以选择其他的常数 $a_j, j = 1, \ldots, N$ 来检验数据值独立同分布的原假设。例如，如果备择假设是数据在中间值趋于更高而在极端值趋于更低，那么我们可以让检验统计量的形式为 $T = \sum_{j=1}^N a_j X_j$ ，其中 $a_1, \ldots, a_N$ 使得中间位置的常数比两端的更大。例如，我们可以使用 $a_j = j(N - j), j = 1, \ldots, N$ 。由于这同样使得当备择假设为真时，较大的数据值更有可能与较大的常数配对，因此当 $T$ 较大时，我们仍然希望拒绝原假设。

### 置换检验中的正态近似 {#sec-15_4_1}

虽然不如进行模拟那样准确，但可以通过假设检验统计量近似服从正态分布来估算置换检验的 $p$ 值。现在，在数据值独立同分布的原假设下，给定数据集 $S = \{x_1, \ldots, x_N\}$ ，随机变量 $X_i$ 等可能地为这 $N$ 个值中的任何一个，并且当 $i \neq j$ 时，随机向量 $(X_i, X_j)$ 等可能地取 $x_k, x_r (r \neq k)$ 这 $N(N - 1)$ 个值中的任何一个。因此，给定 $S = \{x_1, \ldots, x_N\}$ ：

$$ E[X_i] = \frac{1}{N} \sum_{i=1}^N x_i = \bar{x} $$ {#eq-15_4_5}
$$ E[X_i^2] = \frac{1}{N} \sum_{i=1}^N x_i^2 $$ {#eq-15_4_6}
$$
\begin{align*}
E[X_i X_j] &= \frac{1}{N(N - 1)} \sum_k \sum_{r \neq k} x_k x_r \\
&= \frac{1}{N(N - 1)} \left( \sum_k \sum_r x_k x_r - \sum_k \sum_{r=k} x_k x_r \right) \\
&= \frac{1}{N(N - 1)} \left( \sum_k x_k \sum_r x_r - \sum_k x_k^2 \right) \\
&= \frac{1}{N(N - 1)} \left( N^2 \bar{x}^2 - \sum_{k=1}^N x_k^2 \right)
\end{align*}
$$ {#eq-15_4_7}

因此，令 $v = \text{Var}(X_i)$ 且 $c = \text{Cov}(X_i, X_j), i \neq j$ ，上述推导给出：

$$ E[X_i] = \bar{x} $$
$$ v = \text{Var}(X_i) = \frac{1}{N} \sum_{i=1}^N x_i^2 - \bar{x}^2 $$ {#eq-15_4_8}
$$ c = \text{Cov}(X_i, X_j) = \frac{1}{N(N - 1)} (N^2 \bar{x}^2 - \sum_{k=1}^N x_k^2) - \bar{x}^2 $$ {#eq-15_4_9}
$$ v - c = \frac{\sum_{i=1}^N x_i^2 - N \bar{x}^2}{N - 1} $$ {#eq-15_4_10}

因此，当 $H_0$ 为真时，检验统计量 $T = \sum_{j=1}^N j X_j$ 的均值为：
$$ E[T] = \frac{N(N + 1)}{2} \bar{x} $$ {#eq-15_4_11}
方差为：
$$
\begin{align*}
\text{Var}(T) &= \text{Var}\left(\sum_{j=1}^N j X_j\right) \\
&= \sum_{j=1}^N \text{Var}(j X_j) + \sum_i \sum_{j \neq i} \text{Cov}(i X_i, j X_j) \\
&= v \sum_{j=1}^N j^2 + c \sum_i \sum_{j \neq i} i j \\
&= v \sum_{j=1}^N j^2 + c \left( \sum_i \sum_j i j - \sum_i \sum_{j=i} i j \right) \\
&= v \sum_{j=1}^N j^2 + c \left( \sum_{i=1}^N i \sum_{j=1}^N j - \sum_{i=1}^N i^2 \right) \\
&= (v - c) \sum_{j=1}^N j^2 + \frac{c N^2(N + 1)^2}{4} \\
&= (v - c) \frac{N(N + 1)(2N + 1)}{6} + \frac{c N^2(N + 1)^2}{4}
\end{align*}
$$ {#eq-15_4_12}

利用上述结果，我们可以通过假设 $T$ 在 $H_0$ 为真时近似服从正态分布，来估算置换检验的 $p$ 值。

::: {#exm-15_4_b}
再次考虑 @exm-15_4_a 。计算得出，在 $H_0$ 下：
$$ E[T] = 1300 \quad \text{Var}(T) = 1958.81 $$
因此，正态近似得出：
$$
\begin{align*}
p\text{-value} &= P_{H_0}(T \leq 1178) \\
&= P_{H_0}\left( \frac{T - 1300}{\sqrt{1958.81}} \leq \frac{1178 - 1300}{\sqrt{1958.81}} \right) \\
&\approx \Phi(-2.757) = .0029
\end{align*}
$$
这与模拟给出的值非常接近。

现在假设 12 个数据值虽然与之前相同，但它们现在的出现顺序为：
$$22, 14, 14, 16, 24, 20, 18, 15, 17, 15, 12, 13$$
对于这些数据，检验统计量的值为 $\sum_{j=1}^{12} j X_j = 1233$ ，正态近似得出：
$$
\begin{align*}
p\text{-value} &= P_{H_0}(T \leq 1233) \\
&= P_{H_0}\left( \frac{T - 1300}{\sqrt{1958.81}} \leq \frac{1233 - 1300}{\sqrt{1958.81}} \right) \\
&\approx \Phi(-1.514) = .065
\end{align*}
$$

最后，再次假设这 12 个数据值与之前相同，但假设它们现在的出现顺序为：
$$22, 14, 14, 16, 24, 13, 18, 15, 17, 15, 12, 20$$
在这种情况下，检验统计量的值为 $\sum_{j=1}^{12} j X_j = 1275$ 。因此，正态近似得出：
$$
\begin{align*}
p\text{-value} &= P_{H_0}(T \leq 1275) \\
&= P_{H_0}\left( \frac{T - 1300}{\sqrt{1958.81}} \leq \frac{1275 - 1300}{\sqrt{1958.81}} \right) \\
&\approx \Phi(-.565) \approx .286
\end{align*}
$$
$10^5$ 次运行的模拟得出了与上述非常相似的值。模拟给出：
$$ P_{H_0}(T \leq 1233) \approx .068 $$
且
$$ P_{H_0}(T \leq 1275) \approx .299 $$
这些值与正态近似给出的值相当接近。
$\blacksquare$
:::

::: {#exm-15_4_c}
为了进一步说明正态近似的有效性，假设 $N = 4$ ，且数据按以下顺序出现：
$$13, 7, 5, 3$$
假设我们想使用这些数据来检验原假设：数据是来自某个分布的样本，对抗备择假设：数据趋于递减。检验统计量的值为 $T = \sum_{j=1}^4 j X_j = 54$ 。简单的计算得出：
$$ c = -4.667, \quad v = 14 $$
表明在 $H_0$ 下：
$$ E[T] = 70, \quad \text{Var}(T) = 93.33 $$
因此，令 $Z$ 为标准正态随机变量，正态近似得出：
$$
\begin{align*}
p\text{-value} &= P_{H_0}(T \leq 54) \\
&= P_{H_0}\left( \frac{T - 70}{\sqrt{93.33}} \leq \frac{54 - 70}{\sqrt{93.33}} \right) \\
&\approx P(Z \leq -1.656) = .049
\end{align*}
$$
而精确值为：
$$ p\text{-value} = P_{H_0}(T \leq 54) = 1/4! \approx .042 $$
$\blacksquare$
:::

### 两样本置换检验 {#sec-15_4_2}

置换检验在两样本问题中也很有用，即检验来自两个总体的样本是否具有相同的潜在分布。具体而言，令 $X_1, \ldots, X_n$ 是来自未知总体分布 $F$ 的样本，并令 $X_{n+1}, \ldots, X_{n+m}$ 是来自未知总体分布 $G$ 的独立样本。假设我们要利用这些数据来检验原假设：两个总体分布是相同的，对抗备择假设：来自第二个分布的数据往往比来自第一个分布的数据更大。也就是说，我们要检验原假设：

$H_0: F = G$

对抗备择假设：

$H_1$ ：来自 $G$ 的数据倾向于比来自 $F$ 的数据更大

如果数据值为 $X_i = x_i, i = 1, \ldots, n + m$ ，那么上述原假设的置换检验是在已知 $S = \{x_1, \ldots, x_{n+m}\}$ （这 $n+m$ 个数且无特定顺序）的前提下进行的。如果 $H_0$ 为真，那么 $n+m$ 个随机变量 $X_1, \ldots, X_{n+m}$ 都是独立同分布的，那么给定值集合 $S$ ，该集合中大小为 $n$ 的每个子集作为 $X_1, \ldots, X_n$ 的数据值集合的可能性是相等的。由于备择假设是总体分布 $F$ 的数据趋向于小于总体分布 $G$ 的数据，一个合理的检验是：如果从数据集 $S$ 中随机选择 $n$ 个值时，来自总体分布 $F$ 的数据值之和小于可能由机会预期的值，则拒绝原假设。更具体地说，我们可以通过计算 $\sum_{i=1}^n x_i$ 来检验 $H_0$ ；设其值为 $t$ 。那么 $H_0$ 对抗 $H_1$ 的置换检验的 $p$ 值将等于从值 $x_1, \ldots, x_{n+m}$ 中随机选择 $n$ 个值的和小于或等于 $t$ 的概率。即：

$$ p\text{-value} = P\left( \sum_{i \in R} x_i \leq t \right) $$ {#eq-15_4_13}

其中 $R$ 等可能地为从集合 $\{1, 2, \ldots, n + m\}$ 中选出的 $\binom{n+m}{n}$ 个大小为 $n$ 的子集中的任何一个。虽然仅当 $\binom{n+m}{n}$ 较小时才可能进行精确计算，但通过模拟很容易获得精确的近似值。在每次模拟运行中，我们使用 @exm-15_2_a 的方法随机生成值 $1, \ldots, n + m$ 的一个大小为 $n$ 的子集。如果得到的子集是 $R$ ，那么我们检查 $\sum_{i \in R} x_i$ 是否小于或等于 $t$ 。模拟运行中满足该条件的比例即为我们对前述 $p$ 值的估计。

**注** ：我们再次可以使用正态近似，而不是模拟，来估计 $p$ 值。从随机子集 $R$ 开始（等可能地为集合 $\{1, 2, \ldots, n + m\}$ 的 $\binom{n+m}{n}$ 个大小为 $n$ 的子集中的任何一个），令对于 $i = 1, \ldots, n + m$ ：

$$ I_i = \begin{cases} 1, & \text{如果 } i \in R \\ 0, & \text{如果 } i \notin R \end{cases} $$

那么，
$$ \sum_{i \in R} x_i = \sum_{i=1}^{n+m} x_i I_i $$ {#eq-15_4_14}

通过与 @sec-15_4_1 中类似的分析，我们现在可以得出：

$$ E_{H_0}\left[ \sum_{i \in R} x_i \right] = E_{H_0}\left[ \sum_{i=1}^{n+m} x_i I_i \right] = n \bar{x} $$ {#eq-15_4_15}

且

$$ \text{Var}_{H_0}\left( \sum_{i \in R} x_i \right) = \text{Var}_{H_0}\left( \sum_{i=1}^{n+m} x_i I_i \right) = \frac{nm}{n + m - 1} \left( \frac{\sum_{i=1}^{n+m} x_i^2}{n + m} - \bar{x}^2 \right) $$ {#eq-15_4_16}

其中 $\bar{x} = \sum_{i=1}^{n+m} x_i / (n + m)$ 。
