## 连续随机变量的生成 {#sec-15_6}

令 $F$ 为连续随机变量的分布函数。对于介于 $0$ 和 $1$ 之间的任何 $u$ ，量 $F^{-1}(u)$ 被定义为满足 $F(x) = u$ 的 $x$ 值。也就是说，$F(F^{-1}(u)) = u$ 。由于连续随机变量的分布函数是严格递增的，因此 $F^{-1}(u)$ 的值是唯一的。我们称 $F^{-1}$ 为 $F$ 的反函数。

一种生成具有分布函数 $F$ 的连续随机变量的通用方法被称为**逆变换方法** (*inverse transformation method*)，它基于以下命题。

::: {#thm-15_6_1}
令 $U$ 为均匀 $(0, 1)$ 随机变量。对于任何连续分布函数 $F$ ，如果我们定义
$$ X = F^{-1}(U) $$ {#eq-15_6_1}
那么 $X$ 具有分布函数 $F$ 。
:::

**证明** ：因为分布函数 $F$ 是非减的，所以对于任何数字 $a$ 和 $b$ ，不等式 $a \leq b$ 等价于不等式 $F(a) \leq F(b)$ 。因此，
$$ P(F^{-1}(U) \leq x) = P(F(F^{-1}(U)) \leq F(x)) = P(U \leq F(x)) = F(x) $$ {#eq-15_6_2}
从而表明 $F^{-1}(U)$ 具有分布 $F$ 。
$\blacksquare$

::: {#exm-15_6_a}
（**生成指数随机变量**）令
$$ F(x) = 1 - e^{-\lambda x}, \quad x \geq 0 $$ {#eq-15_6_3}
为具有参数 $\lambda$ 的指数随机变量的分布函数。那么 $F^{-1}(u)$ 是满足下式的 $x$ 值：
$$ u = F(x) = 1 - e^{-\lambda x} $$
或等价地，
$$ e^{-\lambda x} = 1 - u $$
或
$$ -\lambda x = \log(1 - u) $$
或
$$ x = -\frac{1}{\lambda} \log(1 - u) $$
因此，根据 @thm-15_6_1，我们可以通过生成一个均匀 $(0, 1)$ 随机变量 $U$ 并设定如下方式来生成具有参数 $\lambda$ 的指数随机变量 $X$ ：
$$ X = -\frac{1}{\lambda} \log(1 - U) $$ {#eq-15_6_4}
由于 $1 - U$ 也是一个均匀 $(0, 1)$ 随机变量，因此得出 $-\frac{1}{\lambda} \log(1 - U)$ 和 $-\frac{1}{\lambda} \log(U)$ 具有相同的分布，从而表明
$$ X = -\frac{1}{\lambda} \log(U) $$ {#eq-15_6_5}
也是参数为 $\lambda$ 的指数分布。
$\blacksquare$
:::

### 正态随机变量的生成 {#sec-15_6_1}

由于反转正态随机变量的分布函数在计算上比较复杂，因此使用了特殊的方法来生成正态随机变量。以下方法被称为 **Box-Muller 方法** (*Box-Muller method*)。


首先，假设 $X$ 和 $Y$ 是独立的标准正态随机变量，因此它们的联合密度函数为
$$ f(x, y) = \frac{1}{\sqrt{2\pi}} e^{-x^2 / 2} \frac{1}{\sqrt{2\pi}} e^{-y^2 / 2} = \frac{1}{2\pi} e^{-(x^2 + y^2) / 2}, \quad -\infty < x, y < \infty $$ {#eq-15_6_6}
令 $R, \Theta$ 为点 $(X, Y)$ 的**极坐标** (*polar coordinates*)。现在根据定义，$R^2 = X^2 + Y^2$ 是具有 2 个自由度的**卡方随机变量** (*chi-square random variable*)，如 @sec-5_8_1 所示，该分布与参数为 $1/2$ 的**指数分布** (*exponential distribution*) 相同（即均值为 2）。因此，$R^2$ 的密度函数为
$$ f_{R^2}(r) = \frac{1}{2} e^{-r / 2}, \quad 0 < r < \infty $$ {#eq-15_6_7}
现在考虑给定 $R^2 = r$ 时 $X, Y$ 的条件联合密度函数。因为
$$ f(x, y) = \frac{1}{2\pi} e^{-r / 2} \quad \text{当 } x^2 + y^2 = r $$
是一个常数（当 $x^2 + y^2 = r$ 时），因此直观上可以证明（并且可以证明）：在给定 $R^2 = r$ 的条件下，向量 $(X, Y)$ 均匀分布在半径为 $\sqrt{r}$ 的圆周上。但这暗示了：在给定 $R^2 = r$ 的条件下，点 $(X, Y)$ 的极坐标 $\Theta$ 在 $(0, 2\pi)$ 上均匀分布。因为这对所有的 $r$ 都成立，所以极坐标 $R$ 和 $\Theta$ 是独立的，其中 $R$ 服从均值为 2 的指数随机变量的平方根分布，而 $\Theta$ 是 $(0, 2\pi)$ 上的均匀随机变量。

利用前述内容，我们可以通过首先生成它们的极坐标 $R$ 和 $\Theta$ 来生成独立的标准正态随机变量 $X$ 和 $Y$ 。由于 $-\log(U)$ 是均值为 1 的指数分布，我们可以通过生成独立的均匀 $(0, 1)$ 随机变量 $U_1$ 和 $U_2$ ，然后设定如下方式来生成 $(X, Y)$ 的极坐标：
$$ R^2 = -2 \log(U_1) $$
且
$$ \Theta = 2\pi U_2 $$
利用极坐标 $R, \Theta$ 回到直角坐标的公式
$$ X = R \cos(\Theta), \quad Y = R \sin(\Theta) $$
表明
$$ X = \sqrt{-2 \log(U_1)} \cos(2\pi U_2) $$ {#eq-15_6_8}
$$ Y = \sqrt{-2 \log(U_1)} \sin(2\pi U_2) $$ {#eq-15_6_9}
是独立的标准正态随机变量。

要生成均值为 $\mu$ 、方差为 $\sigma^2$ 的正态随机变量，只需生成独立的标准正态变量 $X$ 和 $Y$ ，然后取变量 $\mu + \sigma X$ 和 $\mu + \sigma Y$ 。
