## 显著性水平 {#sec-8_2}
考虑一个分布为 $F_{\theta}$ 的总体，其中 $\theta$ 是未知的。假设我们要检验关于 $\theta$ 的特定 **假设**，我们将此假设记为 $H_0$，并称之为 **原假设**（*null hypothesis*）。例如，如果 $F_{\theta}$ 是均值为 $\theta$、方差为 1 的正态分布，那么关于 $\theta$ 的两个可能的 **原假设** 是：

1. $H_0: \theta = 1$
2. $H_0: \theta \le 1$

因此，第一个 **假设** 表明总体是均值为 1 且方差为 1 的正态分布，而第二个 **假设** 表明总体是方差为 1 且均值小于或等于 1 的正态分布。注意，第一个 **原假设** 为真时，完全确定了总体分布，而当第二个 **原假设** 为真时，则没有完全确定总体分布。如果一个 **假设** 为真可以完全确定总体分布，我们称这样的 **假设** 为 **简单假设**（*simple hypothesis*）；否则，我们称之为 **复合假设**（*composite hypothesis*）。

假设现在为了检验特定的 **原假设** $H_0$，我们将观察一个样本大小为 $n$ 的总体样本——例如 $X_1, \ldots, X_n$。基于这 $n$ 个值，我们必须决定是否接受 $H_0$。可以通过在 $n$ 维空间中定义一个区域 $C$ 来指定 $H_0$ 的检验：如果随机样本 $X_1, \ldots, X_n$ 位于 $C$ 中，则拒绝 **假设**，否则接受 **假设**。该区域 $C$ 称之为 **临界区**（*critical region*）。换句话说，由 **临界区** $C$ 确定的统计检验是：

* 接受 $H_0$：如果 $(X_1, X_2, \ldots, X_n) \notin C$
* 拒绝 $H_0$：如果 $(X_1, \ldots, X_n) \in C$

例如，一个关于方差为 1 的正态分布的均值 $\theta$ 的常见假设——均值等于 1 的检验，其 **临界区** 由以下公式给出：

$$
C = \{(X_1, \ldots, X_n) : |\overline{X} - 1| > 1.96 / \sqrt{n}\}
$$ {#eq-8_2_1}

因此，当样本均值与 1 的差值超过 1.96 除以样本大小的平方根时，则拒绝 $\theta = 1$ 的 **原假设**。

::: {.callout-warning title="注意"}
重要的是，在任何检验中，可能会出现两种不同类型的错误。

* 第一种错误，称之为 **I 型错误**，是指检验错误地拒绝了实际上正确的 $H_0$。
* 第二种错误，称之为 **II 型错误**，是指检验错误地接受了实际上不正确的 $H_0$。
:::

如前所述，统计检验 $H_0$ 的目标不是明确确定 $H_0$ 是否为真，而是确定 $H_0$ 是否与结果数据一致。因此，基于这个目标，合理的做法是：仅当 $H_0$ 为真时，并且结果数据非常不可能出现时，才拒绝 $H_0$。传统的方法是指定一个值 $\alpha$ ，然后要求检验具有这样的性质：每当 $H_0$ 为真时，$H_0$ 被拒绝的概率绝不超过 $\alpha$。这个 $\alpha$ 值，称之为 **检验的显著性水平**（*level
 of significance of the test*）。通常会预先设定检验的显著性水平，常用的值有 $\alpha = 0.1, 0.05, 0.005$。
 
 换句话说，传统的检验 $H_0$ 的方法是固定一个显著性水平 $\alpha$ ，然后要求检验具有这样的性质：发生 **I 型错误** 的概率绝不能超过 $\alpha$。

$\theta$ 是总体的一个未知参数，假设现在我们对检验一个关于 $\theta$ 的特定 **假设** 感兴趣。具体来说，对于给定的参数值集合 $w$，假设我们对如下的检验感兴趣：

$H_0 : \theta \in w$

在 $\alpha$ 下检验 $H_0$ 的一种常见方法是，从确定 $\theta$ 的点估计量——记为 $d(\mathbfit{X})$ 开始。

当 $d(\mathbfit{X})$ 远离区域 $w$ 时，则拒绝 **假设**。然而，为了确定 $d(\mathbfit{X})$ 需要多远才能证明拒绝 $H_0$ 是合理的，我们需要确定当 $H_0$ 为真时 $d(\mathbfit{X})$ 的概率分布。因为这通常能帮助我们确定适当的 **临界区**，从而使检验达到所需的 **显著性水平** $\alpha$。例如，@eq-8_2_1 给出的参数为 $(\theta, 1)$ 的总体均值等于 1 的假设检验，当 $\theta$ 的 **点估计量**——即样本均值——与 1 之间的距离超过 $1.96/\sqrt{n}$ 时，则拒绝 **假设**。正如我们将在 @sec-8_3 中所讲述的，选择 $1.96/\sqrt{n}$ 是为了满足 **显著性水平** $\alpha = 0.05$。