## 关于正态总体方差的假设检验 {#sec-8_5}
假设 $X_1, \dots, X_n$ 是来自正态分布总体的样本，该总体具有未知均值 $\mu$ 和未知方差 $\sigma^2$，并且我们希望检验以下的假设：

$H_0 : \sigma^2 = \sigma_0^2 \quad vs \quad H_1 : \sigma^2 \neq \sigma_0^2$

其中 $\sigma_0^2$ 是一个特定的值。

当 $H_0$ 为真时，如 @thm-6_5_1 所述，$(n-1)S^2/\sigma_0^2$ 服从自由度为 $n-1$ 的卡方分布，因此：

$\frac{(n-1)S^2}{\sigma_0^2} \sim \chi^2_{n-1}$

由于 $P\{\chi^2_{n-1} < \chi^2_{\alpha/2, n-1}\} = 1 - \alpha/2$ 且 $P\{\chi^2_{n-1} < \chi^2_{1-\alpha/2, n-1}\} = \alpha/2$，由此得出

$P_{H_0} \left\{ \chi^2_{1-\alpha/2, n-1} \leq \frac{(n-1)S^2}{\sigma_0^2} \leq \chi^2_{\alpha/2, n-1} \right\} = 1 - \alpha$

因此，在显著性水平为 $\alpha$ 下的检验为：

$$
\begin{align}
\text{接受} H_0&, \quad \text{如果} \chi^2_{1-\alpha/2, n-1} \leq \frac{(n-1)S^2}{\sigma_0^2} \leq \chi^2_{\alpha/2, n-1} \\
\text{拒绝} H_0&, \quad \text{否则}
\end{align}
$$

如上的检验可以通过：

1. 首先，计算检验统计量 $(n-1)S^2/\sigma_0^2$ 的值——我们称之为 $c$——来实现
2. 然后，计算自由度为 $n-1$ 的卡方分布随机变量大于 $c$ 或者小于 $c$ 的概率
3. 如果如上的概率中的任一个概率小于 $\alpha/2$，则拒绝原假设。换句话说，该检验的 $p-\text{value}$ 为：

$p-\text{value} = 2 \min \left( P\{\chi^2_{n-1} < c\}, 1 - P\{\chi^2_{n-1} < c\} \right)$

同样，也可以使用类似的方法得到单边检验的 $p-\text{value}$。我们可以使用 R 命令 `pchisq(c, n-1)` 得到 $P\{\chi^2_{n-1} < c\}$ 的值。

::: {#exr-8_5_a}
最近安装了一台自动控制磁带长度的机器。如果磁带长度的标准差 $\sigma$ 小于 0.15 厘米，则认为该机器是有效的。如果 20 个磁带样本的方差 $S^2 = 0.025 \ \text{cm}^2$，我们能否得出该机器无效的结论？
:::

::: {#sol-8_5_a}
我们将检验该机器有效的假设，因为拒绝这个假设将使我们得出该机器无效的结论。因此，我们检验以下假设：

$H_0: \sigma^2 \leq 0.0225 \quad vs \quad H_1: \sigma^2 > 0.0225$

因此，当 $S^2$ 较大时，我们会拒绝 $H_0$。测试数据的 $p-\text{value}$ 是自由度为 19 的卡方随机变量超过 $19 \times 0.025 / 0.0225 = 21.111$ 的概率，即：

$p-\text{value} = P\{\chi^2_{19} > 21.111\} = 1 - \text{pchisq}(21.111, 19) = 0.3307001$

因此，我们必须得出结论：观察到的 $S^2 = 0.025$ 的值不足以排除 $\sigma^2 \leq 0.0225$ 的可能性，因此接受原假设。$\blacksquare$
:::

### 检验两个正态分布的方差是否相等 {#sec-8_5_1}
设 $X_1, \dots, X_n$ 和 $Y_1, \dots, Y_m$ 表示来自两个正态分布总体的独立样本，这两个总体的参数分别为 $(\mu_x, \sigma_x^2)$ 和 $(\mu_y, \sigma_y^2)$，我们考虑检验如下的假设：

$H_0: \sigma_x^2 = \sigma_y^2 \quad vs \quad H_1: \sigma_x^2 \neq \sigma_y^2$

如果我们令：

$\begin{align} S_x^2 &= \frac{1}{n-1} \sum_{i=1}^{n} (X_i - \overline{X})^2 \\ S_y^2 &= \frac{1}{m-1} \sum_{i=1}^{m} (Y_i - \overline{Y})^2 \end{align}$

表示样本方差，那么如 @thm-6_5_1 所示，$(n-1)S_x^2/\sigma_x^2$ 和 $(m-1)S_y^2/\sigma_y^2$ 服从自由度分别为 $n-1$ 和 $m-1$ 的卡方分布，因此 $(S_x^2/\sigma_x^2) / (S_y^2/\sigma_y^2)$ 服从自由度为 $n-1$ 和 $m-1$ 的 $F-\text{分布}$。所以，当 $H_0$ 为真时：

$S_x^2/S_y^2 \sim F_{n-1, m-1}$

所以：

$P_{H_0}\{F_{1 - \alpha / 2, n-1, m-1} \leq S_x^2/S_y^2 \leq F_{\alpha / 2, n-1, m-1}\} = 1 - \alpha$

因此，在显著性水平 $\alpha$ 下，$H_0 \ vs \ H_1$ 的检验为：

$$
\begin{align}
\text{接受} H_0&, \quad \text{如果} F_{1-\alpha/2, n-1, m-1} < \frac{S_x^2}{S_y^2} < F_{\alpha/2, n-1, m-1}  \\
\text{拒绝} H_0&, \quad \text{否则}
\end{align}
$$

上述检验可以通过：

1. 首先，确定检验统计量 $\frac{S_x^2}{S_y^2}$ 的值——记为 $v$
2. 然后，计算 $P\{F_{n-1, m-1} \leq v\}$，其中 $F_{n-1, m-1}$ 是自由度为 $n-1$ 和 $m-1$ 的 $F-\text{分布}$ 随机变量
3. 如果此概率小于 $\alpha/2$（当 $S_x^2$ 显著小于 $S_y^2$ 时）或大于 $1-\alpha/2$（当 $S_x^2$ 显著大于 $S_y^2$ 时），则拒绝原假设。

换句话说，检验数据的 $p-\text{value}$ 为：

$p-\text{value} = 2 \min \left( P\{F_{n-1, m-1} < v\}, 1 - P\{F_{n-1, m-1} < v\} \right)$

当 $p-\text{value}$ 小于等于 显著性水平 $\alpha$ 时，则拒绝原假设。

::: {#exr-8_5_b}
有两种不同的催化剂可用于加快某化学反应的过程。为了检验：无论使用哪种催化剂化学反应产物的方差都是相同的，我们使用第一种催化剂生产了 10 批产品，使用第二种催化剂生产了 12 批产品。如果结果数据为： $S_1^2 = 0.14$、$S_2^2 = 0.28$，我们能否在 5% 的显著性水平下拒绝方差相等的假设？
:::

::: {#sol-8_5_b}
使用 R 命令 `pf(v, n, m)` 来获得具有参数 $n$ 和 $m$ 的 $F-\text{分布}$ 随机变量小于或等于 $v$ 的概率，我们得到：

$P(F_{9,11} \leq 0.5) = pf(0.5, 9, 11) = 0.1537596$

因此，

$p-\text{value} = 2 \min(0.1537596, 1 - 0.1537596) = 0.3075$

因此，我们不能拒绝方差相等的原假设。$\blacksquare$
:::