## 二项分布的假设检验
二项分布在工程问题中经常遇到。例如，考虑一种产品生产线，该生产线制造的产品可以分为两类——可接受的或有缺陷的。通常会假设生产的每个产品的缺陷概率为 $p$，因此一个具有 $n$ 个产品的样本中的缺陷产品数量将是参数为 $(n, p)$ 的二项分布。现在考虑以下的假设检验：

$H_0 : p \le p_0 \quad vs \quad H_1 : p > p_0$

其中 $p_0$ 是某个指定的值。

如果令 $X$ 表示样本大小为 $n$ 的样本中的缺陷数，那么显然当 $X$ 较大时我们希望拒绝 $H_0$。为了计算在显著性水平 $\alpha$ 下需要多大的 $X$ 才能证明拒绝是合理的，我们关注到：

$P\{X \ge k\} = \sum_{i=k}^{n} P\{X = i\} = \sum_{i=k}^{n} \binom{n}{i} p^i (1 - p)^{n-i}$

现在，很直观（并且可以证明），$P\{X \ge k\}$ 是 $p$ 的递增函数——即，样本中包含至少 $k$ 个缺陷产品的概率随着缺陷概率 $p$ 的增加而增加。使用这一点，我们看到当 $H_0$ 为真时（即 $p \le p_0$），

$P\{X \ge k\} \le \sum_{i=k}^{n} \binom{n}{i} p_0^i (1 - p_0)^{n-i}$

因此，显著性水平 $\alpha$ 下的假设检验

$H_0 : p \le p_0 \quad vs \quad H_1 : p > p_0$ 

是当 $X \ge k^*$ 时拒绝 $H_0$，其中 $k^*$ 是使 $\sum_{i=k}^{n} \binom{n}{i} p_0^i (1 - p_0)^{n-i} \le \alpha$ 成立的最小的 $k$ 值。也就是说，

$k^* = \min \left\{ k : \sum_{i=k}^{n} \binom{n}{i} p_0^i (1 - p_0)^{n-i} \le \alpha \right\}$

可以通过首先确定检验统计量的值——例如 $X = x$，然后再计算给定的 $p$-值 来执行假设检验。

$$
\begin{align}
p-\text{value} &= P\{B(n, p_0) \ge x\} \\
&= \sum_{i=x}^{n}{\left(\begin{array}{cc}  n \\ i  \end{array}\right)p_0^i(1-p_0)^{n-i}}
\end{align}
$$

::: {#exr-8_6_a}
一家电脑芯片制造商声称他们出售的芯片的缺陷率不超过 2%。一家电子公司对这家芯片公司的声明印象深刻，并购买了该芯片公司生产的大量芯片。为了确定芯片制造商的声明的可信性，该电子公司决定测试 300 个芯片样本。如果最终发现这 300 个芯片中有 10 个是有缺陷的，那么是否应该拒绝芯片制造商的声明？
:::

::: {#sol-8_6_a}
让我们在 5% 的显著性水平上检测制造商的声明。为了判断是否需要拒绝制造商 2% 缺陷率的声明，我们需要计算当 $p$ 等于 0.02 时，300 个样本中出现 10 个或更多个缺陷产品的概率。也就是说，我们需要计算 $p-\text{value}$。如果 $p-\text{value}$ 小于或等于 0.05，那么就应该拒绝制造商 2% 缺陷率的声明。

$$
\begin{align}
P_{0.02}\{X \ge 10\} &= 1 - P_{0.02}\{X \le 9\} \\
&= 1 - pbinom(9, 300, 0.02) \\
&= 0.08183807
\end{align}
$$

因此，在显著性水平为 0.05 时，我们不能拒绝芯片制造商的声明。

::: {.callout-note}
当然，在 R 中，我们可以使用 `binom.test()` 来直接根据实验结果计算二项分布的 $p-\text{value}$。

```{r}
binom.test(10, 300, 0.02, "greater")
```
:::

$\blacksquare$
:::

::: {#exr-8_6_b}
为了证明编辑 A 优于编辑 B，给两位编辑提供了一份相同的稿件。如果编辑 A 发现了 28 个错误，而编辑 B 发现了 18 个错误，其中有 10 个错误两人都发现了，我们能否得出编辑 A 更优秀的结论？
:::

::: {#sol-8_6_b}
需要注意的是，A 发现了 B 未发现的 18 个错误，B 发现了 A 未发现的 8 个错误。因此，仅由一人发现的错误总数为 26 个。如果 A 和 B 的能力相当，那么他们单独发现某个错误的概率是相等的，即为 1/2。因此，为了证明 A 是更好的编辑，26 次试验中 18 次成功的结果必须足够强大以拒绝以下假设：

$H_0: p \leq 1/2 \quad vs \quad H_1: p > 1/2$

其中，$p$ 是伯努利试验成功的概率。对于实验数据的 $p-\text{value}$ 为：

$p-\text{value} = P\{B(26, 0.5) \geq 18\} = 0.03776$

因此，在 5% 的显著性水平下，我们将拒绝原假设，所以可以得出结论：在 5% 的显著性水平下，A 是更优秀的编辑。
$\blacksquare$
:::

当样本量 $n$ 较大时，我们可以通过使用正态分布逼近二项分布来推导显著性水平为 $\alpha$ 的 $H_0: p \leq p_0 \quad vs \quad H_1: p > p_0$ 的近似检验。其原理如下：因为当 $n$ 较大时，随机变量 $X$ 将近似服从均值为

$E[X] = np$

方差为

$\text{Var}(X) = np(1-p)$

的正态分布，因此

$\frac{X - np}{\sqrt{np(1-p)}}$

将近似服从标准正态分布。因此，显著性水平为 $\alpha$ 的近似检验为：

$\text{拒绝} H_0, \quad \text{如果} \frac{X - np_0}{\sqrt{np_0(1-p_0)}} \geq z_\alpha$

同样的，也可以使用正态分布来近似来计算 $p-\text{value}$。

::: {#exm-8_6_c}
在 @exr-8_6_a 中，$np_0 = 300 \times 0.02 = 6$，且 $\sqrt{np_0(1-p_0)} = \sqrt{5.88}$。因此，由数据 $X = 10$ 得出的 $p-\text{value}$ 为

$\begin{align} p-\text{value} &= P_{0.02}\{X \geq 10\} \\ &= P_{0.02}\{X \geq 9.5\} \\ &P_{0.02}\left\{\frac{X - 6}{\sqrt{5.88}} \geq \frac{9.5 - 6}{\sqrt{5.88}}\right\} \\ &\approx P\{Z \geq 1.443\} \\ &= 0.0745 \end{align}$

因此，精确的 $p-\text{value}$ 为 0.0818，正态分布给出的近似 $p-\text{value}$ 为 0.0745。
:::

假设我们现在希望检验 $p$ 等于某个指定值的原假设，即我们希望检验

$H_0: p = p_0 \quad vs \quad H_1: p \neq p_0$

如果一个具有参数 $n$ 和 $p$ 的二项随机变量 $X$ 的观测值等于 $x$，如果 $x$ 的值显著大于或显著小于在 $p = p_0$ 时的预期值，那么显著性水平为 $\alpha$ 的检验将拒绝原假设 $H_0$。更准确地说，当以下任意一项成立时，检验将拒绝 $H_0$：

$P\{B(n, p_0) \geq x\} \leq \alpha/2 \quad \text{或} \quad P\{B(n, p_0) \leq x\} \leq \alpha/2$

换句话说，当 $X = x$ 时的 $p-\text{value}$ 为

$p-\text{value} = 2 \min \left(P\{B(n, p_0) \geq x\}, P\{B(n, p_0) \leq x\}\right)$

### 检验两个伯努利总体的参数是否相同 {#sec-8_6_1}
假设某类型的芯片有两种不同的生产方法，并且假设第一种生产方法生产的芯片的缺陷率为 $p_1$，而第二种生产方法生产的芯片的缺陷率为 $p_2$。为了检验假设 $p_1 = p_2$，我们使用第一种方法生产了 $n_1$ 个芯片作为样本 1，使用第二种方法生产了 $n_2$ 个芯片作为样本 2。

令 $X_1$ 表示样本 1 中的缺陷芯片的数量，$X_2$  表示样本 2 中的缺陷芯片的数量。因此，$X_1$ 和 $X_2$ 是相互独立的二项分布随机变量，其参数分别为 $(n_1, p_1)$ 和 $(n_2, p_2)$。假设 $X_1 + X_2 = k$，那么两个样本总共有 $k$ 个缺陷品。

如果 $H_0$（$p_1 = p_2$）成立，那么 $n_1 + n_2$ 个芯片中的每一个都有相同的概率成为缺陷品。因此 $k$ 个缺陷品的分布与从一个包含  $n_1 + n_2$ 个物品（其中 $n_1$ 是白色物品， $n_2$ 是黑色物品）中随机抽取 $k$ 个样本的分布相同。换句话说，给定总共 $k$ 个缺陷品，当 $H_0$ 成立时，使用第一种方法得到的缺陷品数量的条件分布将具有以下的超几何分布：

$$
P_{H_0}\{X_1 = i | X_1 + X_2 = k\} = \frac{\binom{n_1}{i}\binom{n_2}{k-i}}{\binom{n_1+n_2}{k}}, \quad i = 0, 1, \ldots, k
$$ {#eq-8_6_1}

在检验 $H_0: p_1 = p_2 \quad vs \quad H_1: p_1 \neq p_2$ 时，当使用第一种方法生产的缺陷芯片比例与使用第二种方法生产的缺陷芯片比例差异很大时，似乎可以合理地拒绝原假设。因此，如果总共存在 $k$ 个缺陷品，那么当 $H_0$ 成立时，我们预计 $X_1/n_1$（使用第一种方法生产的缺陷芯片比例）将接近于 $(k - X_1)/n_2$ （使用第二种方法生产的缺陷芯片比例）。当 $X_1$ 非常小或非常大时，$X_1/n_1$ 和 $(k - X_1)/n_2$ 之间的差异会比较大，因此，合理的显著性水平 $\alpha$ 的检验如下所示。

当 $X_1 + X_2 = k$ 时，

$$
\begin{align}
\text{拒绝} H_0 &, \quad \text{如果} P\{X \leq x_1\} \leq \alpha/2 \quad \text{ 或 } \quad P\{X \geq x_1\} \leq \alpha/2 \\
\text{接受} H_0 &, \quad 否则
\end{align}
$$

其中 $X$ 是具有以下概率质量函数的超几何随机变量：

$$
P\{X = i\} = \frac{\binom{n_1}{i}\binom{n_2}{k-i}}{\binom{n_1+n_2}{k}}, \quad i = 0, 1, \ldots, k
$$ {#eq-8_6_2}

$$
p-\text{value} = 2 \min(P\{X \leq x_1\}, P\{X \geq x_1\})
$$ {#eq-8_6_3}

换句话说，如果显著性水平至少为 $\alpha$ 大于等于 $p-\text{value}$，我们将拒绝原假设。这种检验也称之为 Fisher-Irwin 检验。

可以通过使用 R 命令 `phyper(x, n, m, k)` 来计算 @eq-8_6_3 的概率，该命令用于计算超几何随机变量的概率，其参数 $n, m, k$ 代表从一个包含 $n$ 个红球和 $m$ 个蓝球的盒子中随机抽取 $k$ 个球时，抽取的红球数量小于或等于 $x$ 的概率。