## 引言 {#sec-2_1}
本章将介绍 **描述统计** 的相关内容，在介绍 **描述统计** 的过程中，我们将学习如何描述和总结数据。

@sec-2_2 会讨论如何描述数据集。如果一个数据集中的数据差异相对较小，@sec-2_2_1 和 @sec-2_2_2 介绍了如何使用 **频率表**（*frequency tables*）来描述这样的数据集，@sec-2_2_3 则介绍如何将这样的数据集分组到不同的间隔。

@sec-2_3 讨论了如何使用统计指标来总结数据集，统计指标往往是由数据集确定的量化数值。@sec-2_3_1 介绍了用于描述数据集中心（*center*）的三个统计指标：样本均值（*sample mean*）、样本中位数（*sample median*）和样本众数（*sample mode*）。@sec-2_3_2 会介绍样本方差（*sample variance*）及样本标准差（*sample standard deviation*）。样本均值、样本中位数、样本众数、样本方差和标准差这些统计数据用于描述数据集中数值的分布。@sec-2_3_3 会介绍样本的百分位数（*sample percentiles*），样本百分位数这个统计指标可以告诉我们数据集中哪个值大于所有数据的 95%。

@sec-2_4 节介绍了数据样本集中的切比雪夫不等式（*Chebyshev’s inequality*），切比雪夫不等式给出了与样本均值相差超过 $k$ 倍样本标准差的数据比例的上限。虽然切比雪夫不等式适用于所有数据集，但在某些情况下（例如 @sec-2_5 中讨论的正态分布数据集），我们可以获得更精准的数据比例。

在 @sec-2_5 中，我们注意到，当数据分布符合钟形（*bell-shaped*）时，我们认为该数据集是近似正态的，此时，位于样本均值 $k$ 个样本标准差内的数据比例可以根据所谓的经验法则（*empirical rule*）给出更精确的估计。

@sec-2_6 中关注的是成对数据（*paired data*），并介绍了如何使用散点图（*scatter diagram*）来描述成对数据以及样本相关系数（*sample correlation coefficient*）。样本相关系数是一个统计量，该值表示成对数据中第一个值与第二个值之间相关联的程度。

@sec-2_7 介绍了国民收入分配，洛伦兹曲线（*Lorenz curve*）（ L(p)）和基尼系数（*Gini index*）。洛伦兹曲线给出了收入较低的百分之 $p$ 的居民收入占总收入的比例，基尼系数则是用于衡量收入分配不平等程度的指标。

@sec-2_8 介绍了如何使用 R 来分析数据集。