## 习题 {.unnumbered}
1. 以下是 1997 年 6 月，旧金山湾区每加仑标准无铅汽油的价格的样本数据。

    ```{.bash}
    3.88, 3.90, 3.93, 3.90, 3.93, 3.96, 3.88, 3.94, 3.96, 3.88, 3.94, 3.99, 3.98
    ```

    使用如下的方式对数据进行描述：

    * 频率表
    * 相对频率的线图

2. 解释一下如何构建一个饼图。如果数据集中的某个数据值的相对频率为 r，那么在饼图中，该扇区将会位于什么角度？

3. 以下是西半球四个地区的石油储量估计数据（以十亿桶为单位）：

   * United States  38.7 
   * South America  22.6 
   * Canada         8.8 
   * Mexico         60.0

   请使用饼图来描述如上的数据。

4. 选择一本书或一篇文章，计算前 100 个句子中每个句子的单词数，并使用茎叶图来展现这些数据。现在选择另一本由不同作者撰写的书或文章，并做同样的操作。这两个茎叶图看起来是否相似？你认为这种方法能否有效地判断不同的文章是否由不同的作者所写？

5. 以下是每日上班通勤时间（以分钟为单位）的频率表：

   | Travel time | Frequency |
   |-------------|-----------|
   | 15          | 6         |
   | 18          | 5         |
   | 22          | 4         |
   | 23          | 3         |
   | 24          | 4         |
   | 25          | 2         |
   | 26          | 4         |
   | 32          | 3         |
   | 36          | 1         |
   | 48          | 1         |

   * 频率表中的数据包含了几天的数据？
   * 频率表中的总的通勤时间是多少？

6. @tbl-us_airline 列出了 1985 年至 2006 年间，美国商业航空事故的次数以及由此造成的死亡总人数。

    * 绘制事故数的频率表
    * 绘制事故数的折线图
    * 绘制事故数的累积相对频率图
    * 计算事故数的样本均值
    * 计算事故数的样本中位数
    * 找出事故数的样本众数
    * 计算事故数的样本标准差

```{r}
#| label: tbl-us_airline
#| tbl-cap: "美国商业航空公司 1985~2006 安全数据，数据来源： *National Transportation Safety Board*。"
#| warning: false
#| 
library(knitr)
df <- read.table("../misc/US_airline.csv", header=TRUE, sep=",")
kable(df, align="l")
```

7. 根据 @tbl-us_airline 的数据，

    * 绘制事故导致的死亡人数的直方图
    * 绘制事故导致的死亡人数的茎叶图
    * 计算事故导致的死亡人数的的样本均值
    * 计算事故导致的死亡人数的的样本中位数
    * 计算事故导致的死亡人数的的样本标准差

8. A 镇成年女性的体重样本均值大于 B 镇成年女性的体重样本均值。此外，A 镇成年男性的体重样本均值也大于 B 镇成年男性的体重样本均值。我们是否可以得出结论：A 镇成年人的体重样本均值大于 B 镇成年人的体重样本均值？请给出你的解释。

9. 首位数定律（*Benford’s law for first digits*）指出：在许多现实生活中的数值数据集中，首位数字并不是以相等的比例出现，而是偏向于较小的数字。更具体地说，首位数定律指出，首位非零数字为 $i, i=1,...,9$ 的数据比例大约为 $log_{10}{(i+1)}$。例如，$log_{10}{(2)}=0.301$，这表明大约 30.1% 的数据的首位数字是 1。@tbl-2_9_bl 给出了首位数定律中以 1~9 作为首位数字的数据的比例。

   有趣的是，首位数定律已被证明可以适用于各种现实生活数据集，包括电费账单、街道地址、股票价格、人口数量、死亡率、河流长度、物理和数学常数，并且当数据值广泛分布时似乎最为准确。首位数定律最初是由美国天文学家西蒙・纽科姆（Simon Newcomb）在 1881 年发表的。1938 年，物理学家弗兰克・本福德（Frank Benford）在 20 个不同领域的数据集上测试了首位数定律，并表明在大多数情况下它都是一个很好的拟合。弗兰克・本福德测试的数据包括：河流的表面积、美国城市的人口规模、物理常数和分子量（*molecular weights*）等。

   物理考试中的一个多选题为：以下哪个是 20℃ 下，100% 过氧化氢溶液的密度（单位为 $g/{cm}^3$），(a) 7.3316、(b) 6.2421、(c) 1.4512、(d) 8.1818。如果你对过氧化氢一无所知，你会猜哪个答案是正确的？

    | First digit | Proportion of data having it as first digit |
    |-------------|------------------------------------------|
    | 1           | 0.301                                    |
    | 2           | 0.176                                    |
    | 3           | 0.125                                    |
    | 4           | 0.097                                    |
    | 5           | 0.079                                    |
    | 6           | 0.067                                    |
    | 7           | 0.058                                    |
    | 8           | 0.051                                    |
    | 9           | 0.046                                    |

    : 首位数定律 {#tbl-2_9_bl}
    
10. A 公司总共有 100 名员工，而 B 公司总共有 110 名员工。假设 A 公司的所有员工的薪水总和比 B 公司高。

    * 对于 A 公司工资的中位数与 B 公司工资的中位数来说意味着什么？
    * 对于 A 公司工资的平均数与 B 公司工资的平均数来说意味着什么？

11. 一个包含 198 个数据的数据集中，前 99 个数据的样本均值等于 120，而后 99 个数据的样本均值等于 100。关于整个数据集的样本均值，你能得出什么结论？

    * 关于整个数据集的样本中位数，你能得出什么结论？
    * 关于整个数据集的样本众数，你能得出什么结论？

12. 下表给出了 1922 年英格兰的重大道路交通事故中，按照年龄、性别汇总的行人死亡人数数据。

    * 估算男性年龄的样本均值
    * 估算女性年龄的样本均值
    * 估算死亡男性的四分位数
    * 估算死亡女性的四分位数

    | Age Range | Number of Males | Number of Females |
    |-----------|-----------------|-------------------|
    | 0-5        | 120             | 67                |
    | 5-10       | 184             | 120               |
    | 10-15      | 44              | 22                |
    | 15-20      | 24              | 15                |
    | 20-30      | 23              | 25                |
    | 30-40      | 50              | 22                |
    | 40-50      | 60              | 40                |
    | 50-60      | 102             | 76                |
    | 60-70      | 167             | 104               |
    | 70-80      | 150             | 90                |
    | 80-100     | 49              | 27                |

13. 以下是 12 个相邻位置发现的煤炭样本中的含灰量占比数据：

    ```{.bash}
    9.2, 14.1, 9.8, 12.4, 16.0, 12.6, 22.7, 18.9, 21.0, 14.5, 20.4, 16.9
    ```

    * 计算如上数据的样本均值
    * 计算如上数据的样本标准差

14. 5 个数据的样本均值和样本方差分别是 $\overline{x} = 104$，$s^2 = 16$，如果其中的 3 个数是 102， 100， 105，另外两个数是什么？

15. 假设你得到了美国 50 个州中每个州所有工人的平均工资。

    * 你认为这 50 个州的平均工资的样本均值会等于整个美国的工人平均工资吗？
    * 如果对（a）的回答是否定的，请解释除了这 50 个平均值之外，还需要什么其他信息来确定整个国家的样本平均薪资。同时，解释你将如何使用这些额外信息来计算这个整个美国的工人平均工资。 

16. 如下是 40 个晶体管的使用寿命（单位为小时）：

    ```{.bash}
    112, 121, 126, 108, 141, 104, 136, 134, 
    121, 118, 143, 116, 108, 122, 127, 140,
    113, 117, 126, 130, 134, 120, 131, 133,
    118, 125, 151, 147, 137, 140, 132, 119,
    110, 124, 132, 152, 135, 130, 136, 128
    ```

    * 计算如上数据的样本均值、样本中位数、样本众数
    * 给出如上数据的累积相对频率图

17. 一个实验测量了 50 个粘土样本干燥后的收缩比率，并记录了以下数据：

    ```{.bash}
    18.2 21.2 23.1 18.5 15.6 20.8 19.4 15.4 21.2 13.4 
    16.4 18.7 18.2 19.6 14.3 16.6 24.0 17.6 17.8 20.2 
    17.4 23.6 17.5 20.3 16.6 19.3 18.5 19.3 21.2 13.9 
    20.5 19.0 17.6 22.3 18.4 21.2 20.4 21.4 20.3 20.1 
    19.6 20.6 14.8 19.7 20.5 18.0 20.8 15.8 23.1 17.0
    ```

    * (a) 画出如上数据的茎叶图
    * (b) 计算样本均值，样本中位数，样本众数
    * (c) 计算样本方差
    * (d) 从 13% 开始，以 1% 为间隔将如上的数据进行分组，并绘制直方图
    * (e) 对于分组数据而言，假设每个数据点实际上位于其所在区间的中点，计算样本均值和样本方差，并与 (b) 和 (c) 的结果进行比较。为什么它们会不同？

18. 如下是计算 $\{x_i;\ i=1,...,n\}$ 样本均值和样本方差的一种快速算法。首先计算前 $j(j \ge 2)$ 个数据的样本均值和方差：$\overline{x}_j = \frac{\sum_{i=1}^{j}{x_i}}{j}$，$s_j^2=\frac{\sum_{i=1}^{j}{(x_i - \overline{x})^2}}{j - 1}$。其中，$\overline{x}_1 = x_1$，$s_1^2 = 0$。则：

    $$
    \begin{align}
    & \overline{x}_{j+1} = \overline{x}_j + \frac{x_{j + 1} - \overline{x}}{j + 1} \\
    & s_{j+1}^2 = (1 - \frac{1}{j})s_j^2 + (j + 1)(\overline{x}_{j+1} - \overline{x}_j)^2
    \end{align}
    $$

    * (a) 使用如上的算法计算 `3, 4, 7, 2, 9, 6` 的样本均值和样本方差
    * (b) 使用普通的计算方式来校验 (a) 的结果
    * (c) 验证如上算法中的 $\overline{x}_{j+1}$ 和 $\overline{x}_{j}$ 的关系

19. 对于 @tbl-us_daily_min_temputer 的数据，

    * 计算 1 月的平均气温的 90-分位值
    * 计算 7 月的平均气温的 75-分位值

20. 根据 《纽约时报》在 2013 年 8 月 1 日两周前发布的讣告，找出如下的死亡年龄的四分位数。

    ```{.bash}
    92, 90, 92, 74, 69, 80, 94, 98, 65, 96, 
    84, 69, 86, 91, 88, 74, 97, 85, 88, 68, 
    77, 94, 88, 65, 76, 75, 60, 69, 97, 92, 
    85, 70, 80, 93, 91, 68, 82, 78, 89
    ```

21. 我们按照各个大学在谷歌上的月搜索量对大学进行月度排名，在截止到 2013 年 6 月的 114 个月中，获得过月榜单 TOP 10 的大学的上榜次数如下表所示。

    | University                                           | Number of Months in Top 10 |
    |------------------------------------------------------|----------------------------|
    | Harvard University                                   | 114                        |
    | University of Texas, Austin                          | 114                        |
    | University of Michigan                               | 114                        |
    | Stanford University                                  | 113                        |
    | University of California Los Angeles (UCLA)          | 111                        |
    | University of California Berkeley                    | 97                         |
    | Penn State University                                | 94                         |
    | Massachusetts Institute of Technology (MIT)          | 66                         |
    | University of Southern California (USC)              | 63                         |
    | Ohio State University                                | 52                         |
    | Yale University                                      | 48                         |
    | University of Washington                             | 33                         |

    * 计算样本均值
    * 计算样本方差
    * 计算样本的四分位数

22. 填写缺失的单词或短语以完成以下句子：“如果向一组数字中增加一个新的数字，如果新的数字____，则该数组的样本均值将增加。”

23. 用箱线图表示第 20 题中的数据。

24. 在一个石油化工企业中，在 36 个随机选择的时间点测量了平均颗粒物浓度（单位为 $mg/m^3$），得到了如下的浓度数据：

    ```{.bash}
    5, 18,  15, 7,  23, 220, 130, 85, 103, 25, 
    80, 7,  24, 6,  13, 65,  37,  25, 24,  65, 
    82, 95, 77, 15, 70, 110, 44,  28, 33,  81, 
    29, 14, 45, 92, 17, 53
    ```

    * 使用直方图描述如上数据
    * 如上的直方图是近似正态直方图吗？

25. 一位化学工程师想要研究盐水蒸发池中水的蒸发率，他获得了 4 年中盐水蒸发池 7 月份每天蒸发英寸数的 55 个数据。这些数据以下面的茎叶图给出，其最小数据为 0.02 英寸，最大数据为 0.56 英寸。

    ```{.bash}
    .0    2,6
    .1    1,4
    .2    1,1,1,3,3,4,5,5,5,6,9
    .3    0,0,2,2,2,3,3,3,3,4,4,5,5,5,6,6,7,8,9 
    .4    0,1,2,2,2,3,4,4,4,5,5,5,7,8,8,8,9,9 
    .5    2,5,6
    ```

    计算如上数据的：
    
    * 样本均值
    * 样本中位数
    * 样本标准差
    * 如上的数据看起来符合近似正态分布吗？
    * 位于样本均值 1 个标准差以内的数据占比是多少？

26. 以下是加利福尼亚大学伯克利分校工业工程与运筹学系录取的最近 30 名学生的 GPA（*grade point averages*）。

    ```{.bash}
    3.46, 3.72, 3.95, 3.55, 3.62, 3.80, 3.86, 3.71, 3.56, 3.49, 
    3.96, 3.90, 3.70, 3.61, 3.72, 3.65, 3.48, 3.87, 3.82, 3.91, 
    3.69, 3.67, 3.72, 3.66, 3.79, 3.75, 3.93, 3.74, 3.50, 3.83
    ```

    * (a) 使用茎叶图来绘制如上的数据
    * (b) 计算样本均值 $\overline{x}$
    * (c) 计算样本标准差 $s$
    * (d) 计算位于 $[\overline{x} - 1.5s, \overline{x} + 1.5s]$ 的数据比例，并和切比雪夫不等式给出的下限比例进行对比
    * (e) 计算位于 $[\overline{x} - 2s, \overline{x} + 2s]$ 的数据比例，并和切比雪夫不等式给出的下限比例进行对比

27. 第 26 题中的数据是否近似于正态分布？对于第 26 题的 (d) 和 (e) ，请使用经验法则给出的近似占比与实际占比进行比较。

28. 你是否期望一个健身俱乐部所有会员的体重直方图会近似于正态分布？

29. 对于第 16 题中的数据：

    * (a) 计算样本均值和样本中位数
    * (b) 这些数据符合近似正态分布吗？
    * (c) 计算样本标准差 $s$
    * (d) 计算位于 $[\overline{x} - 1.5s, \overline{x} + 1.5]$ 区间的数据的占比
    * (e) 对比 (d) 的结果和经验法则给出的结果 
    * (f) 对比 (d) 的结果和切比雪夫不等式给出的结果

30. 以下是 12 名考试成绩大致相同的法学院学生的身高和起薪数据：

    | Height (inches) | Salary |
    |-----------------|--------|
    | 64              | 91     |
    | 65              | 94     |
    | 66              | 88     |
    | 67              | 103    |
    | 69              | 77     |
    | 70              | 96     |
    | 72              | 105    |
    | 72              | 88     |
    | 74              | 122    |
    | 74              | 102    |
    | 75              | 90     |
    | 76              | 114    |

    * 绘制数据的散点图
    * 计算样本相关系数

31. 根据人们的站立姿势数据形成一个随机样本。针对样本中的人，还额外记录了每个人在过去一年中经历背痛的天数。令研究人员惊讶的是，这些数据表明良好的站姿与背痛天数之间存在正相关关系。这是否意味着良好的站姿会导致背痛？

32. 如果我们把美国 50 个州中每个州的居民平均收入和居住在该州的外国出生的移民数量绘制为成对的数据图，那么这些成对数据将呈现正相关关系。我们能否得出结论，移民居民往往比土生土长的美国人的收入更高？如果不是，还能如何解释这个现象？

33. 随机抽取 12 名高中三年级学生，并要求他们估算自己每周平均学习的小时数。以下的数据给出了估算结果和学生的 GPA。

    | Hours | GPA |
    |-------|-----|
    | 6     | 2.8 |
    | 14    | 3.2 |
    | 3     | 3.1 |
    | 22    | 3.6 |
    | 9     | 3.0 |
    | 11    | 3.3 |
    | 12    | 3.4 |
    | 5     | 2.7 |
    | 18    | 3.1 |
    | 24    | 3.8 |
    | 15    | 3.0 |
    | 17    | 3.9 |

    * 计算学习小时数和 GPA 之间的样本相关系数。

34. 验证样本相关系数的特性 3。

35. 验证样本相关系数的特性 4。

36. 在一项针对二至四年级的儿童研究中，研究人员针对每个学生都做了阅读测试。在研究结果数据时，研究人员注意到学生的阅读测试分数和身高之间存在正相关关系。研究人员得出结论，身高较高的孩子阅读能力更好，因为他们可以更容易地看到黑板。你认为呢？

37. 最近的一项研究发现，母乳喂养的婴儿与 6 岁时进行的词汇测试分数之间存在正相关关系。讨论在解释这项研究结果时可能遇到的困难。

38. 一个群体的收入分别为 25、32、60、40、38、50，绘制其洛伦茨曲线并计算其基尼系数。

39. 根据如下的年收入（以千美元为单位）频率表，绘制该群体的洛伦茨曲线并计算其基尼系数：

    | Value | Frequency |
    |-------|-----------|
    | 30    | 2         |
    | 50    | 4         |
    | 60    | 5         |
    | 90    | 4         |
    | 100   | 3         |
    | 120   | 2         |

40. 如果样本中所有的数据都乘以一个大于 0 的常数 $c$，基尼系数将会发生什么变化？如果样本中所有的数据都加上一个大于 0 的常数 $c$，基尼系数又会发生什么变化？下降，保持不变，还是不好说？


