## 数据收集和描述统计 {#sec-1_2}

:::{.callout-note title="描述统计"}
**描述统计**（*descriptive statistics*）是统计学的一个重要分支，另一个重要的分支是 @sec-1_3 中介绍的 **推断统计**（*Inferential statistics*）。

**描述统计** 主要关注于数据的收集、处理、汇总、图表描述、概括与分析，包括统计数据的收集方法、数据的加工处理方法、数据的显示方法、数据的分布特征与分析方法等。**描述统计** 的目的是将数据转化为有意义的信息，并帮助我们理解数据的特征和规律。常见的 **描述统计** 包括直方图、平均数、中位数、众数等。

**推断统计** 主要关注如何利用样本数据来推断总体特征，包括参数估计（例如平均数、标准差的估计）和假设检验两种类型。**推断统计** 允许我们根据部分数据来推断总体特征，从而提高研究的效率和准确性。常用的 **推断统计** 包括置信区间、t 检验、方差分析等。

**描述统计** 是统计学的基础，其主要处理样本数据；而 **推断统计** 则是描述统计的升华，其利用样本数据来推测总体特征。
:::

有时候，我们会从一个给定的数据集合为起点来启动统计分析：例如，政府会定期收集和公布相关年份的降水量、地震发生次数、失业率、国内生产总值以及通货膨胀率。我们可以使用 **统计学** 来描述、总结并分析如上的数据。

在有些场景下，我们可能还没有可用于分析的数据，此时需要利用统计理论来设计合适的实验以生成分析所需的数据。实验方案的选择取决于我们如何使用这些数据。

``` {.bash filename="教学方式的实验"}
对于计算机编程课而言，假设一名老师想要确定哪种教学方法对初学者更好。

为了研究这个问题，该老师可以把学生分成两组，然后针对不同组的学生采用不同的教学方法。在课程结束时，对学生的学习效果进行测试，并比较不同分组的学生成绩。如果其中一组学生的成绩明显高于另一组，那么我们假定该组使用的教学方法更优越的想法就更为合理。
```


然而，为了从数据中得出有效的结论，对学生进行分组的方式至关重要，分组时应确保两组学生的编程资质是一致的。这一点，我们我们需要特别关注。我们不应该将男生分为一组，而把女生分为另一组。如果按照性别分组，即使女生组的测试成绩明显高于男生组，我们也无法确定成绩差异是源自教学方法的不同，还是因为女性在学习编程技能方面可能更具天赋。为了避免这个陷阱，我们可以 **随机** 把学生分成两组。**“随机”** 这个词意味着分组的方式应确保每个学生有同等的机会被分配到不同的组。

在实验的最后，我们应该对数据进行描述（例如，两个分组的测试成绩）。此外，我们还应呈现数据的汇总指标（例如，不同分组的平均成绩）。在 **统计学** 中，涉及数据描述和数据汇总的部分称之为 **描述统计**。