## 总体与样本 {#sec-1_4}

在 **统计学** 中，我们对获取研究对象中的所有个体的集合的信息感兴趣。研究对象中所有个体的集合我们称之为 **总体**。**总体** 的规模往往太大，所以我们无法检查 **总体** 中的每个成员。例如，我们可能有某个州的所有居民数据，或者某个制造商去年生产的所有电视机数据，亦或者某个社区的所有家庭数据。在这些情况下，我们试图通过选择总体元素的一个子分组并对该子分组进行检查来了解 **总体**，这个子分组我们称其为 **样本**。

如果 **样本** 需要提供有关 **总体** 的信息，那么，在某种意义上而言，**样本** 必须具有代表性。

``` {.bash filename="市民的平均年龄"}
假设我们对某市居民的年龄分布感兴趣，并且我们获得了进入城镇图书馆（town library）的前 100 个市民的年龄。如果这 100 人的平均年龄为 46.2 岁，我们是否可以依次为依据得出结论：该市居民的平均年龄为 46.2 岁？
```

可能并非如此。当然，我们可以认为，在这种情况下选择的 **样本** 可能并不能代表 **总体**，因为通常而言，年轻学生和老年市民去图书馆的可能性要大于上班族。

::: {.callout-note title="town library"}
在美国，"town library" 是指位于城镇内的公共图书馆。这些图书馆由城镇或地方政府资助，为当地社区提供各种书籍、资料和服务。城镇图书馆通常提供免费的借阅服务，包括书籍、期刊、报纸、音像资料等，并提供学习空间、研究帮助、电脑和互联网接入等资源。它们也可能举办各种活动和课程，以满足社区居民的教育、文化和娱乐需求。
:::

在某些情况下，我们得到了一个 **样本**，然后我们必须判断该 **样本** 是否能够代表 **总体**，例如如上的市民平均年龄的示例。在实践中，如果样本不是以“随机“的方式进行选择，那么通常不能假定给定的 **样本** 可以代表 **总体**。任何特定的、非随机的抽样规则往往会导致 **样本** 对某些数据存在固有的偏好，这也意味着会天然的反对另外的数据。

因此，对于待选择的个体而言，在没有任何先验知识的情况下，通过完全”随机“的方式来选择 **样本**，我们更有可能获得有代表性的 **样本**。尽管这听起来可能有些矛盾，但这确实如此。换句话说，我们不需要刻意选择样本，以便 **样本** 中的人的性别比例和职业比例与 **总体** 是一致的。相反，我们应该把 **样本** 的特性留给 “可能性” 或者 ”概率“，以获得大致正确的百分比。一旦选好了随机样本，我们就可以通过研究 **样本** 并使用 **统计推断** 来得出和 **总体** 有关的结论。