## 统计学简史

在文艺复兴时期，意大利的威尼斯和佛罗伦萨开始对人口和经济方面的数据进行系统化的收集。**统计学**（*statistics*） 一词来源于国家（*state*）这个单词，通常用来描述和国家有关的数据收集。这种收集数据的想法不断从意大利传播到西欧的其他国家。事实上，在 16 世纪上半叶，欧洲国家的政府普遍要求教区居民登记出生、婚姻和死亡情况。由于公共卫生条件差，政府尤其关注居民登记的死亡信息统计。

::: {.callout-note title="statistics 一词的来源"}
在 [Statistics, History of](https://doi.org/10.1007/978-3-642-04898-2_639) 这篇论文中，作者提到了 statistics 一词的来源。

> It is widely believed that the term statistics originated from the Latin Status (situation, condition) of population and economics; in late Latin, the same term meant State. Another root of the term comes from the Italian word stato (state), and a statista (a person who deals with affairs of state). 
> 
> According to Kendall (1960:447) the first use of the word statistics “occurs in a work by an Italian historian Girolamo Ghilini, who in 1589 refers to an account of civile, politica, statistica e militare scienza.” 
:::

19 世纪之前，欧洲的高死亡率主要源自流行病、战争和饥荒。对于流行病而言，最严重的是瘟疫。从 1348 年的黑死病开始，瘟疫在近 400 年的时间里频繁在欧洲发生。1562 年，为了让英国的王室成员意识到需要搬迁到乡下，伦敦市开始每周公布死亡人数。最初，这些死亡人数的清单中会列出死亡地点以及是否因瘟疫而死亡。从 1625 年开始，该清单中的信息扩展到所有的死亡原因。

1662 年，英国商人 John Graunt 出版了一本名为 *Natural and Political Observations Made upon the Bills of Mortality* 的书。@tbl-death_england 摘录了该书中所列出的英格兰五个不同瘟疫年份的总死亡人数和因瘟疫死亡的人数。

| 年份 | 死亡人数 | 瘟疫致死人数 | 
| --- | --- | --- |
| 1592 | 25,886 | 11,503 |
| 1593 | 17,844 | 10,662 |
| 1603 | 37,294 | 30,561 |
| 1625 | 51,758 | 35,417 |
| 1636 | 23,359 | 10,400 |

: 不同年份的英格兰死亡人数表 {#tbl-death_england}

Graunt 利用伦敦的死亡人数来估算该市的人口总数。例如，为了估算 1660 年伦敦的人口，Graunt 对伦敦某些教区 (或社区) 家庭进行了调查，并发现平均每 88 人中大约有 3 人死亡。这意味着平均每 88/3 个人就会有 1 个人死亡。伦敦的死亡人数清单显示 1660 年伦敦有 13200 人死亡，所以 Graunt 估计当年伦敦的人口大约为：

$$
13200 × 88/3 = 387200
$$

Graunt 利用这种估计方法来预测整个英格兰的人口数量。他在书中指出，政府会对这些数据感兴趣，因为这些数据可以作为应征入伍人数和应纳税人数的指标。

Graunt 还利用伦敦的死亡人数清单，以及关于何种疾病会导致何人、在什么年龄死亡的一些合理猜测，来推断死亡年龄。(回想一下，前面提到的死亡人数清单只列出了死亡原因和地点，其并没有列出死者的年龄。) 然后，格兰特利用这些信息计算出不同年龄段的死亡人口比例。@tbl-mortality_jg 是 Graunt 计算的死亡率表之一。例如，@tbl-mortality_jg 指出，在 100 名新生儿中，有 36 人将在 6 岁之前死亡，24 人将在 6~15 岁之间死亡，……

| 死亡年龄 | 每 100 新生儿中的死亡人数 |
| --- | --- | 
| 0-6 | 36 |
| 6-16 | 24 |
| 16-26 | 15 |
| 26-36 | 9 |
| 36-46 | 6 |
| 46-56 | 4 |
| 56-66 | 3 |
| 66-76 | 2 |
| >=76 | 1 |

: John Graunt 的死亡率表 {#tbl-mortality_jg}

从事 **年金** 行业的人对 Graunt 的死亡年龄表非常感兴趣。**年金** 与人寿保险不同，人们会一次性支付一笔款项作为投资，然后在有生之年定期从 **年金** 中获得收益。

::: {.callout-note title="年金"}
年金（*annuity*）是一种金融产品，通常由保险公司或金融机构提供。年金是一种长期投资工具，旨在为购买者提供一定期间内的收入。购买者通常向保险公司或金融机构支付一笔或多笔资金，而作为回报，购买者将在未来的一段时间内获得一定的收益。
:::

受到 Graunt 死亡率表的启发，1693 年，Edmund Halley 又做了更进一步的工作。Halley 是哈雷彗星的发现者（同时，Halley 也是对《自然哲学的数学原理》一书的出版贡献最大的人，他不但鼓励牛顿把自己的发现编写成书，更是为该书的出版提供了资金支持），他利用死亡率表来计算任何年龄段的人活到任何特定年龄的概率。Halley 说服了当时的保险公司，让他们相信年度人寿保险保费应该取决于被保险人的年龄。

继 Graunt 和 Halley 之后，从 17 世纪末到 18 世纪，对数据的收集呈现稳步增长的趋势。例如，1667年，巴黎开始收集死亡人数清单；到 1730 年时，在欧洲，记录死亡年龄已成为一件非常普遍的事情。

18 世纪之前，“statistics” 这个词被用作对国家或地区进行描述性分析的科学方法的简称。从 1800 年左右开始，西欧国家和美国政府开始系统地收集和公布类似的人口普查数据，这积累了大量的、可用的人口普查记录和相关的表格数据，这也导致了 “statistics” 一词在含义上发生了变化。19 世纪时，“statistics” 越来越多地与数字联系在一起，到 19 世纪 30 年代，在英国和法国，人们普遍将 “statistics” 一词与社会“数字科学”（*numerical science*）视为同等含义。

贯穿整个 19 世纪，在 Jacob Bernoulli、Karl Friedrich Gauss 和 Pierre Simon Laplace 等数学家的推动下，尽管 **概率论** 已经发展起来，但在研究统计结果方面，**概率论** 几乎没有任何应用。此中的原因在于，当时的大多数社会统计学家都满足于让数据自己说话。特别是，当时的统计学家对个体推断并不感兴趣，他们更关心整个社会。因此，在当时，统计学家并不关心抽样，而是试图获得全部的人口普查数据。因此，在 19 世纪的社会统计学中，通过样本来推断总体概率的事情几乎没有发生过。

直到 19 世纪末，统计学才开始关注如何从数值数据中推断结论。**推断统计** 这一运动始于 Francis Galton 关于 [遗传天才](https://baike.baidu.com/item/%E9%81%97%E4%BC%A0%E7%9A%84%E5%A4%A9%E6%89%8D/55137162) 的分析工作，在这项分析中， Francis Galton 使用了我们现在所说的回归分析和相关性分析（@sec-9）。Francis Galton 的工作极大的推动了 Karl Pearson 为统计学所做的贡献。Karl Pearson 是卡方检验（@sec-11）的发明者，也是由 Francis Galton 于1904 年资助建立的高尔顿实验室的第一任负责人。在高尔顿实验室，Karl Pearson 发起了一个旨在发明一种用统计数据进行推断的新方法的研究项目。Pearson 邀请科学和工业领域的高年级学生到实验室来学习统计方法，然后将对应的方法应用于各自的领域。化学家 W.S. Gosset 是高尔顿实验室最早的访问学者之一，他以 “Student” 的名义出版了自己的研究发现，并以此表达了对皮尔逊的敬意。（有一个比较有名的故事是说，Gosset 害怕他所在的吉尼斯酿酒厂的老板在发现他们的一位化学家正在做统计学研究时会不高兴，因此不敢以自己的名义出版著作）。Gosset 因为他所发明的 t 检验而名声大振（@sec-8）。

20 世纪初，群体生物学（*population biology*）和农业是应用统计学的两个最重要的领域。统计学这这些领域的应用主要源自 Pearson 和他的实验室的其他人的研究，也源自英国科学家 Ronald A. Fisher 在统计学中的显著成就。在如上所介绍的先驱者以及其他研究者（例如， Karl Pearson 的儿子 Egon 和出生于波兰的数理统计学家 Jerzy Neyman 等）的推动下，他们所发明的推理理论已经通用到可以处理广泛的量化问题和实践问题。因此，在 20 世纪初之后的几年里，越来越多的科学家、商人和政界人士开始将统计学视为能够为科学问题和实践问题提供定量解决方案的工具（见 @tbl-statistics_change）。

| 时间 | 定义 |
| --- | --- |
| Quetelet, 1849 | Statistics has then for its object that of presenting a faithful representation of a state at a determined epoch. | 
| Galton, 1889 | Statistics are the only tools by which an opening can be cut through the formidable thicket of difficulties that bars the path of those who pursue the Science of man. | 
| Fisher, 1925 | Statistics may be regarded (i) as the study of populations, (ii) as the study of variation, and (iii) as the study of methods of the reduction of data. | 
| E. Pearson, 1936 | Statistics is a scientific discipline concerned with collection, analysis, and interpretation of data obtained from observation or experiment. The subject has a coherent structure based on the theory of Probability and includes many different procedures which contribute to research and development throughout the whole of Science and Technology. | 
| Weaver, 1952 | Statistics is the name for that science and art which deals with uncertain inferences — which uses numbers to find out something about nature and experience. | 
| Porter, 1986 | Statistics has become known in the 20th century as the mathematical tool for analyzing experimental and observational data. | 
| this book, 2020 | Statistics is the art of learning from data. | 

: Statistics 定义的变化 {#tbl-statistics_change}

如今，统计学的思想无处不在。在每一份报纸和杂志上，**描述统计学** 的特点都有所体现。在公共卫生、医学研究、工程研究、科学研究、市场营销、质量控制、教育、会计、经济、气象预报、投票和调查、体育、保险、赌博以及所有声称是科学的研究领域，**统计推断** 都是不可或缺的。的确，统计学已经深深植根于人类的知识遗产（*intellectual heritage*）之中。

::: {.callout-note title="知识遗产"}
知识遗产（*intellectual heritage*）是指社会所拥有的知识、思想、传统、技能和价值观的集合，这些资源被传承下来并世代相传。知识遗产包括各种形式的人类智慧，如文学作品、艺术品、哲学理论、科学发现、宗教信仰、法律体系、技术创新等。知识遗产不仅仅是一种资产，更是一种社会、文化和历史的遗产，它反映了人类的智慧、经验和创造力，对于塑造社会的认同感、价值观和意识形态具有重要意义。
:::