## 习题 {.unnumbered} 
1. 下周将举行选举，我们试图通过对总体选民进行抽样来预测共和党候选人或民主党候选人谁会获胜。以下哪种抽样方法可能产生有代表性的样本？
    * a. 对参加大学篮球比赛的所有达到投票年龄的人进行民意调查。
    * b. 对去市中心一家高档餐厅用餐的所有达到投票年龄的人进行民意调查。
    * c. 获取一份选民登记名单，随机选择100个名字，并对他们进行提问。
    * d. 使用电视台的电话投票民意调查结果，电视台会要求听众打电话进来并说出他们的选择。
    * e. 从电话簿中选择名字，并给这些人打电话。

2. 在1936年的美国总统竞选中，第 1 题的 (e) 选项使用的方法导致了及其糟糕的预测结果。在那次竞选中，富兰克林·罗斯福以压倒性优势击败了阿尔弗雷德·兰登。该杂志从汽车用户和电话用户名单中抽取选民样本，基于对这些选民的调研，*Literary Digest* 杂志预测兰登会获胜。
    * a. 你认为 *Literary Digest* 杂志的预测为何如此离谱？
    * b. 从 1936 年到现在，有没有什么变化让你相信 *Literary Digest* 杂志使用的方法在今天会更有效？

3. 一位研究人员正试图发现当今美国人死亡时的平均年龄。为了获得数据，研究人员阅读了 30 期的《纽约时报》的讣告专栏，并记录了美国人的死亡年龄。你认为这种方法会得到一个有代表性的样本吗？

4. 为了确定镇上吸烟者的比例，现决定在当地的以下地点之一进行民意调查。这些民意调查地点中，哪一个最有可能得出合理的结果？为什么？
    * a. 台球厅
    * b. 保龄球馆
    * c. 购物中心
    * d. 图书馆

5. 一所大学计划对其近期毕业的学生进行调查，以确定他们的年薪信息。该学校随机选择了 200 名近期要毕业的学生，并向他们发送了和他们目前工作有关的调查问卷。然而，在这 200 人中，只有 86 人返回了问卷。假设这返回的 86 份问卷显示的平均年薪为 75000 美元。
    * a. 该学校认为 75000 美元是所有毕业生平均工资水平的比较好的近似值，这种想法对吗？解释你的回答背后的理由。
    * b. 如果你对 (a) 的回答是否定的，你能想到，在什么条件下，返回的问卷所显示的工资水平将会是一个不错的毕业生平均工资水平的近似值？

6. 一篇文章报道称，对夜间交通事故中丧生的行人所穿衣服的调查显示，约 80% 的受害者穿着深色衣服，20% 的受害者穿着浅色衣服。文章得出的结论是，晚上穿浅色衣服更安全。
    * a. 这个结论合理吗？请解释下你的回答。
    * b. 如果你对 (a) 的回答是否定的，那么在得出最终结论之前，还需要什么其他信息？

7. 如何评判 Graunt 估算伦敦人口的方法？他的方法是有什么隐含的假设？

8. 1658 年，伦敦的死亡率清单记录了 12246 人死亡。假设对伦敦教区的调查显示，该年的人口死亡率大约为 2%，使用 Graunt 的方法来估算 1658 年伦敦的人口总数。

9. 1662 年，当 Graunt 的书出版时，假设你是一名年金销售员。解释一下，你将如何利用 Graunt 给出的关于人们死亡年龄的数据。

10. 基于 Graunt 的死亡率表（@tbl-mortality_jg）：
    * a. 活到 6 岁的人的占比是多少？
    * b. 活到 46 岁的人的占比是多少？
    * c. 死于 6 岁到 36 岁之间的人的占比是多少？