## Introduction {#sec-13_1}

:::{.callout-note title="对过程的解释"}
在质量控制领域，我们将 *process* 译作 *过程*，以强调一系列活动的内在关联性。过程指为了达到某个目标而执行的一系列操作或阶段，这种操作可以是动态的、复杂的，具有系统性和整体性，例如：生产过程、加工过程……
:::

几乎每个工厂在生产产品的 **过程** 中都会存在某些 **随机变异**（*variation*）。也就是说，无论生产 **过程** 控制得多么严格，生产出的产品之间总会存在一些 **差异**（*variation*）。我们称这种 **差异**（*variation*）为 **随机变异**（*chance variation*），并且我们认为这种 **差异**（*variation*）是生产 **过程** 本身所固有的。

然而，在生产 **过程** 中，还存在另一种类型的 **差异**（*variation*），这种 **差异**（*variation*）不是生产 **过程** 本身所固有的，而是由某些 **特定原因**（*assignable cause*）引起的，并且通常这些 **特定原因**（*assignable cause*）会对产品质量产生不利影响。例如，这种 **差异**（*variation*）可能是由机器错误的设置、原材料质量较差、错误的软件、人为错误或其他更多的可能性所导致。当产品表现出的 **差异**（*variation*）仅由 **随机原因**（*chance cause*）而不是 **特定原因**（*assignable cause*）导致时，我们称生产 **过程** 是 **受控**（*in control*）的。

我们需要解决的一个关键问题就是：确定某个生产 **过程** 是 **受控**（*in control*） 的还是 **失控**（*out of control*）的。

我们可以使用 **控制图**（*control charts*）来简化确定一个 **过程** 是 **受控** 还是 **失控**。**控制图** 由两个数字来确定：**上控制限**（*the upper control limits*）和 **下控制限**（*the lower control limits*）。为了使用 **控制图**，我们需要把制造 **过程** 生成的数据分为若干子组，并计算每个子组的统计量（例如，每个子组的平均值和标准差）。当子组的统计量超出 **上下控制限** 时，我们会认为 **过程** 是 **失控** 的。

* 在 @sec-13_2 和 @sec-13_3 节中，我们假设连续生产的产品具有某些可测量的特性，当 **过程**  **受控** 时，产品的这些特性数据的均值和方差是固定的。我们将会介绍如何基于子组平均值（@sec-13_2 节）和子组标准差（@sec-13_3 节）构建控制图。
* 在 @sec-13_4 中，我们假设产品不具有某种可测量特性，此时，我们通过某种 **属性**（*attribute*）将产品分类为“合格”或“不合格”，进而判断产品是否合格。然后我们将展示如何构建 **控制图**（*control charts*）以指示产品质量的变化。
* 在 @sec-13_5 中，我们将考虑具有随机缺陷数量情况下的 **控制图**。
* 最后，在 @sec-13_6 中，我们将讨论更复杂的 **控制图**——不仅单独考虑每个子组的数据值，还会综合考虑其他子组的数据值。这类控制图包括三种不同的类型：**移动平均控制图**（*moving average control chart*）、**指数加权移动平均控制图**（*exponential weighted moving average control chart*）和 **累积和控制图**（*cumulative sum control chart*）。