## 基于平均值构建控制图：$\overline{x}$ 控制图 {#sec-13_2}
假设当 **过程** 处于 **受控** 状态时，连续生产的产品在某个可测特性上的观测数据是独立的、并且服从均值为 $\mu$、方差为 $\sigma^2$ 的正态分布。然而，由于特殊情况，该 **过程** 可能会失控并且生产出的产品在可观测特性上的数据开始具有不同分布。我们希望能够识别出这种失控的情况，以便停止 **过程**、找出问题所在、并加以修复。

令 $X_1, X_2, \dots$ 表示连续生产的产品的可测量特性。为了确定 **过程** 何时失控，我们将数据分成固定大小（记作 $n$）的子组。固定大小 $n$ 的选择必须确保各子组内数据的一致性。例如，可以选择 $n$ 以使得各子组内的所有产品都是在同一天、同一批次或同一设置下所生产的。换句话说，$n$ 的具体值的选择，需要使得数据分布的变化更可能的发生在子组之间，而不是子组内部。$n$ 的典型的取值为 4、5 或 6。

令 $\overline{X}_i, i = 1,2,...$ 表示第 $i$ 个子组的平均值，即

$$
\begin{aligned}
\overline{X}_1 &= \frac{X_1 + \cdots + X_n}{n} \\
\overline{X}_2 &= \frac{X_{n+1} + \cdots + X_{2n}}{n}\\
\overline{X}_3 &= \frac{X_{2n+1} + \cdots + X_{3n}}{n} \\
\qquad \qquad & \qquad\vdots 
\end{aligned}
$$

当 **过程** 受控时，每个 $X_i$ 的均值为 $\mu$ 且方差为 $\sigma^2$，因此可得：

$$
\begin{aligned}
E(\overline{X}_i) &= \mu \\
\text{Var}(\overline{X}_i) &= \frac{\sigma^2}{n}
\end{aligned}
$$

因此

$$
\frac{\overline{X}_i - \mu}{\sqrt{\sigma^2 / n}} \sim \mathcal{N}(0, 1)
$$

也就是说，**过程** 连续生产的产品中，如果第 $i$ 个子组中的产品始终处于受控状态，那么随机变量 $\sqrt{n} \frac{\overline{X}_i - \mu}{\sigma}$ 服从标准正态分布。因此，标准正态随机变量 $Z$ 几乎总是位于 $-3$ 和 $+3$ 之间。（实际上，$P\{-3 < Z < 3\} = 0.9973$。）因此，如果 **过程** 在连续生产的产品中，第 $i$ 个子组的产品始终处于受控状态，那么我们一定可以期望得到：

$$
-3 < \sqrt{n} \frac{\overline{X}_i - \mu}{\sigma} < 3
$$

即，

$$
\mu - \frac{3\sigma}{\sqrt{n}} < \overline{X}_i < \mu + \frac{3\sigma}{\sqrt{n}}
$$

我们称

$$
\begin{aligned}
\text{UCL} &\equiv \mu + \frac{3\sigma}{\sqrt{n}} \\
\text{LCL} &\equiv \mu - \frac{3\sigma}{\sqrt{n}}
\end{aligned}
$$

分别为 **上控制限**（*upper control limits*）和 **下控制限**（*lower control limit*）。

$\overline{X}$ 控制图的作用是检测产品的平均值是否发生变化，其方法是绘制连续子组的平均值 $\overline{X}_i$，并在 $\overline{X}_i$ 第一次落在 $\text{LCL}$ 和 $\text{UCL}$ 之外时，判断 **过程** 已经失控（见 @fig-13_1）。

::: {#exr-13_2_a}
某厂商生产的钢轴直径应服从均值为 3mm、标准差为 0.1mm 的正态分布。连续抽取钢轴样本、并且以 4 个钢轴为一组得到 10 个子组的样本均值（单位：mm）数据如下：

|样本编号|$\overline{X}$|
|---|---|---|
|1|	3.01|	
|2|	2.97|	
|3|	3.12|	
|4|	2.99|	
|5|	3.03|	
|6|	3.02|
|7|	3.10|
|8|	3.14|
|9|	3.09|
|10| 3.20|

根据如上的数据，我们应得出什么结论？
:::

::: {#sol-13_2_a}
当 **过程** 处于受控状态时，连续生产的钢轴直径服从均值 $\mu = 3$、标准差 $\sigma = 0.1$ 的正态分布。因此，当 $n = 4$ 时：

$$
\begin{aligned}
\text{LCL} &= 3 - \frac{3(0.1)}{\sqrt{4}} = 2.85 \\
\text{UCL} &= 3 + \frac{3(0.1)}{\sqrt{4}} = 3.15
\end{aligned}
$$

由于第 10 子组的样本平均值大于 **上控制限**（*UCL*），因此可以怀疑钢轴的平均直径已经不再是 3mm。（显然，从第 6 到第 10 子组样本的结果来看，其平均直径看起来已经超过了 3mm。）
:::

```{r}
#| label: fig-13_1
#| fig-cap: $\overline{X}$ 的控制图，其中 $n = 4$
#| warning: false
#| 

library(ggplot2)

x <- c(3.01, 2.97, 3.12, 2.99, 3.03, 3.02, 3.10, 3.14, 3.09, 3.20)
i <- seq_along(x)
df <- data.frame(i=i, x=x)

mu <- 3       # 均值
sigma <- 0.1  # 标准差
n <- 4        # 子组样本量
UCL <- mu + 3 * sigma / sqrt(n)  # 上控制限
LCL <- mu - 3 * sigma / sqrt(n)  # 下控制限

ggplot(df, aes(x = i, y = x)) +
  geom_point(shape = 4, size = 2) +  # 绘制均值点
  #geom_line(aes(group = 1), color = "black") +  # 连接均值点的线
  geom_hline(yintercept = UCL, color = "blue", linetype = "dashed", size = 1) +  # 上控制限
  geom_hline(yintercept = LCL, color = "blue", linetype = "dashed", size = 1) +  # 下控制限
  geom_hline(yintercept = mu, color = "gray", linetype = "dotted", size = 1) +  # 中心线
  annotate("text", x = 11, y = UCL, label = "UCL", hjust = 0, vjust = -0.5, color = "blue") +  # 标注UCL
  annotate("text", x = 11, y = LCL, label = "LCL", hjust = 0, vjust = 1.5, color = "blue") +  # 标注LCL
  annotate("text", x = 10, y = x[10], label = "Out of control", hjust = -0.2, vjust = -0.5, color = "black") +  # 标注失控点
  geom_point(data=df[10, ], aes(x = i, y = x), color = "red", shape = 4, size = 4) +  # 突出显示失控点
  labs(title = "Control Chart", x = "Subgroup", y = expression(bar(X))) +  # 添加标题和轴标签
  scale_x_continuous(limits = c(1, 12),
                     breaks = seq(1, 10, by = 1)) + 
  theme_minimal()  # 使用简洁主题
```

:::{.callout-tip title="备注"}
* 在如上的控制图中，我们假定当 **过程** 处于受控状态时，数据分布服从正态分布。然而，根据中心极限定理（@sec-6_3），即使数据分布不服从正态分布，各子组均值的分布也应大致服从正态分布。因此，各子组均值也不太可能偏离其平均值 的 3 个标准差。

* 通常情况下，我们并不能确定所有生产产品的可测量质量，因此只能通过随机选择的产品来确定 **过程** 的质量。因此，我们自然的会选择同时生产的产品作为一个子组。

需要注意的是，即使 **过程** 处于受控状态，子组均值也有概率位于控制界限之外，以 @exr-13_2_a 的数据为例，位于控制界限之外的概率是 0.0027。因此，我们可能会错误地停止 **过程** 并去寻找那些本来就不存在的问题源。

假设 **过程** 刚刚失控，并且测量数据的均值从 $\mu$  变为 $\mu + a$，其中 $a > 0$。如果之后没有进一步变化，那么需要多长时间才能从控制图上观察到 **过程** 已经失控？为了回答这个问题，子组均值落在控制界限内的条件是：

$-3 < \sqrt{n} \frac{\overline{X} - \mu}{\sigma} < 3$

即，

$-3 - \frac{a \sqrt{n}}{\sigma} < \sqrt{n} \frac{\overline{X} - \mu}{\sigma} - \frac{a\sqrt{n}}{\sigma} < 3 - \frac{a \sqrt{n}}{\sigma}$

所以，

$-3 - \frac{a \sqrt{n}}{\sigma} < \sqrt{n} \frac{\overline{X} - \mu - a}{\sigma} < 3 - \frac{a \sqrt{n}}{\sigma}$

因此，子组均值 $\overline{X}$ 服从均值为 $\mu + a$、方差为 $\sigma^2 / n$ 的正态分布。因此，

$\sqrt{n}\frac{\overline{X} - \mu - a}{\sigma}$ 服从标准正态分布，其落在控制界限内的概率为：

$$
\begin{aligned}
P \left\{ -3 - \frac{a \sqrt{n}}{\sigma} < Z < 3 - \frac{a \sqrt{n}}{\sigma} \right\} &= \Phi \left( 3 - \frac{a \sqrt{n}}{\sigma} \right) - \Phi \left( -3 - \frac{a \sqrt{n}}{\sigma} \right) \\
&\approx \Phi \left( 3 - \frac{a \sqrt{n}}{\sigma} \right) 
\end{aligned}
$$

因此，落在控制界限外的概率约为：

$1 - \Phi \left( 3 - \frac{a \sqrt{n}}{\sigma} \right)$

例如，如果子组大小 $n = 4$，均值增加 $1$ 个标准差，即 $a = \sigma$，那么子组均值落在控制界限之外的概率为：

$1 - \Phi(1) \approx 0.1587$

由于每个子组均值落在控制界限之外都是相互独立的，切其概率为 $1 - \Phi \left( 3 - \frac{a \sqrt{n}}{\sigma} \right)$，因此检测到此变化所需的子组数量服从几何分布，其均值为：

$\left[ 1 - \Phi \left( 3 - \frac{a \sqrt{n}}{\sigma} \right) \right]^{-1}$

在 $n = 4$ 的情况下，如果均值变化为 1 个标准差，为检测均值发生 1 个标准差变化，需要绘制的子组数量服从几何分布，其均值为：

$\frac{1}{0.1587} \approx 6.301$。
:::

### $\mu$、$\sigma$ 未知的场景 {#sec-13_2_1}
如果我们刚开始使用控制图，并且没有可靠的历史数据，那么 $\mu$ 和 $\sigma$ 则都是未知的。此时，我们需要估计 $\mu$ 和 $\sigma$。为此，我们使用 $k$ 个子组，其中 $k$ 应满足 $k \geq 20$  且 $nk \geq 100$。如果 $\overline{X}_i,\ i = 1, \ldots, k$ 是第 $i$ 个子组的平均值，那么可以通过这些子组平均值的均值 $\overline{\overline{X}}$ 来估计 $\mu$，即：

$$
\overline{\overline{X}} = \frac{\overline{X}_1 + \cdots + \overline{X}_k}{k}
$$

为了估计 $\sigma$，令 $S_i$ 表示第 $i$ 个子组的样本标准差，其中 $i = 1, \ldots, k$。即：

$$
\begin{aligned}
S_1 &= \sqrt{\frac{\sum_{i=1}^n (X_i - \overline{X}_1)^2}{n-1}} \\
S_2 &= \sqrt{\frac{\sum_{i=1}^n (X_{n+i} - \overline{X}_2)^2}{n-1}} \\
\quad & \quad \vdots \\
S_k &= \sqrt{\frac{\sum_{i=1}^n (X_{(k-1)n+i} - \overline{X}_k)^2}{n-1}}
\end{aligned}
$$

令：

$$
\overline{S} = \frac{S_1 + \cdots + S_k}{k}
$$

统计量 $\overline{S}$ 并不是 $\sigma$ 的无偏估计，即 $E[\overline{S}] \neq \sigma$。为了将 $\overline{S}$ 转化为无偏估计，我们首先计算 $E[\overline{S}]$：

$$
E[\overline{S}] = \frac{E[S_1] + \cdots + E[S_k]}{k} = E[S_1]
$$ {#eq-13_2_1}

最后一个等式成立是因为 $S_1, \ldots, S_k$ 是独立且同分布的（因此具有相同的均值）。为了计算 $E[S_1]$，我们需要用到 @thm-6_5_1 中的正态分布样本的基本概念，即：

$$
(n-1)\frac{S_1^2}{\sigma^2} = \sum_{i=1}^n \frac{(X_i - \overline{X}_1)^2}{\sigma^2} \sim \chi^2_{n-1}
$$ {#eq-13_2_2}

现在可以证明（参见习题 3）：

$$
E[\sqrt{Y}] = \frac{\sqrt{2}\Gamma(n/2)}{\Gamma(\frac{n-1}{2})}, \quad \text{当} \, Y \sim \chi^2_{n-1}
$$ {#eq-13_2_3}

由于

$$
E\left[\sqrt{(n-1)S^2/\sigma^2}\right] = \sqrt{n-1}E[S_1]/\sigma
$$

根据 @eq-13_2_2 和 @eq-13_2_3，我们可以得出：

$$
E[S_1] = \frac{\sqrt{2}\Gamma(n/2)\sigma}{\sqrt{n-1}\Gamma(\frac{n-1}{2})}
$$

因此，如果定义

$$
c(n) = \frac{\sqrt{2}\Gamma(n/2)}{\sqrt{n-1}\Gamma(\frac{n-1}{2})}
$$

则根据 @eq-13_2_1，可以推导出 $\overline{S}/c(n)$ 是 $\sigma$ 的无偏估计量。

@tbl-13_1 展示了从 $n=2$ 到 $n=10$ 的 $c(n)$ 的值。

|  |  |
|----------|--------------|
| c(2)        | 0.7978849    |
| c(3)        | 0.8862266    |
| c(4)        | 0.9213181    |
| c(5)        | 0.9399851    |
| c(6)        | 0.9515332    |
| c(7)        | 0.9593684    |
| c(8)        | 0.9650309    |
| c(9)        | 0.9693103    |
| c(10)       | 0.9726596    |

: $c(n)$ 的值 {#tbl-13_1}

:::{.callout-tip title="技术说明"}
在计算 @tbl-13_1 中的数值时，$\Gamma(n/2)$ 和 $\Gamma\left(n - \frac{1}{2}\right)$ 的计算基于我们在 @sec-5_7 中已经构建的递归公式：

$$
\Gamma(a) = (a - 1)\Gamma(a - 1)
$$

递归公式表明，对于整数 $n$，有：

$$
\begin{aligned}
\Gamma(n) &= (n - 1)(n - 2) \cdots 3 \cdot 2 \cdot 1 \cdot \Gamma(1) \\
&= (n - 1)! \quad \because \quad \Gamma(1) = \int_{0}^{\infty} e^{-x} \, dx = 1
\end{aligned}
$$

类似的，我们可得到如下的递归公式：

$$
\Gamma\left(\frac{n + 1}{2}\right) = \left(\frac{n - 1}{2}\right)\left(\frac{n - 3}{2}\right)\cdots\frac{3}{2} \cdot \frac{1}{2} \cdot \Gamma\left(\frac{1}{2}\right)
$$

$$
\begin{aligned}
\Gamma\left(\frac{1}{2}\right) &= \int_{0}^{\infty} e^{-x} x^{-1/2} \, dx \\
&= \int_{0}^{\infty} e^{-y^2/2} \frac{\sqrt{2}}{y} \, y \, dy \quad \text{by } x = \frac{y^2}{2}, \, dx = y \, dy \\
&= \sqrt{2} \int_{0}^{\infty} e^{-y^2/2} \, dy \\
&= 2\sqrt{\pi} \cdot \frac{1}{\sqrt{2\pi}} \int_{0}^{\infty} e^{-y^2/2} \, dy \\
&= 2\sqrt{\pi} \cdot P[N(0, 1) > 0] \\
&= \sqrt{\pi}
\end{aligned}
$$
:::

本节所述的对 $\mu$ 和 $\sigma$ 的估计用到了所有的 $k$ 个子组，因此，只有当整个 **过程** 都处于受控状态时才是合理的。为了检验这一点，我们基于 $\mu$ 和 $\sigma$ 的估计值来计算 **控制限**（*the control limits*），即：

$$
\begin{aligned}
\text{LCL} & = \overline{\overline{X}}-\frac{3\overline{S}}{c(n)\sqrt{n}} \\
\text{UCL} & = \overline{\overline{X}}+\frac{3\overline{S}}{c(n)\sqrt{n}}
\end{aligned}
$$ {#eq-13_2_4}

接下来，我们检查每个子组的平均值 $\overline{X}_i$ 是否落在上下控制限之间。我们删除那些平均值未落在控制限内的子组（假设 **过程** 暂时失控），然后重新计算 $\mu$ 和 $\sigma$ 的估计值。然后，我们再次检查所有剩余子组的平均值是否都位于控制限之间。如果还存在子组的的平均值未落在控制限内，删除这些子组，如此反复。当然，如果有过多的子组平均值落在控制限之外，就表明 **过程** 尚未处于受控状态。

::: {#exr-13_2_b}
对于 @exr-13_2_a 而言，假设该 **过程** 刚刚开始，因此均值 $\mu$ 和标准差 $\sigma$ 是未知的。在这种场景下，我们重新来考虑下 @exr-13_2_a。此时，假设样本标准差如下所示：

| |$\overline{X}$| 	 $S$ |	 | $\overline{X}$ |	 $S$|
|---|---|---|---| ---| ---|
| 1 | 3.01 | 0.12 |	6 | 3.02 | 0.08 |
| 2 | 2.97 | 0.14 |	7 | 3.10 | 0.15 |
| 3 | 3.12 | 0.08 |	8 | 3.14 | 0.16 |
| 4 | 2.99 | 0.11 |	9 | 3.09 | 0.13 |
| 5 | 3.03 | 0.09 |	10| 3.20 | 0.16 |

因为 $\overline{\overline{X}} = 3.067$，$\overline{S} = 0.122$，$c(4) = 0.9213$，控制限为：

$\text{LCL} = 3.067 - \frac{3 \times 0.122}{2 \times 0.9213} = 2.868$
$\text{UCL} = 3.067 + \frac{3 \times 0.122}{2 \times 0.9213} = 3.266$

由于所有的 $\overline{X}_i$ 均落在控制限内，因此我们假设该 **过程** 处于控制状态，且均值为 $\mu = 3.067$，标准差为：$\sigma = \frac{\overline{S}}{c(4)} = 0.1324$。

假设该生产线生产的产品的规格应该为 $3 \pm 0.1$。假设该 **过程** 保持处于受控状态，且上述数据是对真实均值和标准差的准确估计，计算满足规格的产品的比例？
:::

::: {#sol-13_2_b}
在 $\mu = 3.067$，$\sigma = 0.1324$ 下，我们有：

$$
\begin{align}
P\{2.9 \leq X \leq 3.1\} &= P\left\{ \frac{2.9 - 3.067}{0.1324} \leq \frac{X - 3.067}{0.1324} \leq \frac{3.1 - 3.067}{0.1324} \right\} \\
&= \Phi(0.2492) - \Phi(-1.2613) \\
&= 0.5984 - 0.1036 \\
&= 0.4948
\end{align}
$$

因此，满足规格要求的产品比例为 49%。$\blacksquare$
:::

:::{.callout-tip title="备注"}
**1.**

估计量 $\overline{\overline{X}}$ 等于所有 $nk$ 个测量值的平均值，因此，显然，$\overline{\overline{X}}$ 是 $\mu$ 的估计量。然而，为什么不直接使用所有 $nk$ 个测量值的样本标准差（如下式所示）作为 $\sigma$ 的初始估计量可能并不直观：

$S \equiv \sqrt{\frac{\sum_{i=1}^{nk} \left( X_i - \overline{\overline{X}} \right)^2}{nk - 1}}$

主要的原因在于：**过程** 在前 $k$ 个子组期间可能并非始终处于受控状态，因此如上式所示的估计量可能与真实值之间相差甚远。此外，一个 **过程** 可能会由于某些突发事件而失控，从而导致均值 $\mu$ 发生变化，而标准差却保持不变。在这种情况下，各子组的样本标准差仍然可以作为 $\sigma$ 的估计量，而 $S$ 却不能。

即使整个 **过程** 看似均处于受控状态，$\sigma$ 的无偏估计量 $\frac{\overline{S}}{c(n)}$ 仍然要优于样本标准差 $S$。这是因为：我们不能确定在此期间均值终没有发生变化。例如，即使所有子组均值都落在控制限内，我们判断该 **过程** 处于受控状态，但这并不能保证不存在某些特定原因导致的差异（这些特定原因导致的差异可能导致均值发生变化，但这些变化尚未在图表中体现出来）。这意味着在实际操作中，即使假设 **过程** 处于受控状态并持续生产产品，我们也需要认识到可能会存在某些特定原因导致的差异。由此认为，$\frac{\overline{S}}{c(n)}$  是一个比样本标准差更“安全”的估计量。换句话说，当 **过程** 始终受控时，$\frac{\overline{S}}{c(n)}$ 的表现可能不如样本标准差好；但如果均值存在些微小变化，$\frac{\overline{S}}{c(n)}$ 的表现会比样本标准差要好很多。

**2.**

以前，我们常使用基于子组极差（*subgroup ranges*）——即子组中最大值与最小值之差来作为 $\sigma$ 的估计量。这种方法的目的主要是简化必要的计算量（显然，计算极差比计算子组的样本标准差要容易得多）。然而，随着现代计算机能力的增强，计算量已经不再是一个需要考虑的限制因素。此外，标准差估计量的方差比极差估计量的方差更小，并且鲁棒性也更好（即使背后的数据分布不是正态分布，标准差估计量仍能提供合理的总体标准差估计）。因此，在本书中，我们不考虑极差估计量。
:::