## 不合格品率控制图 {#sec-13_4}
当测量的数据值是在某个范围内连续变化时，可以使用 $\overline{X}$-控制图和 $S$-控制图判断 **过程** 是否处于受控状态。但有时候，可直接将所生产的产品分类为有缺陷或无缺陷，此时，我们依然可以构建控制图。

假设当 **过程** 处于受控状态时，所生产的每个产品出现缺陷的概率相互独立且为 $p$。令 $X$ 表示大小为 $n$ 的产品子组中缺陷产品的数量，那么在 **过程** 受控的假设下，$X$ 将是一个参数为 $(n, p)$ 的二项随机分布。如果 $F = X / n$ 是子组缺陷产品的比例，那么在 **过程** 受控的假设下，其均值和标准差由以下公式给出：

$E[F]=\frac{E[X]}{n}=\frac{np}{n}=p$

$\sqrt{\text{Var}(F)}=\sqrt{\frac{\text{Var}(X)}{n^2}}=\sqrt{\frac{np(1 - p)}{n^2}}=\sqrt{\frac{p(1 - p)}{n}}$

因此，当 **过程** 处于受控状态时，大小为 $n$ 的子组中缺陷产品的比例很可能在以下范围内：

$\text{LCL}=p - 3\sqrt{\frac{p(1 - p)}{n}}, \quad \text{UCL}=p + 3\sqrt{\frac{p(1 - p)}{n}}$

对于本节的场景，子组大小 $n$ 通常比 $\overline{X}$-控制图和 $S$-控制图中使用的 4~10 的典型值要大得多。选择更大的 $n$ 的主要原因在于：如果 $p$ 很小且 $n$ 的大小不合理，那么即使 **过程** 失控，大多数子组也将没有缺陷产品。因此，与 $np$ 不接近于零的 $n$ 相比，$np$ 接近于零的 $n$ 在检测质量变化时需要花费更长的时间。

当然，要启动这样一个控制图，我们首先必须要估计 $p$。为此，选择 $k$ 个子组，并尽量使 $k\geq20$，同时令 $F_i$ 表示第 $i$ 个子组中缺陷产品的比例。$p$ 的估计值由 $\overline{F}$ 给出，其定义为：

$\overline{F}=\frac{F_1+\cdots + F_k}{k}$ 

由于 $nF_i$ 等于第 $i$ 个子组中的缺陷产品数量，则 $\overline{F}$ 也可以表示为：

$$
\begin{align*}
\overline{F}&=\frac{nF_1+\cdots + nF_k}{nk}\\
&=\frac{\text{所有子组中的缺陷产品总数}}{\text{所有子组中的产品总数}}
\end{align*}
$$

换句话说，$p$ 的估计值就是所检查产品中缺陷产品的比例。此时上控制限和下控制限由以下公式给出：

$\text{LCL}=\overline{F}-3\sqrt{\frac{\overline{F}(1 - \overline{F})}{n}}, \quad \text{UCL}=\overline{F}+3\sqrt{\frac{\overline{F}(1 - \overline{F})}{n}}$

现在，我们就可以检查子组的缺陷比例 $F_1,F_2,\cdots,F_k$ 是否落在如上的控制限内。如果某些子组超出了控制限范围，那么应该剔除相应的子组，并重新计算 $\overline{F}$。

::: {#exm-13_4_a}
对于一台自动螺丝机生产线而言，我们从每小时生产的产品中连续抽取 50 个螺丝作为样本，每个螺丝或者为合格品或者为缺陷品。对 20 个这样的样本进行检测，得到以下数据。

|子组|缺陷产品个数|F|子组|缺陷产品个数|F|
| ---- | ---- | ---- | ---- | ---- | ---- |
|1|6|.12|11|1|.02|
|2|5|.10|12|3|.06|
|3|3|.06|13|2|.04|
|4|0|.00|14|0|.00|
|5|1|.02|15|1|.02|
|6|2|.04|16|1|.02|
|7|1|.02|17|0|.00|
|8|0|.00|18|2|.04|
|9|2|.04|19|1|.02|
|10|1|.02|20|2|.04|

$\overline{F} = \frac{缺陷产品总数}{产品总数} = \frac{34}{1000} = 0.034$

因此，

$$
\begin{align*}
\text{UCL}&= 0.034 + 3\sqrt{\frac{(0.034)(0.968)}{50}}= 0.1109\\
\text{LCL}&= 0.034 - 3\sqrt{\frac{(0.034)(0.966)}{50}}=- 0.0429
\end{align*}
$$

由于第一个子组中的缺陷产品比例超出了上控制限，我们需要剔除该子组并重新计算 $\overline{F}$：

$\overline{F}=\frac{34 - 6}{950}=0.0295$

因此，新的上控制限和下控制限为 $0.0295\pm\sqrt{(0.0295)(1 - 0.0295)/50}$，即

$\text{LCL}=-0.0423, \quad \text{UCL}=0.1013$

由于其余子组的缺陷品比例都落在控制限内，我们可以接受这样的结论：当 **过程** 受控时，子组中的缺陷品比例应低于 $0.1013$。$\blacksquare$
:::

:::{.callout-tip title="备注"}
请注意，即使质量变化可能会意味着质量提升，我们也试图检测到任何质量上的变化。也就是说，即使次品出现的概率降低，我们也将该过程视为“失控”。这样做的原因是，注意到质量上的任何变化（无论是变好还是变差）都很重要，以便能够评估变化的原因。换句话说，如果产品质量出现了提升，那么分析生产过程以确定质量提升的原因就很重要。（也就是说，我们做对了哪些事情？） 
:::