## 缺陷数控制图 {#sec-13_5}
在本节中，我们将考虑由一个或一组产品构成的产品单元中的缺陷产品数量的场景，例如：飞机机翼中有缺陷的铆钉数量，某芯片公司每天生产的有缺陷的计算机芯片数量。本节分析的场景中，通常待检测的产品的数量比较大，并且实际出现缺陷的概率都很小，所以假设由此产生的缺陷数量服从泊松分布是合理的。因此，我们假设，当 **过程** 处于受控状态时，单位缺陷数量（*number of defects per unit*）服从均值为 $\lambda$ 的泊松分布。

如果我们令 $X_i$ 表示第 $i$ 个单元中的缺陷数量，那么，由于泊松随机变量的方差等于其均值，当 **过程** 处于受控状态时：

$E[X_i]=\lambda, \quad \text{Var}(X_i)=\lambda$

因此，当 **过程** 处于受控状态时，$X_i$ 很可能在 $\lambda\pm3\sqrt{\lambda}$ 范围内，所以上控制限和下控制限由以下公式给出：

$\text{UCL}=\lambda + 3\sqrt{\lambda}, \quad \text{LCL}=\lambda - 3\sqrt{\lambda}$

如前所述，当一开始绘制控制图、且 $\lambda$ 未知时，应该使用 $k$ 个单元的样本来估计 $\lambda$：

$\overline{X}=(X_1+\cdots + X_k)/k$

由此我们得到控制限：

$\overline{X}+3\sqrt{\overline{X}} \quad, \quad \overline{X}-3\sqrt{\overline{X}}$

如果所有的 $X_i$（$i = 1,\cdots,k$）都落在控制限内，那么我们就假设 **过程** 处于受控状态，且 $\lambda = \overline{X}$。如果存在 $X_i$ 超出控制限，那么就剔除这些数据并重新计算 $\overline{X}$，依此类推。

在每个产品（或每天）的平均缺陷数较小的情况下，应该将产品（天数）组合起来，并使用给定数量——比如 $n$ 个产品（或 $n$ 天）——的缺陷数作为样本数据。由于独立泊松随机变量的和仍然是均值为 $\lambda$ 的泊松随机变量，因此给定数量的缺陷数据将是一个均值更大的 $\lambda$ 的泊松随机变量。所以，当每个产品的平均缺陷数小于 25 时，这种产品组合的方式是有用的。

为了体会产品组合的优势，假设当 **过程** 处于受控状态时，每个产品的平均缺陷数为 4，并且假设发生了一些情况，导致这个值从 4 变为 6，也就是说，产品缺陷数增加了 1 个标准差。那么，当连续数据由 $n$ 个产品中的缺陷数组成时，平均要生产多少个产品才能判断 **过程** 为失控状态。


由于在受控状态下，$n$ 个产品样本中的缺陷数服从均值和方差都等于 $4n$ 的泊松分布，所以控制限为 $4n\pm3\sqrt{4n}$ ，即 $4n\pm6\sqrt{n}$。现在，如果每个产品的平均缺陷数变为 6，那么将服从均值为 $6n$ 的泊松分布，所以此时样本落在控制限之外的概率（称其为 $p(n)$）由下式给出：

$p(n)=P\{Y > 4n + 6\sqrt{n}\}+P\{Y < 4n - 6\sqrt{n}\}$

其中 $Y$ 服从均值为 $6n$ 的泊松分布。现在

$$
\begin{align*}
p(n) &\approx P\{Y > 4n + 6\sqrt{n}\} \\
&=P\left\{\frac{Y - 6n}{\sqrt{6n}}>\frac{6\sqrt{n}-2n}{\sqrt{6n}}\right\}\\
&\approx P\left\{Z>\frac{6\sqrt{n}-2n}{\sqrt{6n}}\right\}\quad \text{其中 }Z\sim \mathcal{N}(0,1)\\
&=1 - \Phi\left(\sqrt{6}-2\sqrt{\frac{n}{6}}\right)
\end{align*}
$$

因为每个数据值落在控制限之外的概率为 $p(n)$，所以得到一个落在控制限之外的数据值所需的产品数量是一个参数为 $p(n)$ 的几何随机变量，因此其均值为 $1 / p(n)$。最后，由于每个数据值对应 $n$ 个产品，所以在 **过程** 被判定为失控之前生产的物品数量的均值为 $n / p(n)$，所以失控时生产的产品平均数量为：

$$
n/(1 - \Phi(\sqrt{6}-\sqrt{\frac{2n}{3}}))
$$

@tbl-13_2 中给出了不同的 $n$ 所对应的平均产品数量。由于当 **过程** 处于受控状态时，$n$ 的值越大越好（在 **过程** 被错误地判定为失控之前生产的产品的平均数量约为 $n / 0.0027$），从 @tbl-13_2 中可以明显看出，我们应该至少组合 9 个产品。这意味着每个数据值（等于组合中的缺陷数量）的均值至少为 $9\times4 = 36$。 

| $n$ | 平均产品数量 |
| ---- | ---- |
| 1 | 19.6 |
| 2 | 20.66 |
| 3 | 19.80 |
| 4 | 19.32 |
| 5 | 18.80 |
| 6 | 18.18 |
| 7 | 18.13 |
| 8 | 18.02 |
| 9 | 18 |
| 10 | 18.18 |
| 11 | 18.33 |
| 12 | 18.51 |

: {#tbl-13_2}

::: {#exr-13_5_a}
对于某汽车厂商而言，以每 10 辆汽车为单元，连续单元发现的缺陷数量如下表所示： 

| 汽车 | 缺陷量 | 汽车 |  缺陷量 | 汽车 |  缺陷量 | 汽车 |  缺陷量 |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 1 | 141 | 6 | 74 | 11 | 63 | 16 | 68 |
| 2 | 162 | 7 | 85 | 12 | 74 | 17 | 95 |
| 3 | 150 | 8 | 95 | 13 | 103 | 18 | 81 |
| 4 | 111 | 9 | 76 | 14 | 81 | 19 | 102 |
| 5 | 92 | 10 | 68 | 15 | 94 | 20 | 73 |

整个生产过程看起来是否一直处于受控状态？
:::

::: {#sol-13_5_a}
因为 $\overline{X}=94.4$，所以控制限为：

$$
\begin{align*}
\text{LCL}&=94.4 - 3\sqrt{94.4}=65.25\\
\text{UCL}&=94.4 + 3\sqrt{94.4}=123.55
\end{align*}
$$

由于前三个数据值大于上控制限（*UCL*），删除这三个数据并重新计算样本均值。由此可得：

$\overline{X}=\frac{(94.4)\times20-(141 + 162+150)}{17}=84.41$

所以新的控制限为：

$$
\begin{align*}
\text{LCL}&=84.41 - 3\sqrt{84.41}=56.85\\
\text{UCL}&=84.41 + 3\sqrt{84.41}=111.97
\end{align*}
$$

此时，因为其余 17 个数据值都落在控制限内，我们可以宣称该 **过程** 现在处于受控状态，均值为 84.41。然而，由于在达到受控状态之前，缺陷的平均数量似乎一开始就很高，所以数据值 $X_4$ 也很可能是在 **过程** 处于受控状态之前产生的。因此，在这种情况下，需要删除 $X_4$ 并重新计算似乎是比较谨慎的做法。基于其余 16 个数据值，我们得到：

$$
\begin{align*}
\overline{X}&=82.56\\
\text{LCL}&=82.56 - 3\sqrt{82.56}=55.30\\
\text{UCL}&=82.56 + 3\sqrt{82.56}=109.82
\end{align*}
$$

所以，该过程现在看起来处于受控状态，其均值为 82.56。 
$\blacksquare$
:::