## 概率模型的所有参数都指定时的拟合优度检验 {#sec-11_2}
假设有 $n$ 个独立的随机变量 $Y_1, Y_2, \dots, Y_n$，其中每个变量的取值为 $1, 2, \dots, k$，我们希望检验如下的零假设：$Y_j$ 的概率质量函数为 $\{ p_i, i = 1, \dots, k \}$。也就是说，如果用 $Y$ 表示任意一个 $Y_j$，那么零假设为：

$H_0: P\{Y = i\} = p_i, \quad i = 1, \dots, k$

备择假设为：

$H_1: P\{Y = i\} \neq p_i, \quad \text{对于某些} i = 1, \dots, k$

为了检验上述假设，令 $X_i$（$i = 1, \dots, k$）表示 $Y_j$ 等于 $i$ 的数量。由于每个 $Y_j$ 都独立地以概率 $P\{Y = i\}$ 等于 $i$，那么原假设 $H_0$ 为真时，$X_i$ 服从参数为 $n$ 和 $p_i$ 的二项分布。因此，当原假设 $H_0$ 为真时，

$E[X_i] = np_i$

因此，可以用 $(X_i - np_i)^2$ 来判断 $p_i$ 是否确实等于 $P\{Y = i\}$。当 $(X_i - np_i)^2$ 比较大时，则表明 $H_0$ 可能不成立。实际上，这种推理让我们考虑以下检验统计量：

$$
T = \sum_{i=1}^k \frac{(X_i - np_i)^2}{np_i}
$$ {#eq-11_2_1}

并且，当 $T$ 较大时，我们将拒绝零假设。

为了确定临界区，首先需要指定显著性水平 $\alpha$，然后确定满足下式的临界值 $c$：

$P_{H_0}\{T \geq c\} = \alpha$

也就是说，我们需要确定 $c$，使得当 $H_0$ 为真时，统计量 $T$ 大于等于 $c$ 的概率为 $\alpha$。在显著性水平 $\alpha$ 下，当 $T \geq c$ 时，则需要拒绝原假设 $H_0$，否则就接受原假设。

接下来我们需要确定 $c$ 的值。确定 $c$ 的经典的方法是使用如下的结论：当 $n$ 较大时，在 $H_0$ 为真时，$T$ 近似服从自由度为 $k - 1$ 的卡方分布（当 $n \rightarrow \infty$ 时，$T$ 服从自由度为 $k-1$ 的卡方分布）。因此，当 $n$ 较大时，$c$ 的取值可以是 $\chi^2_{\alpha, k-1}$，因此在显著性水平为 $\alpha$ 时的近似检验为：

$\begin{align} \text{拒绝} \quad &H_0 \quad \text{如果} T \geq \chi^2_{\alpha, k-1} \\ \text{接受} \quad &H_0 \quad \text{否则} \end{align}$

如果观察到的统计量 $T$ 的值为 $t$，那么上述检验等价于在 $\alpha$ 值大于或等于如下的 $p-\text{value}$ 时拒绝 $H_0$：

$p-\text{value} = P_{H_0}\{T \geq t\} \approx P\{\chi^2_{k-1} \geq t\}$

其中 $\chi^2_{k-1}$ 是自由度为 $k - 1$ 的卡方分布随机变量。

经验规则指出，对于 $n$ 来说，$n$ 需要足够大才能使得如上的检验是一个比较好的近似检验，一般而言，对于每个 $i, i = 1,..., k$，需要满足 $np_i \geq 1$，并且至少 80% 的 $np_i$ 值应大于 5。