## 具有固定边缘总和的列联表的独立性检验 {#sec-11_5}
在 @exr-11_4_a 中，我们确定了：在特定人群中性别和政治派别的相关性。为了检验我们的原假设，我们首先从该人群中选择了一个随机样本，然后记录了样本的 **特征**（*characteristics*）。

然而，我们收集数据的另一种方式是：预先确定样本中男性和女性的数量，然后从男性和女性人群中选择对应大小的随机样本。也就是说，样本中的男性和女性的数量并不是由随机抽取而决定，而是提前确定他们的数量。因为这样做会导致样本中的男性样本总数和女性样本总数都有固定的特定值，所以我们通常称由此得到的列联表具有固定的边缘（*fixed margins*）。

事实证明，即便使用以上的规则来收集数据，@sec-11_4 中给出的假设检验仍然可以用来检验两个特征的独立性。检验统计量仍然是 

$TS=\sum_{i}\sum_{j}\frac{(N_{ij}-\hat{e}_{ij})^{2}}{\hat{e}_{ij}}$

* $N_{ij}$ 是样本中同时具有 $X-\text{特征}$ $i$ 和 $Y-\text{特征}$ $j$ 的样本数量
* $N_{i}$ 是样本中具有 $X-\text{特征}$ $i$ 的样本数量
* $M_{j}$ 是样本中具有 $Y-\text{特征}$ $j$ 的样本数量
* $\hat{e}_{ij}=n\hat{p}_{i}\hat{q}_{j}=\frac{N_{i}M_{j}}{n}$ ，其中 $n$ 是样本的总大小。

此外，当原假设 $H_0$ 为真时， $TS$ 仍然近似具有自由度为 $(r - 1)(s - 1)$ 的卡方分布。这里的量 $r$ 和 $s$ 分别指的是 $X-\text{特征}$ 和 $Y-\text{特征}$ 可能取值的数量。换句话说，独立性假设检验与某个特征的边缘总和是预先固定的还是由整个总体的随机样本产生的无关。

::: {#exr-11_5_a}
随机选取了 20000 名不吸烟者和 10000 名吸烟者，并对他们进行了为期 10 年的跟踪调查。以下数据显示了在这段时间内患肺癌的人数。

|    |吸烟者数量|不吸烟者数量|总计|
|----|----|----|----|
|患肺癌数量|62|14|76|
|未患肺癌数量|9938|19986|29924|
|总计|10000|20000|30000|

在 1% 的显著性水平下检验吸烟与肺癌是否独立的假设。
:::

::: {#sol-11_5_a}
当吸烟和肺癌无关时，每个 $ij$ 单元格中预期人数的估计值为：

$\hat{e}_{11}=\frac{(76)(10000)}{30000}=25.33$

$\hat{e}_{12}=\frac{(76)(20000)}{30000}=50.67$

$\hat{e}_{21}=\frac{(29924)(10000)}{30000}=9974.67$

$\hat{e}_{22}=\frac{(29924)(20000)}{30000}=19949.33$

因此，检验统计量的值为：

$\begin{align*} TS&=\frac{(62 - 25.33)^{2}}{25.33}+\frac{(14 - 50.67)^{2}}{50.67}+\frac{(9938 - 9974.67)^{2}}{9974.67} \\ &+\frac{(19986 - 19949.33)^{2}}{19949.33}\\ &=53.09 + 26.54 + 0.13 + 0.07 = 79.83 \end{align*}$

因此，$p-\text{value}\approx P(\chi_{1}^{2}>79.83)=1-\text{pchisq}(79.83,1)\approx0$ 。

所以，在任何显著性水平下，随机选取的一个人患肺癌与否与这个人是否吸烟无关的原假设都会被拒绝。
:::

接下来，我们将介绍如何使用本节的计算框架来检验 $m$ 个离散总体分布是否相等的假设。考虑 $m$ 个独立的总体，每个总体的成员取值为 $1,\ldots,n$。假设从总体 $i$ 中随机选取的一个成员的值为 $j$ 的概率为 $p_{i,j}$ ，其中 $i = 1,\ldots,m$，$j = 1,\ldots,n$。检验如下的原假设：

$H_0：\forall j = 1,\ldots,n, \quad p_{1,j}=p_{2,j}=p_{3,j}=\cdots=p_{m,j}$

首先考虑由这 $m$ 个总体的所有成员组成的 **超总体**（*superpopulation*）。该 **超总体** 的任何成员都可以根据两个 **特征** 进行分类。第一个特征指定成员来自 $m$ 个总体中的哪一个，第二个特征指定其取值。于是，$m$ 个总体的分布都相等的假设就变成了如下的假设：对于每个取值而言，该取值在 $m$ 个总体中的每一个中的比例都是相同的。但这完全等同于：从超总体中随机选取的一个成员的两个特征是独立的。

因此，我们可以通过从每个总体中随机选取样本成员来检验 $H_0$。如果我们用 $M_i$ 表示从总体 $i$ 中抽取的样本大小，用 $N_{i,j}$ 表示该样本中取值等于 $j$ 的数量，其中 $i = 1,\ldots,m$，$j = 1,\ldots,n$，那么我们可以通过检验如下的列联表中特征的独立性来检验 $H_0$。

|取值|总体 1|总体 2| $\cdots$ |总体 $i$|$\cdots$|总体 $m$|总计|
|----|----|----|----|----|----|----|----|
|1| $N_{1,1}$ | $N_{2,1}$ |$\cdots$| $N_{i,1}$ |$\cdots$| $N_{m,1}$ | $N_1$ |
|2||||||||
|$\vdots$||||||||
|$j$| $N_{1,j}$ | $N_{2,j}$ |$\cdots$| $N_{i,j}$ |$\cdots$| $N_{m,j}$ | $N_j$ |
|$\vdots$||||||||
|$n$| $N_{1,n}$ | $N_{2,n}$ |$\cdots$| $N_{i,n}$ |$\cdots$| $N_{m,n}$ | $N_n$ |
|总计| $M_1$ | $M_2$ |$\cdots$| $M_i$ |$\cdots$| $M_m$ | |

注意，$N_j$ 表示样本中取值为 $j$ 的成员的数量。

::: {#exr-11_5_b}
最近的一项研究报告称，他们从四个不同的国家随机选取了500名（每个国家随机选择 500 名）女性办公室职员进行调研。其中一个问题就是：她们在工作中是否经常受到言语或性虐待，并得到了如下数据。

|国家|受虐待的人数|
|----|----|
|澳大利亚|28|
|德国|30|
|日本|51|
|美国|55|

基于这些数据，这些国家中经常在工作中感到受虐待的女性办公室职员的比例相同这一说法是否合理？
:::

::: {#sol-11_5_b}
将上述数据表示成如下的列联表：

||国家 1|国家 2|国家 3|国家 4|总计|
|----|----|----|----|----|----|
|受到虐待|28|30|51|55|171|
|未受虐待|472|470|442|445|1829|
|总计|500|500|500|500|2000|

可以通过检验上述列联表中的独立性来检验原假设。使用 R 语言得到检验统计量的值为 $TS = 19.51$，对应的 $p-\text{value}$ 为 0.0002。

因此，在 1% 的显著性水平下（实际上，在任何高于 0.02% 的显著性水平下），我们将拒绝这些国家中的不同女性在工作中受到虐待的比例相同这一假设。$\blacksquare$
:::