## 引言 {#sec-7_1}
令 $X_1, ..., X_n$ 是来自分布为 $F_\theta$ 的随机样本，这个分布由一个未知参数向量 $\theta$ 来指定。例如，样本可能来自一个平均值未知的泊松分布；或者可能来自一个均值和方差都未知的正态分布。在概率论中，通常假设分布的所有参数都是已知的，而在统计学中，情况则恰恰相反。统计学的核心问题之一就是使用观测数据来推断未知参数。

* 在 @sec-7_2 中，我们会介绍 **最大似然方法**（*maximum likelihood*）来估计未知参数。因为 **最大似然估计** 指定了一个单一值作为 $\theta$ 的估计，因此我们称其为 **点估计**（*point estimates*）。
* 在 @sec-7_3 中，我们会考虑 **区间估计**（*interval estimates*）的相关问题。对于区间估计而言，我们不会指定某个值作为 $\theta$ 的估计，而是会指定一个区间来估计 $\theta$。此外，我们还考虑了可以对这样的区间估计报以多少 **置信度**（*confidence*）的问题。在该节中，我们会展示如何计算一个均值未知、但给定方差的正态分布的均值的区间估计。接下来，我们还会讨论区间估计中的一系列问题。在 @sec-7_3_1 中，我们会讨论方差未知的正态分布的均值的区间估计。在 @sec-7_3_2 中，我们会讨论正态分布的方差的区间估计。
* 在 @sec-7_4 中，我们会讨论两个正态分布的均值差的区间估计，我们会分两种情况进行讨论：
    * 这两个正态分布的方差是已知的；
    * 这两个正态分布的方差未知，但是我们会假设他们的方差是相同的。
* 在 @sec-7_5 和 @sec-7_6 中，我们会分别讨论伯努利随机变量和指数随机变量的均值的区间估计。
* 在 @sec-7_7 中，我们会重新回到计算未知参数的点估计的一般性问题上来，并展示如何通过 **均方误差**（*mean square error*）来评估估计量。我们还会讨论估计量的偏差，并会探讨偏差与均方误差之间的关系。
* 在 @sec-7_8 中，我们会考虑在有先验信息可用时确定未知参数估计值的问题，这就是 **贝叶斯**（*bayesian*）方法。贝叶斯方法假设在观察数据之前，决策者总是可以获得关于 $\theta$ 的信息，并且该信息可以用 $\theta$ 的概率分布来表示。我们还会讨论如何使用估计量和参数 $\theta$ 之间的均方误差来计算 **贝叶斯估计量**（*Bayes estimator*）。 

::: {.callout-note title="估计量与估计值"}
在下一节会讲到：任何用于估计未知参数 $\theta$ 的值的统计量都称为 $\theta$ 的 **估计量**（*estimator*）。估计量的观测值称为 **估计值**（*estimate*）。
:::