## 伯努利随机变量均值的近似置信区间 {#sec-7_5}
考虑某个物品的一个总体，总体中每个物品达到某些标准的概率都是未知概率 $p$，并且物品之间的达标率是相互独立的。如果我们从总体中抽取 $n$ 个物品进行测试，以确定这些物品是否达到标准，我们如何利用抽检所得到的数据来计算 $p$ 的置信区间？

如果我们令 $X$ 表示抽取的 $n$ 个物品中符合标准的物品数量，那么 $X$ 是参数为 $(n, p)$ 的二项随机变量。因此，当 $n$ 较大时，根据二项分布会近似为正态分布的特性（@sec-6_3），$X$ 近似服从均值为 $np$、方差为 $np(1-p)$ 的正态分布。因此，

$$
\frac{X - np}{\sqrt{np(1-p)}} \approx \mathcal{N}(0, 1)
$$ {#eq-7_5_1}

其中 $\approx$ 表示“近似服从”。因此，对于任何 $\alpha \in (0, 1)$，我们有：

$P\left\{-z_{\alpha/2} < \frac{X - np}{\sqrt{np(1-p)}} < z_{\alpha/2}\right\} \approx 1 - \alpha$

因此，如果对于实验数据 $X = x$ 而言，$p$ 的近似 $100(1-\alpha)\%$ 置信区为：

$$
\left\{p : -z_{\alpha/2} < \frac{x - np}{\sqrt{np(1-p)}} < z_{\alpha/2}\right\}
$$ {#eq-7_5_001}

然而，@eq-7_5_001 的区域并非区间。令 $\hat{p} = X/n$ 表示符合标准的物品所占的比例，以便得到 $p$ 的置信区间。根据 @exr-7_2_a 可知，$\hat{p}$ 是 $p$ 的最大似然估计，因此 $\hat{p}$ 应该近似等于 $p$。因此，$\sqrt{n\hat{p}(1-\hat{p})}$ 将近似等于 $\sqrt{np(1-p)}$，因此由 @eq-7_5_1 可以得到：

$\frac{X - np}{\sqrt{n\hat{p}(1-\hat{p})}} \approx \mathcal{N}(0, 1)$

因此，对于任何 $\alpha \in (0, 1)$，我们有：

$P\left\{-z_{\alpha/2} < \frac{X - np}{\sqrt{n\hat{p}(1-\hat{p})}} < z_{\alpha/2}\right\} \approx 1 - \alpha$

即，

$P\{-z_{\alpha/2}\sqrt{n\hat{p}(1-\hat{p})} < np - X < z_{\alpha/2}\sqrt{n\hat{p}(1-\hat{p})}\} \approx 1 - \alpha$

将上述不等式两边都除以 $n$，并根据 $\hat{p} = X/n$，有：

$$
P\left\{\hat{p} - z_{\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}} < p < \hat{p} + z_{\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\right\} \approx 1 - \alpha
$$ {#eq-7_5_002}

@eq-7_5_002 给出了 $p$ 的 $100(1-\alpha)\%$ 的近似置信区间。

::: {#exm-7_5_a}
从一批晶体管中随机抽取 100 个样本，并测试这 100 个样本是否符合当前标准。如果其中有 80 个晶体管符合标准，那么符合标准的所有晶体管的比例 $p$ 的近似 95% 置信区间为：

$(0.8 - 1.96 \sqrt{\frac{0.8(0.2)}{100}}, \, 0.8 + 1.96 \sqrt{\frac{0.8(0.2)}{100}}) = (0.7216, \, 0.8784)$

也就是说，在 95% 的置信度的情况下，符合标准的晶体管的比例在 72.16% 到 87.84% 之间。
:::

::: {#exr-7_5_b}
2013 年 8 月，《纽约时报》报道了最近的一项民意调查，结果显示 52% 的人（误差范围为 $\pm 4\%$）对奥巴马总统的工作表现呈肯定态度。这意味着什么？我们能推断出有多少人参与了调查吗？
:::

::: {#sol-7_5_b}
新闻媒体通常会使用 95% 置信区间。由于 $z_{0.025} = 1.96$，令 $p$ 代表肯定奥巴马总统工作表现的人的比例，那么关于 $p$ 的 95% 置信区间可以表示为：

$\hat{p} \pm 1.96 \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} = 0.52 \pm 1.96 \sqrt{\frac{0.52 \times 0.48}{n}}$

其中，$n$ 是样本的大小。由于“误差范围”是 $\pm 4\%$，由此可以推导出：

$1.96 \sqrt{\frac{0.52 \times 0.48}{n}} = 0.04$

即：

$n = \frac{(1.96)^2 \times 0.52 \times 0.48}{(0.04)^2} = 599.29$

也就是说，大约有 599 人参与了调查，其中 52% 的人对奥巴马总统的工作表现持肯定态度。 $\blacksquare$
:::

我们经常希望为 $p$ 指定一个近似的 $100(1 - \alpha)\%$ 的置信区间，并且该置信区间的长度不能超过某个给定的值（$b$）。获得这样的、有大小限定的置信区间的问题在于确定合适的样本量 $n$。从样本大小为 $n$ 的样本中得到的 $p$ 的近似 $100(1 - \alpha)\%$ 的置信区间的长度为：

$2z_{\alpha/2} \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}$

该值近似等于 $2z_{\alpha/2}\sqrt{\frac{p(1-p)}{n}}$。不幸的是，因为 $p$ 是未知的，因此我们不能简单地令 $2z_{\alpha/2}\sqrt{\frac{p(1-p)}{n}} = b$，然后再确定所需的样本量 $n$。然而，我们可以先进行一个初步的抽样，以获得 $p$ 的粗略估计，然后利用该估计来确定 $n$。

也就是说，我们使用初步抽样样本中的比例 $p^*$ 作为 $p$ 的初步估计；然后通过求解下列方程确定总样本量 $n$：

$2z_{\alpha/2} \sqrt{\frac{p^*(1 - p^*)}{n}} = b$

对上式两边平方得到：

$(2z_{\alpha/2})^2 \frac{p^*(1 - p^*)}{n} = b^2$

即：

$n = \frac{(2z_{\alpha/2})^2 p^*(1 - p^*)}{b^2}$

也就是说，如果最初抽取了 $k$ 个样本以获得 $p$ 的初步估计，那么还应再抽取 $n - k$ 个样本。

::: {#exm-7_5_c}
某芯片制造商生产的每个芯片的达标率为某个未知概率 $p$（假设芯片之间的达标率是相互独立的）。已经抽取了 30 个芯片的初步样本以便获得区间长度为 0.05 的 $p$ 的近似 99% 置信区间。在抽取的 30 个芯片中，如果有 26 个芯片符合标准（达标），那么 $p$ 的初步估计为 $26/30$。使用该值，得到长度为 0.05 的 99% 置信区间所需的样本量为：

$n = \frac{4(z_{0.005})^2 \cdot \frac{26}{30} \left(1 - \frac{26}{30}\right)}{(0.05)^2} = \frac{4(2.58)^2 \cdot \frac{26}{30} \cdot \frac{4}{30}}{(0.05)^2} = 1231$

因此，我们现在应该再抽取 1201 个芯片，并且如果其中有 1040 个芯片是符合标准的，那么 $p$ 的最终 99% 置信区间为：

$\left(\frac{1066}{1231} - \sqrt{\frac{1066}{1231} \left(1 - \frac{1066}{1231}\right)} \cdot \frac{z_{0.005}}{\sqrt{1231}}, \, \frac{1066}{1231} + \sqrt{\frac{1066}{1231} \left(1 - \frac{1066}{1231}\right)} \cdot \frac{z_{0.005}}{\sqrt{1231}}\right)$

即：

$p \in (0.84091, 0.89101)$ $\blacksquare$
:::

::: {.callout-tip title="备注"}
如前所示，当样本量为

$n = \frac{(2z_{\alpha/2})^2}{b^2} \cdot p(1-p)$

时，$p$ 的 $100(1-\alpha)\%$ 置信区间的长度将近似为 $b$。

现在很容易证明，对于函数 $g(p) = p(1-p)$（定义域为：$0 \leq p \leq 1$）而言，当 $p = \frac{1}{2}$ 时，$g(p)$ 取得最大值 $\frac{1}{4}$。因此，$n$ 的上界为

$n \leq \frac{(z_{\alpha/2})^2}{b^2}$

因此，样本量至少为 $\frac{(z_{\alpha/2})^2}{b^2}$ 时，可以确保在不需要任何额外的抽样的情况下，置信区间的长度不超过 $b$。
:::

@tbl-7_3 对本节的内容进行了总结。

| 置信区间类型 | 置信区间|
|--------------------------|--------------------------|
| 双边置信区间                | $\hat{p} \pm z_{\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$                                           |
| 单边下置信区间          | $\left(-\infty, \, \hat{p} + z_{\alpha} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\right)$                       |
| 单边上置信区间         | $\left(\hat{p} - z_{\alpha} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}, \, \infty\right)$                        |
: $X \sim \mathcal{N}(n, p)$，$\hat{p} = X/n$，$p$ 的 $100(1-\alpha)\%$ 的置信区间 {#tbl-7_3}