## 引言 {#sec-6_1}
统计学是一门从观测数据中得出结论的科学。例如，在技术研究中，经常遇到的一种情况是：我们可能会面对数量庞大的、具有可测量值（*measurable values*）的对象的集合。我们希望通过对这些数量庞大的对象适当抽样（*sampling*）并分析抽样得到的样本对象，从而得到一些和全部对象相关的结论。

为了使用样本数据（*sample data*）推断总体（*pupulation*），必须对样本与总体之间的关系作某些假设。通常，非常合理的一个假设是：总体会存在一个潜在的概率分布，因此可以认为，从总体中抽取的对象的测量值是独立随机变量并且其分布于总体分布一致。如果通过随机抽取的方式来获得样本数据，那么样本数据是独立、同总体分布一致这样的假设是合理的。

::: {#def-6_1_1}
如果 $X_1, ..., X_n$ 是独立同分布的随机变量，其分布函数为 $F$，我们称 $X_1, ..., X_n$ 构成了来自于 $F$ 的 **样本**（*sample*）（有时也称其为随机样本）。
:::

在大多数应用中，总体的分布 $F$ 并非总是事先指定的（事实是，在大多数情况下，$F$ 是未知的），因此我们会尝试使用数据来推断 $F$。

* 有时，我们会假设 $F$ 由一些未知的参数来确定。例如，我们可以假设 $F$ 是一个均值和方差都未知的正态分布，或者是一个均值未知的泊松分布。
* 有时，我们会假设，除了是一个连续分布或者离散分布外，$F$ 几乎没有任何的已知信息。

在使用样本数据推断总体分布的过程中，如果假定总体的潜在分布 $F$ 是由一组未知参数确定的，则称其为 **参数推断**（*parametric inference*）；而如果对总体的潜在分布 $F$ 没有任何假设，则称其为 **非参数推断**（*nonparametric inference*）。

::: {#exm-6_1_a}
假设刚刚安装了一个新工艺以用来生产计算机芯片，并且假设这个新工艺生产的连续芯片的使用寿命是独立、同分布的，其分布是一个未知分布 $F$。

物理原因有时会暗示分布 $F$ 的参数形式。例如，物理原因可能会让我们相信 $F$ 是一个正态分布或者是一个指数分布。在这种情况下，我们面对的将是一个 **参数统计** 问题，我们希望使用观察到的数据来估计 $F$ 的参数。例如，如果假设 $F$ 是正态分布，我们将希望估计其 **均值** 和 **方差**；如果假设 $F$ 是指数分布，我们将希望估计其 **均值**。

在其他情况下，可能没有任何物理依据来假设 $F$ 具有某种特定分布形式。在这种情况下，关于 $F$ 的推断问题将构成一个 **非参数推断** 问题。

::: {.callout-note}
物理原因（*Physical reasons*）指的是基于物理学原理或物理现象的原因。在统计学和概率论中，物理原因通常涉及使用物理理论或实验结果来推导或假设某些统计分布的形式。例如，在某些情况下，物理现象可能会暗示数据遵循某种特定的分布：

1. 正态分布：如果某个过程受到大量小的、独立的随机影响，那么根据中心极限定理，最终的结果可能会接近正态分布。比如，测量误差通常假定为正态分布。
2. 指数分布：在某些情况下，事件的发生是完全随机的，且时间间隔独立且服从相同分布，那么这些时间间隔可能符合指数分布。比如，放射性衰变事件的时间间隔通常假设为指数分布。
3. 泊松分布：当在固定时间间隔内的事件发生是独立的，且事件发生的概率很小，次数很多时，事件的发生次数通常会服从泊松分布。比如，电话交换机中每小时接收到的呼叫数可能服从泊松分布。 $\blacksquare$
:::
:::

在本章中，我们将关注由样本产生的某些统计量（或统计指标）的概率分布，其中 **统计量**（*statistic*）是一个随机变量，统计量的值由样本数据决定。我们将讨论的两个重要的统计量：**样本均值** 和 **样本方差**。

* 在 @sec-6_2 中，我们将介绍 **样本均值**，并推导 **样本均值** 的期望和方差。我们注意到，当样本量至少为中等大小时，样本均值的分布近似正态分布。如上的结论来自于 **中心极限理论**（*the central limit theorem*）。
* 中心极限理论是概率论中最重要的理论之一，我们将在 @sec-6_3 中对其进行讨论。
* 在 @sec-6_4 中，我们将介绍 **样本方差** 并确定其期望。
* 在 @sec-6_5 中，我们假设总体符合正态分布，并给出样本均值和样本方差的联合分布。
* 在 @sec-6_6 中，我们假设从有限元素的总体中采样，并解释采样所得到的样本是“随机样本”的含义。当总体大小相对于样本大小很大时，我们通常将总体视为是无限大的。