## 样本空间和事件 {#sec-3_2}
让我们思考这样的一个实验，在该实验中，我们无法提前确切的预测实验结果。虽然我们无法提前知晓实验结果，但我们可以假定该实验的、所有可能的、结果集合是已知的。所有可能的实验结果的集合，我们称之为实验的 **样本空间**（*sample space*），并用 $S$ 来表示 **样本空间**。

**样本空间** 的例子如下所示：

::: {#exm-3_2_1}
对于确定新生儿性别的实验，$S=\{g,\ b\}$，其中，$g$ 表示小孩为女孩，$b$ 表示小孩为男孩。
:::

::: {#exm-3_2_2} 
对于确定已编号的 7 匹马（编号为 1~7 号）之间的赛马实验，$S=\{(1, 2, 3, 4, 5, 6, 7)的所有排序\}$。(2, 3, 1, 6, 5, 4, 7) 的实验结果意味着 2 号马排在第一名，3 号马排在第二名，然后是 1 号马，依此类推……
:::

::: {#exm-3_2_3}
假如我们想确定患者的最小有效用药剂量，则这个实验的一个可能的样本空间就是让 $S$ 包含所有的正数，即 $S=(0,\ \infty)$。如果用药剂量为 $x$ 时开始对患者有效，但是任何低于 $x$ 的用药剂量均对患者无效，那么此次试验的结果就是 $x$。
:::

**样本空间** 的任何子集 $E$ 称之为一个 **事件**（*event*）。也就是说，一个 **事件** 是由实验的可能结果组成的集合。如果实验的结果存在于 $E$ 中，那么我们就说， $E$ 已经发生。如下是 **事件** 的一些例子：

* 在 @exm-3_2_1 中，如果 $E = \{g\}$，那么 $E$ 表示的事件为：新生儿为女孩。类似的，如果 $F = \{b\}$，那么 $F$ 表示的事件为：新生儿为男孩。
* 在 @exm-3_2_2 中，如果 $E=\{以 3 为首的所有排序\}$，则 $E$ 表示的事件为：3 号马赢得比赛。

对于样本空间 $S$ 中的任意两个事件 $E$ 和 $F$，我们定义一个新事件 $E \cup F$，并称其为事件 $E$ 和 $F$ 的并集。$E \cup F$ 由所有属于 $E$ 或 $F$ 或同时属于 $E$ 和 $F$ 的结果组成。也就是说，如果 事件 $E$ 或 事件 $F$ 发生，那么事件 $E \cup F$ 就会发生。例如，在 @exm-3_2_1 中，如果 $E = \{g\}$ 且 $F = \{b\}$，那么 $E \cup F = \{g, b\}$。也就是说，$E \cup F$ 是整个样本空间 $S$。在 @exm-3_2_2  中，如果 $E = \{所有以 6 为首的比赛结果\}$ 是 6 号马赢得比赛的事件，而 $F = \{所有第二名是 6 的比赛结果\}$ 是 6 号马获得第二名的事件，那么 $E \cup F$ 就是6 号马获得前两名的事件。

类似地，对于样本空间 $S$ 中的任意两个事件 $E$ 和 $F$，我们也可以定义一个新事件 $EF$（有时也记作 $E \cap F$），并称之为事件 $E$ 和 $F$ 的交集。$E \cap F$ 由属于 $E$ 并且同时属于 $F$ 的所有结果组成。也就是说，只有当事件 $E$ 和 $F$ 都发生时，事件 $EF$ 才会发生。例如，在 @exm-3_2_3 中，如果 $E = (0, 5)$ 是药品所需剂量小于 5 的事件，而 $F = (2, 10)$ 是所需剂量在 2~10 之间的事件，那么 $EF = (2, 5)$ 就是所需剂量在 2~5 之间的事件。在 @exm-3_2_2 中，如果 $E = \{所有以 5 结尾的结果\}$ 是5 号马获得最后一名的事件，而 $F = \{所有以 5 为首的结果\}$ 是 5 号马获得第一名的事件，那么事件 $EF$ 则不包含任何结果，因此事件 $EF$ 不可能发生。对于不可能发生的事件，我们称其为 **空事件**，并用 $\emptyset$ 表示。因此，$\emptyset$ 指的是不包含任何实验结果的事件。如果 $EF = \emptyset$，则意味着 $E$ 和 $F$ 不能同时发生，此时我们称 $E$ 和 $F$ 为 **互斥事件**。

对于 $\forall E$，我们定义事件 $E^c$ 为事件 $E$ 的补集。事件 $E^c$ 由样本空间 $S$ 中不属于 $E$ 的所有结果组成。也就是说，当且仅当事件 $E$ 不发生时，$E^c$ 才会发生。在 @exm-3_2_1 中，如果 $E = \{b\}$ 是小孩为男孩的事件，那么 $E^c = \{g\}$ 就是小孩为女孩的事件。需要注意，由于实验必须会产生某种结果，因此 $S^c = \emptyset$。

::: {.callout-note}
$E^c=\{\forall F \subset S,\ E \cap F = \emptyset 且 E \cup F = S\}$
:::

对于任意两个事件 $E$ 和 $F$，如果事件 $E$ 中的所有结果在事件 $F$ 中都存在，那么我们说事件 $E$ 包含在事件 $F$ 中，并记作 $E \subset F$。因此，如果 $E \subset F$，那么事件 $E$ 的发生意味着事件 $F$ 必然发生。如果 $E \subset F$ 且 $F \subset E$，那么我们说 $E$ 和 $F$ 相等（或相同），并记作 $E = F$。

我们也可以定义超过两个事件的并集和交集。特别是，事件 $E_1, E_2, ..., E_n$ 的并集，记作 $E_1 \cup E_2 \cup ... \cup E_n$ 或者 $\cup_1^n{E_i}$。事件  $\cup_1^n{E_i}$ 至少包含一个 $E_i(i = 1, 2, ..., n)$ 中的所有结果。类似地，事件 $E_i(i = 1, 2, ..., n)$的交集，记作 $E_1E_2...E_n$，为同时出现在所有事件 $E_i(i = 1, 2, ..., n)$ 中的结果组成的事件。换句话说，当至少有一个事件 $E_i$ 发生时，$E_i$ 的并集就会发生；当所有事件 $E_i$ 都发生时，则  $E_i$ 的交集就会发生。