## 等概率样本空间 {#sec-3_5}
对于执行大量次数的实验来说，我们会很自然地假设：样本空间中的每个结果发生的可能性是相等的。也就是说，对于许多实验而言，其样本空间 $S$ 是一个有限集合，$S = \{1,2,...,N\}$，通常很自然地假设：

$$
P(\{1\}) = P(\{2\}) = ··· = P(\{N\}) = p
$$

根据 **公理 2** 和 **公理 3**，我们有：$1 = P(S) = P(\{1\}) + P(\{2\}) + ··· + P(\{N\}) = Np$，故而有：

$$
P(\{i\}) = p = \frac{1}{N}
$$

由此，根据 **公理 3**，对于任意事件 $E$：$P(E)=\frac{位于\ E\ 中的结果数}{N}$。

也就是说，如果我们假设实验的每个结果发生的可能性是相等的，那么任何事件 $E$ 的概率就等于样本空间中包含在 $E$ 中的结果的比例。

因此，为了计算概率，通常需要有效地计算出给定事件可以以多少种不同的方式发生。为此，我们将使用以下规则。

### 计数的基本原理 {#sec-3_5_1} 
假设要执行两个实验，如果实验 1 可能有 $m$ 种可能的结果，并且对于实验 1 的每一种结果，实验 2 都有 $n$ 种可能的结果，那么这两个实验总共有 $mn$ 种可能的结果。

:::{.callout-tip title="计数的基本原理的证明"}
可以使用如下的方式来枚举所有可能的实验结果：

$$
\begin{array}{ccc}
    (1,1), & (1,2), & ..., &(1,n) \\
    (2,1), & (2,2), & ..., &(2,n) \\
    \ \ \ ... & \\
    (m,1), & (m,2), & ..., &(m,n) \\
\end{array}
$$

如果实验 1 产生了第 $i$ 种可能的结果，并且实验 2 产生了第 $j$ 种可能的结果，我们称实验结果为 $(i, j)$。因此，可能的结果集由 $m$ 行组成，其中每行包含 $n$ 个元素。
:::

::: {#exr-3_5_a}
从一个包含 6 个白球和 5 个黑球的碗中 “随机抽取” 两个球。其中一个球是白色的，另一个是黑色的概率是多少？
:::

:::{#sol-3_5_a}
如果我们认为选球的顺序非常重要，那么第一个抽取的球可能是 11 个中的任何一个，第二个抽取的球可能是剩下的 10 个中的任何一个，因此样本空间包含 11 × 10 = 110 个点。此外，有 6 × 5 = 30 种方式使得第一个球是白色的，第二个球是黑色的。同样地，有 5 × 6 = 30 种方式使得第一个球是黑色的，第二个球是白色的。因此，假设 “随机抽取” 意味着样本空间中的每个点都有相同的可能性，那么我们可以看出需要计算的概率是：

$$
\frac{30 + 30}{110} = \frac{6}{11}
$$
:::

对于两个以上的实验，**计数的基本原理** 可以按如下的方式泛化（*generalized*）：

::: {.callout-tip title="计数基本原理的泛化"}
如果要执行 $r$ 个实验，其中第一个实验有 $n_1$ 种可能的结果，如果对于这 $n_1$ 种可能的结果，第二个实验有 $n_2$ 种可能的结果，如果对于前两个实验的每种可能的结果，第三个实验有 $n_3$ 种可能的结果，以此类推，那么这 $r$ 个实验总共有 $n_1 \cdot n_2 \cdot \cdot \cdot n_r$ 种可能的结果。
:::

为了说明 **基本计数原理**，让我们来确定 $n$ 个不同对象的线性序（*linear order*）排列的方式的数量。例如，字母 a、b、c 有多少种不同的排列方式？

通过直接枚举，我们可以发现有 6 种，即 abc、acb、bac、bca、cab、cba，其中的每一个都称为一个 **排列**（*permutation*）。因此，3 个对象有 6 种可能的 **排列**。如上的结果也可以从基本原理中得出，因为第一个对象可以是 3 个字母中的任何一个，第二个对象可以从剩下的 2 个字母中选择，第三个对象则从剩下的一个字母中选择。因此，有 3・2・1 = 6 种可能的 **排列**。

以此类推，对于 $n$ 个对象，其不同的排列种类为：$n \cdot (n-1) \cdot (n-2) \cdot \cdot \cdot 3 \cdot 2 \cdot 1$。为了方便，我们将如上的式子记为 $n!$，读作“$n$ 的阶乘”。为了方便，我们令 $0!=1$。

$$
n! = n \cdot (n-1) \cdot (n-2) \cdot \cdot \cdot 3 \cdot 2 \cdot 1
$$

例如：

* $1! = 1$
* $2! = 2 \cdot 1 = 2$
* $3! = 3 \cdot 2 \cdot 1 = 6$
* $4! = 4 \cdot 3 \cdot 2 \cdot 1 = 24$

::: {#exr-3_5_b}
琼斯先生有 10 本书要放在他的书架上。其中，有 4 本是数学书，3 本是化学书，2 本是历史书，还有 1 本是语言书。琼斯想把这些书按主题分类放在一起排列在书架上。有多少种不同的排列方式？
:::

::: {#sol-3_5_b}
有 4! 3! 2! 1! 种排列方式使得数学书排在最前面，然后是化学书，接着是历史书，最后是语言书。同样地，对于每个可能的主题顺序，都有 4! 3! 2! 1! 种可能的排列方式。因此，由于有 4! 种可能的主题顺序，所以所求的答案是 4! × 4! × 3! × 2! × 1! = 6912。
:::

::: {#exr-3_5_c}
一个概率论课程的班级由 6 名男生和 4 名女生组成。在一次考试中，根据学生的考试成绩进行了排名。假设 10 名学生的考试成绩都不相同：

* （a）学生的排名有多少种不同的可能？
* （b）如果所有排名的可能性都相同，那么女生获得前 4 名的概率是多少？
:::

:::{#sol-3_5_c}

* （a）因为每个排名都对应着 10 个人的一个特定有序排列，所以学生的排名可能性有 10! = 3,628,800 种。
* （b）由于女生有 4! 种可能的排名方式，男生有 6! 种可能的排名方式，根据 **基本计数原理**，女生获得前 4 名的可能排名有 (6!)(4!) = (720)(24) = 17,280 种。因此，所求的概率为：$\frac{6!4!}{10!}=\frac{4 \cdot 3 \cdot 2 \cdot 1}{10 \cdot 9 \cdot 8 \cdot 7} = \frac{1}{210}$。
:::

现在，假设我们想要从 $n$ 个对象中选择 $r$ 个对象，并确定这 $r$ 个不同对象所形成的排列方式的数量。例如，从五个物品 A、B、C、D、E 中选择 3 个物品，总共有多少种不同的选择方式？为了回答这个问题，由于有 5 种方式来选择第一个物品，4 种方式来选择下一个物品，3 种方式来选择最后一个物品。因此，当选择的物品存在顺序依赖时，有 5・4・3 种方式来选择这 3 个物品。然而，在存在顺序依赖时，任意选择的 3 个物品（比如 A、B 和 C ）都会被计算 6 次（ABC、ACB、BAC、BCA、CAB、CBA），因此可以形成的不同选择的总数是：(5・4・3)/(3・2・1) = 10。

一般来说，$n (n − 1)・・・(n − r + 1)$ 表示在顺序依赖条件下，从 $n$ 个物品中选择 $r$ 个物品的不同选择方式的数量。由于在这种计数中，每 $r$ 个物品的选择方式都会被计算 $r!$ 次，因此，从 $n$ 个物品中可以形成的 $r$ 个不同物品的数量是：

$$
\frac{n \cdot (n-1) \cdot \cdot \cdot(n-r+1)}{r!} = \frac{n!}{(n-r)!r!}
$$

### 组合的符号和术语
::: {#def-3_5_001}
定义 $\left(\begin{array}{cc} n \\ r  \end{array}\right), \forall r \le n$ 为一次性从 $n$ 个物品中选择 $r$ 个物品的组合数量，则：

$$
\left(\begin{array}{cc} 
n \\ 
r  
\end{array}\right) = \frac{n!}{(n-r)!r!}
$$
:::

$\left(\begin{array}{cc} n \\ r  \end{array}\right)$ 表示在不考虑抽取顺序的情况下，从 $n$ 个元素中选择 $r$ 个元素的不同组合数。例如：

* 从 8 个人中选择 2 个人的方式：$\left(\begin{array}{cc} 8 \\ 2  \end{array}\right) = \frac{8 \cdot 7}{2 \cdot 1}=28$。
* 从 10 个人中选择 2 个人的方式：$\left(\begin{array}{cc} 10 \\ 2  \end{array}\right) = \frac{10 \cdot 9}{2 \cdot 1}=45$。

特别注意的是，$\left(\begin{array}{cc} n \\ 0  \end{array}\right)$ = $\left(\begin{array}{cc} n \\ n  \end{array}\right)$ = 1。

::: {#exr-3_5_d}
要从 6 名男性和 9 名女性中随机选取 5 人组成一个委员会。如果是随机选择的话，这个委员会由 3 名男性和 2 名女性组成的概率是多少？
:::

::: {#sol-3_5_d}
随机选取意味着 $\left(\begin{array}{cc} 15 \\ 5  \end{array}\right)$ 种可能的组合数中的任何一组被选取的可能性都是一致的。因为，3 名男性的选择方式有 $\left(\begin{array}{cc} 6 \\ 3  \end{array}\right)$ 种，2 名女性的选择方式有 $\left(\begin{array}{cc} 9 \\ 2  \end{array}\right)$ 种，根据 **基本计数原理**，委员会由 3 名男性和 2 名女性组成的概率为：

$$
\frac{\left(\begin{array}{cc} 6 \\ 3  \end{array}\right) \cdot \left(\begin{array}{cc} 9 \\ 2  \end{array}\right)}{\left(\begin{array}{cc} 15 \\ 5  \end{array}\right)} = \frac{240}{1001}
$$
:::

::: {#exr-3_5_e}
从一个具有 $n$ 个物品的集合中随机抽取大小为 $k$ 的样本，则某个给定的物品被抽取到的概率是多少？ 
:::

::: {#sol-3_5_e}
如果某个给定的物品位于 $k$ 中，则意味着 $k$ 由给定的 1 个物品和剩余的 $k-1$ 个物品（从 $n-1$ 个物品中抽取的）组成，则 $k$ 个物品的抽取方式为 $\left(\begin{array}{cc}  {n-1} \\ {k-1}  \end{array}\right)$。另外，从 $n$ 个物品中抽取 $k$ 个物品的方式总共有 $\left(\begin{array}{cc}  n \\ k  \end{array}\right)$。因此，从 $n$ 个物品的集合中随机抽取大小为 $k$ 的样本，则某个给定的物品被抽取到的概率为：

$$
\frac{\left(\begin{array}{cc}  {n-1} \\ {k-1}  \end{array}\right)}{\left(\begin{array}{cc}  n \\ k  \end{array}\right)} = \frac{\frac{(n-1)!}{(n-k)!(k-1)!}}{\frac{n!}{(n-k)!k!}} = \frac{k}{n}
$$
:::

::: {#exr-3_5_f}
一个篮球队由 6 名黑人球员和 6 名白人球员组成。需要对这些球员随机地两两配对，以确定他们的室友。如果配对是随机进行的，那么黑人球员与白人球员不是室友的概率是多少？
:::

::: {#sol-3_5_f}
首先，我们设想对这 6 对球员进行编号，分别是：第 1 对，第 2 对，……。对于第 1 对 球员，有 $\left(\begin{array}{cc}  12 \\ 2  \end{array}\right)$ 种配对方式。然后，第 2 对球员则有 $\left(\begin{array}{cc}  10 \\ 2  \end{array}\right)$ 种配对方式。对于第 3 对球员，则有 $\left(\begin{array}{cc}  8 \\ 2  \end{array}\right)$ 种配对方式，……因此，根据 **基本计数原理的泛化规则**，这 6 对球员的配对方式总共有 $\left(\begin{array}{cc}  12 \\ 2  \end{array}\right) \left(\begin{array}{cc}  10 \\ 2  \end{array}\right) \left(\begin{array}{cc}  8 \\  2 \end{array}\right) \left(\begin{array}{cc}  6 \\ 2  \end{array}\right) \left(\begin{array}{cc}  4 \\ 2  \end{array}\right) \left(\begin{array}{cc}  2 \\ 2  \end{array}\right) = \frac{12!}{(2!)^6}$。所以，不考虑分组序号的情况下，配对方式总共有 $\frac{12!}{2^6 \cdot 6!}$。

同理，6 名黑（白）人球员之间配对的方式均有 $\frac{ 6! }{ 2^3 \cdot 3! }$。因此，黑人球员与白人球员不是室友的概率为：$\frac{ (\frac{ 6! }{ 2^3 \cdot 3! })^2 }{ \frac{ 12! }{ 2^6 \cdot 6! } } = \frac{ 5 }{ 231 } = 0.0216$
:::

::: {#exr-3_5_g}
房间里有 $n$ 个人，则他们的生日不在同一天的概率是多少？如果这个概率要低于 50%，那么 $n$ 至少是多少？
:::

::: {#sol-3_5_g}
在不考虑闰年的情况下，每个人的生日可以为一年 365 天中的任何一天，所以 $n$ 个人的生日的可能性为 $365^n$。如果他们的生日均不在同一天，则其可能性为 $365 \cdot 364 \cdot \cdot \cdot (365 - n + 1)$。这是因为第一个人的生日可以是 365 天中的任何一天，第二个人的生日可以是剩下的 364 天中的任何一天，第三个人的生日可以是剩下的 363 天中的任何一天，以此类推。因此，他们的生日不在同一天的概率为 $\frac{ 365 \cdot 364 \cdot \cdot \cdot (365 - n + 1) }{ (365)^n }$。

令人惊讶的事实是，当 $n \ge 23$ 时，这个概率小于 50%。也就是说，如果房间里至少有 23 个人的时候，那么他们之中至少有两个人的生日相同的概率将超过 50%。对这个结果，许多人最初会感到惊讶，因为与 365（一年的天数）相比，23 这个数字显得如此之小。然而，每两个人其生日相同的概率是 $\frac{ 365 }{ (365)^2 }=\frac{ 1 }{ 365 }$。而在一个由 23 人组成的群体中，有 $\left(\begin{array}{cc}  23 \\ 2  \end{array}\right) = 253$ 对不同的分组。从这个角度来看，这个结果就不再那么令人惊讶了。
:::