## 简介 {#sec-16_1}

近年来，数据的激增以及快速计算能力的提升，催生了多种估算概率的技术，这些技术较少依赖于假设特定的数据模型，而更多地利用海量历史数据。这类技术通常被称为**机器学习**（*machine learning*）。本章将介绍几种流行的机器学习技术。

在 @sec-16_2 中，我们引入了一个原型模型：在拥有大量历史数据的情况下，估算某架特定的跨国航班晚点到达目的地的概率。我们假设任何单次航班都可以由一个值组成的“特征向量”来描述，该向量的分量在性质上是定性描述性的。

随后的章节将介绍估算此类概率的方法。在 @sec-16_3 中，我们引入了**朴素贝叶斯**（*naive Bayes*）方法，该方法尝试通过将晚点概率写为给定航班特征下的条件概率来对其进行估算。接着，利用贝叶斯定理，在满足关于特征向量分量独立性的特定假设时，我们可以得到该概率的表达式，且其中的各部分均可被估算。在 @sec-16_3_1 中，我们给出了一种改进的朴素贝叶斯方法，当独立性假设明显不成立时，该方法可以提高估算精度。

在 @sec-16_4 中，我们引入了“最近邻”规则。这些规则利用历史数据集中那些特征向量与目标航班特征向量接近的数据，来估算目标航班晚点的概率。要使用此类规则，首先要为每一个历史数据定义其特征向量与目标航班特征向量之间的距离。然后，该规则会充分利用那些距离最小的历史数据。例如，其中一种规则选取 $k$ 个与目标航班最接近的历史数据值（即 $k$ 个最近邻），并将这 $k$ 架航班中晚点航班所占的比例作为晚点概率的估计值。@sec-16_4_1 介绍了最近邻规则的变体，这些变体利用了所有的历史数据值，并给予那些特征向量与目标航班最接近的数据更多的“权重”。最近邻规则的一个明显弱点是，在确定特征向量之间的距离时，给予了向量的所有分量相同的权重，而没有考虑到某些分量可能比其他分量重要得多。@sec-16_4_2 通过允许给予分量的权重取决于该分量本身，从而解决了这一问题。

在 @sec-16_5 中，我们讨论了如何评估所介绍的这些程序在确定航班晚点概率方面的效果。

到目前为止，我们一直假设特征向量的元素在性质上是定性的，而在 @sec-16_6 中，我们假设它们是定量的。假设一个实验的结果要么是成功要么是失败，@sec-16_6_1 和 @sec-16_6_2 分别介绍了最近邻规则和逻辑回归方法，用于估算具有特征向量 $(x_1, \dots, x_n)$ 的实验成功的概率。

在 @sec-16_7 中，我们考虑了一个不同类型的问题。该通用模型的一个原型示例是：假设有两种可以开出的不同药物，每种药物 $i$ 的使用都会导致治愈（即成功），概率为 $p_i$ ($i = 1, 2$)，其中 $p_1$ 和 $p_2$ 是未知的。假设开出某种特定药物的结果（治愈与否）可以立即获知，问题在于如何根据之前所有选择的结果，顺序地决定为接下来的每个病人开出哪种药物。这类问题被称为**多臂老虎机问题**（*bandit problems*）。我们提出了一种随机化决策程序；即在每个阶段，它指定一个概率 $\alpha$，并要求决策者以概率 $\alpha$ 使用药物 1，以概率 $1 - \alpha$ 使用药物 2。
