## 晚点航班概率 {#sec-16_2}

假设我们有兴趣估算一架从加利福尼亚飞往纽约市的直达航班晚点的概率（这里“晚点”定义为比预定到达时间晚点至少三十分钟）。在没有任何关于该航班的额外信息时，我们可能会通过查阅所有此类航班的历史数据，并使用其中晚点航班的比例作为估计值。然而，我们通常对某次特定的航班更感兴趣。因此，让我们根据以下变量的值对每次航班进行分类：

$X_1$：航空公司
$X_2$：起飞城市
$X_3$：到达机场
$X_4$：星期几
$X_5$：起飞时间
$X_6$：飞机的尺寸
$X_7$：天气状况

假设这些变量的可能取值为：

$X_1$：1 = 美国航空（*American*），2 = 达美航空（*Delta*），3 = 联合航空（*United*），4 = 捷蓝航空（*Jet Blue*）；
$X_2$：1 = 洛杉矶，2 = 旧金山，3 = 圣地亚哥，4 = 奥克兰；
$X_3$：1 = 纽约肯尼迪机场，2 = 纽约拉瓜迪亚机场，3 = 纽瓦克机场；
$X_4$：1, ..., 7，其中 1 = 星期一，2 = 星期二，依此类推；
$X_5$：1 = 清晨，2 = 上午，3 = 下午，4 = 傍晚，5 = 傍晚时分，6 = 深夜；
$X_6$：1 = 小型，2 = 中型，3 = 大型；
$X_7$：1 = 优于平均，2 = 平均，3 = 有暴风雨。

因此，例如，一架在周三傍晚从奥克兰飞往纽瓦克的联合航空大型飞机，且天气状况优于平均水平，其特征向量将被编码为 $(X_1, X_2, X_3, X_4, X_5, X_6, X_7) = (3, 4, 3, 3, 5, 3, 1)$。我们使用向量 $(3, 4, 3, 3, 5, 3, 1)$ 来标识这样一次航班，并称其为该航班的**特征向量**（*characterizing vector*）。我们如何估算这样一次航班晚点的概率呢？当然，一种方法是查找历史数据库中所有具有相同特征向量的航班，并以这些航班中晚点的比例来估算晚点概率。然而，由于可能出现的航班数量非常多（根据计数的基本原理，共有 $4 \cdot 4 \cdot 3 \cdot 7 \cdot 6 \cdot 3 \cdot 3 = 18,144$ 种可能），即使拥有庞大的历史数据集，也可能没有多少次完全相同类型的航班，因此此类估计可能不太准确。在接下来的章节中，我们将给出解决上述问题的几种不同方法。
