## 朴素贝叶斯方法 {#sec-16_3}

假设我们想要估算特征向量为 $X_1 = x_1, X_2 = x_2, \dots, X_7 = x_7$ 的航班将要晚点的概率。令 $L$ 为航班晚点的事件，我们将上述概率写为条件概率 $P(L | X_1 = x_1, \dots, X_7 = x_7)$。现在，根据贝叶斯定理，我们有：

$$
\begin{align}
P(L | X_1 = x_1, \dots, X_7 = x_7) &= \frac{P(L, X_1 = x_1, \dots, X_7 = x_7)}{P(X_1 = x_1, \dots, X_7 = x_7)} \\
&= \frac{P(L) P(X_1 = x_1, \dots, X_7 = x_7 | L)}{P(X_1 = x_1, \dots, X_7 = x_7)}
\end{align}
$$ {#eq-16_3_1}

因为 $P(L)$ 是随机选择的航班晚点的概率，它的自然估计值是我们的历史数据库中晚点航班所占的比例，这也是我们将要使用的估计值。然而，$P(X_1 = x_1, \dots, X_7 = x_7)$ 的自然估计量，即数据库中具有特征向量 $(x_1, \dots, x_7)$ 的航班比例，通常是不准确的，因为历史航班中具有该特定特征向量的航班数量有限。同样地，$P(X_1 = x_1, \dots, X_7 = x_7 | L)$ 的相应自然估计量（即数据库中特征向量为 $(x_1, \dots, x_7)$ 的晚点航班比例）也会面临同样的困难。为了克服这一困难，我们将假定 $X_1, X_2, \dots, X_7$ 是独立的随机变量，并且当我们已知航班晚点时，它们仍然保持独立（但不必具有相同的概率）。现在，在此假设下，我们将得到：

$$
P(X_1 = x_1, \dots, X_7 = x_7) = P(X_1 = x_1) P(X_2 = x_2) \dots P(X_7 = x_7)
$$

我们可以通过数据库中特征向量具有 $X_i = x_i$ 的所有航班的比例来估计 $P(X_i = x_i)$。例如，我们会通过数据库中由联合航空（*United*）承运的所有航班的比例来估计 $P(X_1 = 3)$。此外，因为我们也假设当我们已知航班晚点时 $X_1, X_2, \dots, X_7$ 仍然保持独立，所以我们有：

$$
P(X_1 = x_1, \dots, X_7 = x_7 | L) = P(X_1 = x_1 | L) P(X_2 = x_2 | L) \dots P(X_7 = x_7 | L)
$$

因此，我们可以通过所有晚点航班中特征向量具有 $X_i = x_i$ 的航班比例来估计 $P(X_i = x_i | L)$。因此，如果 $f(L)$ 是数据库中到达晚点的航班比例；$f_i(x)$ 是数据库中特征向量具有 $X_i = x$ 的航班比例；而 $f_i(x|L)$ 是数据库中特征向量具有 $X_i = x$ 的晚点航班比例，那么我们对下式的估计：

$$
P(L | X_1 = x_1, \dots, X_7 = x_7) = \frac{P(L) P(X_1 = x_1, \dots, X_7 = x_7 | L)}{P(X_1 = x_1, \dots, X_7 = x_7)}
$$

被称为**朴素贝叶斯估计量**（*naive Bayes estimator*），即：

$$
\frac{f(L) f_1(x_1 | L) f_2(x_2 | L) \dots f_7(x_7 | L)}{f_1(x_1) f_2(x_2) \dots f_7(x_7)}
$$

::: {#exm-16_3_1}
@tbl-16_1 给出了 79 架从单一机场起飞的航班的历史晚点数据。假设这些航班由向量 $(x_1, x_2, x_3, x_4)$ 描述，其中 $x_1$ 的可能取值为 1 和 2，$x_2$ 的可能取值为 1 和 2，$x_3$ 的可能取值为 1, 2 和 3，而 $x_4$ 的可能取值为 1 和 2。使用朴素贝叶斯方法估算特征向量为 $(2, 1, 2, 2)$ 的航班将要晚点的概率。

| 航班向量 | 此类航班数量 | 晚点数量 |
| :---: | :---: | :---: |
| (1,1,1,1) | 2 | 1 |
| (1,1,1,2) | 2 | 0 |
| (1,1,2,1) | 2 | 0 |
| (1,1,2,2) | 1 | 0 |
| (1,1,3,1) | 3 | 1 |
| (1,1,3,2) | 3 | 0 |
| (1,2,1,1) | 4 | 1 |
| (1,2,1,2) | 3 | 1 |
| (1,2,2,1) | 5 | 2 |
| (1,2,2,2) | 3 | 1 |
| (1,2,3,1) | 3 | 1 |
| (1,2,3,2) | 4 | 2 |
| (2,1,1,1) | 4 | 2 |
| (2,1,1,2) | 3 | 1 |
| (2,1,2,1) | 5 | 2 |
| (2,1,2,2) | 4 | 1 |
| (2,1,3,1) | 3 | 1 |
| (2,1,3,2) | 2 | 0 |
| (2,2,1,1) | 3 | 1 |
| (2,2,1,2) | 4 | 1 |
| (2,2,2,1) | 5 | 2 |
| (2,2,2,2) | 5 | 3 |
| (2,2,3,1) | 3 | 1 |
| (2,2,3,2) | 3 | 0 |

: 历史航班数据 {#tbl-16_1}

**解答：**
由于这 79 架航班中有 25 架晚点，因此 $P(L)$ 的估计值为 $f(L) = 25/79$。
因为 79 架航班中有 44 架的 $x_1 = 2$，所以 $P(X_1 = 2)$ 的估计值为 $f_1(2) = 44/79$。
因为 79 架航班中有 34 架的 $x_2 = 1$，所以 $P(X_2 = 1)$ 的估计值为 $f_2(1) = 34/79$。
因为 79 架航班中有 30 架的 $x_3 = 2$，所以 $P(X_3 = 2)$ 的估计值为 $f_3(2) = 30/79$。
因为 79 架航班中有 37 架的 $x_4 = 2$，所以 $P(X_4 = 2)$ 的估计值为 $f_4(2) = 37/79$。
因为 25 架晚点航班中有 15 架的 $x_1 = 2$，所以 $P(X_1 = 2 | L)$ 的估计值为 $f_1(2 | L) = 15/25$。
因为 25 架晚点航班中有 9 架的 $x_2 = 1$，所以 $P(X_2 = 1 | L)$ 的估计值为 $f_2(1 | L) = 9/25$。
因为 25 架晚点航班中有 12 架的 $x_3 = 2$，所以 $P(X_3 = 2 | L)$ 的估计值为 $f_3(2 | L) = 12/25$。
因为 25 架晚点航班中有 10 架的 $x_4 = 2$，所以 $P(X_4 = 2 | L)$ 的估计值为 $f_4(2 | L) = 10/25$。

特征向量为 $(2, 1, 2, 2)$ 的航班的朴素贝叶斯估计晚点概率为：

$$
\frac{f(L) f_1(2 | L) f_2(1 | L) f_3(2 | L) f_4(2 | L)}{f_1(2) f_2(1) f_3(2) f_4(2)} = \frac{25 \cdot 15 \cdot 9 \cdot 12 \cdot 10 \cdot 79^4}{79 \cdot 25^4 \cdot 44 \cdot 34 \cdot 30 \cdot 37} = .3078
$$

将此估计值与 $1/4 = .25$（即特征向量为 $(2, 1, 2, 2)$ 且晚点的航班比例）进行比较，或与 $25/79 = .3165$（即所有航班中晚点的比例）进行比较，是很有趣的。 $\blacksquare$
:::

### 朴素贝叶斯方法的一种变体 {#sec-16_3_1}

如前一节所示，我们有兴趣使用历史数据来估算由向量 $(x_1, \dots, x_n)$ 表征的情况将导致某种结果的概率。正如所指出的，朴素贝叶斯方法通过假设 $X_1, \dots, X_n$ 是独立的来估算 $P(X_1 = x_1, \dots, X_n = x_n)$，因此有：

$$
P(X_1 = x_1, \dots, X_n = x_n) = P(X_1 = x_1) \dots P(X_n = x_n)
$$

然后使用历史数据中第 $i$ 个分量取值为 $x_i$ 的比例作为 $P(X_i = x_i)$ 的估计值 ($i = 1, \dots, n$)。然而，在许多例子中，$X_1, \dots, X_n$ 独立的假设显然是不可行的。例如，假设患有克罗恩病（*Crohn's disease*）类似身体症状的患者接受了一组 $n$ 次医疗测试，测试 $i$ 的结果（记为 $X_i$）如果对该疾病呈阳性则为 1，如果是阴性则为 0。现在，假设测试具有一定的有效性，那么 $X_i = 1$ 会使得患者患有该疾病的可能性增加，从而使得 $X_j = 1$ 的可能性也增加。因此，$X_1, \dots, X_n$（即测试结果）显然不是独立的。然而，虽然它们不独立，但如果我们知道该患者是否患有该疾病，那么假设它们是独立的可能是合理的。也就是说，在给定患者是否患有该疾病的条件下，可以合理地假设测试结果是独立的。假设如此，如果我们令 $D$ 为患者患病的事件，我们可以利用等式：

$$
\begin{align}
P(X_1 = x_1, \dots, X_n = x_n) &= P(X_1 = x_1, \dots, X_n = x_n | D) P(D) \\
&\quad + P(X_1 = x_1, \dots, X_n = x_n | D^c) (1 - P(D))
\end{align}
$$

假设当我们知道患者是否患病时，$X_1, \dots, X_n$ 是独立的，则有：

$$
P(X_1 = x_1, \dots, X_n = x_n | D) = P(X_1 = x_1 | D) \dots P(X_n = x_n | D)
$$
$$
P(X_1 = x_1, \dots, X_n = x_n | D^c) = P(X_1 = x_1 | D^c) \dots P(X_n = x_n | D^c)
$$

现在，我们可以通过考虑历史数据库中患有该疾病的患者，并让估计值作为这些患者中测试 $i$ 值为 $x_i$ 的比例，来估计 $P(X_i = x_i | D)$。类似地，我们可以通过考虑历史数据库中未患有该疾病的患者，并让估计值作为这些患者中测试 $i$ 值为 $x_i$ 的比例，来估计 $P(X_i = x_i | D^c)$。此外，$P(D)$ 将通过历史数据库中患有该疾病的患者比例来估算，而 $P(D^c)$ 则通过未患有该疾病的比例来估算。

::: {#exm-16_3_2}
向每位表现出某种医疗状况症状的患者提供一系列三次测试，三次测试的结果由向量 $(x_1, x_2, x_3)$ 表征，其中 $x_1$ 的可能取值为 1 和 2，$x_2$ 的可能取值为 1 和 2，而 $x_3$ 的可能取值为 1, 2 和 3。历史数据涉及 68 名接受过测试的患者，给出了每名患者的测试结果以及最终是否被发现患有该病症。数据总结在 @tbl-16_2 中。

| 特征向量 | 患者数量 | 患病人数 | 未患病人数 |
| :---: | :---: | :---: | :---: |
| (1,1,1) | 4 | 1 | 3 |
| (1,1,2) | 3 | 0 | 3 |
| (1,1,3) | 5 | 1 | 4 |
| (1,2,1) | 6 | 1 | 5 |
| (1,2,2) | 7 | 2 | 5 |
| (1,2,3) | 5 | 3 | 2 |
| (2,1,1) | 6 | 3 | 3 |
| (2,1,2) | 7 | 2 | 5 |
| (2,1,3) | 5 | 1 | 4 |
| (2,2,1) | 6 | 2 | 4 |
| (2,2,2) | 9 | 4 | 5 |
| (2,2,3) | 5 | 1 | 4 |

: 医疗测试历史数据 {#tbl-16_2}

例如，历史数据库详述的 68 名患者中，有 7 名具有特征向量 $(2, 1, 2)$，其中 2 名患有该病症。使用上述方法估算特征向量为 $(2, 1, 2)$ 的新患者患有该病症的概率。

**解答：**
令 $\mathbf{X} = (X_1, X_2, X_3)$。那么，令 $C$ 为患者患有该医疗状况的事件，我们从下式开始：

$$
\begin{align}
P(C | \mathbf{X} = (2, 1, 2)) &= \frac{P(C, \mathbf{X} = (2, 1, 2))}{P(\mathbf{X} = (2, 1, 2))} \\
&= \frac{P(C) P(\mathbf{X} = (2, 1, 2) | C)}{P(\mathbf{X} = (2, 1, 2))} \\
&= \frac{P(C) P(\mathbf{X} = (2, 1, 2) | C)}{P(\mathbf{X} = (2, 1, 2) | C) P(C) + P(\mathbf{X} = (2, 1, 2) | C^c) P(C^c)}
\end{align}
$$

现在，如果我们假设当我们知道患者是否患病时 $X_1, X_2, X_3$ 变得独立，那么我们有：

$$
P(\mathbf{X} = (2, 1, 2) | C) = P(X_1 = 2 | C) P(X_2 = 1 | C) P(X_3 = 2 | C)
$$
$$
P(\mathbf{X} = (2, 1, 2) | C^c) = P(X_1 = 2 | C^c) P(X_2 = 1 | C^c) P(X_3 = 2 | C^c)
$$

我们现在准备估计测试向量为 $(2, 1, 2)$ 的患者患病的概率。
因为 68 名患者中有 21 名患有该病症，所以 $P(C)$ 的估计值为 $21/68$。
在患有该病症的 21 名患者中：
13 名的 $x_1 = 2$，所以 $P(X_1 = 2 | C)$ 的估计值为 $13/21$。
8 名的 $x_2 = 1$，所以 $P(X_2 = 1 | C)$ 的估计值为 $8/21$。
8 名的 $x_3 = 2$，所以 $P(X_3 = 2 | C)$ 的估计值为 $8/21$。

因为 68 名患者中有 47 名没有患有该病症，所以 $P(C^c)$ 的估计值为 $47/68$。
在没有患有该病症的 47 名患者中：
25 名的 $x_1 = 2$，所以 $P(X_1 = 2 | C^c)$ 的估计值为 $25/47$。
22 名的 $x_2 = 1$，所以 $P(X_2 = 1 | C^c)$ 的估计值为 $22/47$。
18 名的 $x_3 = 2$，所以 $P(X_3 = 2 | C^c)$ 的估计值为 $18/47$。

$P(\mathbf{X} = (2, 1, 2) | C)$ 的估计值因此为 $\frac{13 \cdot 8 \cdot 8}{21^3} = .08984$。
$P(\mathbf{X} = (2, 1, 2) | C^c)$ 的估计值因此为 $\frac{25 \cdot 22 \cdot 18}{47^3} = .09535$。
$P(C | \mathbf{X} = (2, 1, 2))$ 的估计值为：

$$
\frac{(21/68)(.08984)}{(21/68)(.08984) + (47/68)(.09535)} = .2963
$$

也就是说，我们对具有特征向量 $(2, 1, 2)$ 的患者患有该病症的概率的估计值为 .2963。 $\blacksquare$
:::

**注：** 上述变体利用了**条件独立**（*conditional independence*）的概念，当不需要相互独立的随机变量 $X_1, \dots, X_n$ 在已知一些额外信息的情况下变得独立时，就会产生条件独立。例如，假设有 2 枚硬币，硬币 1 在每次抛掷中出现正面的概率为 .8，硬币 2 出现正面的概率为 .3。假设这些硬币中有一枚是以同样的可能性被选中的。现在假设所选的硬币被抛掷 8 次。令 $X_i = 1$ 如果第 $i$ 次抛硬币结果为正面，令 $X_i = 0$ 如果第 $i$ 次抛硬币结果为反面。现在，如果我们知道前 5 次抛掷的结果都是正面，那么我们就非常有可能使用的是硬币 1，这使得下一次抛掷也出现正面的可能性更大（相对于我们没有关于前 5 次抛掷的信息时）。因此，$X_1, \dots, X_8$ 不是独立的。然而，如果我们知道选择了哪枚硬币，那么关于之前抛掷的信息对于确定即将到来的抛掷结果将没有用处。也就是说，如果我们令 $Y$ 为所选的硬币，那么知道 $Y = 1$ 还是 $Y = 2$ 都会使得 $X_1, \dots, X_n$ 独立。在这种情况下，我们说 $X_1, \dots, X_n$ 在给定 $Y$ 的值时是**条件独立**的。这意味着，例如：

$$
\begin{align}
P(X_1 = 1, X_2 = 1, X_3 = 1 | Y = 1) &= P(X_1 = 1 | Y = 1) P(X_2 = 1 | Y = 1) P(X_3 = 1 | Y = 1) \\
&= (.8)(.8)(.8) = .512
\end{align}
$$ $\blacksquare$
