## 基于距离的估计量：$k$-最近邻规则 {#sec-16_4}

让我们定义两个特征向量 $\mathbf{x} = (x_1, x_2, \dots, x_7)$ 和 $\mathbf{y} = (y_1, y_2, \dots, y_7)$ 之间的距离（记为 $d$）：

$$
d(\mathbf{x}, \mathbf{y}) = \sum_{i=1}^7 I\{x_i \neq y_i\}
$$

其中

$$
I\{x_i \neq y_i\} = 
\begin{cases} 
0, & \text{若 } x_i = y_i \\
1, & \text{若 } x_i \neq y_i 
\end{cases}
$$

也就是说，两个特征向量之间的距离是它们取值不同的坐标数量。基于距离的航班晚点概率估计量（针对特征向量为 $(x_1, x_2, \dots, x_7)$ 的航班）是基于这样一种假设：距离较小的两个特征向量应该具有相似的晚点概率。**$k$-最近邻规则**（*$k$-nearest neighbor rule*）是一种流行的估计方法。要使用它，首先需要确定 $(x_1, x_2, \dots, x_7)$ 与历史数据库中所有特征向量之间的距离。该规则会选出与 $(x_1, x_2, \dots, x_7)$ 距离最小的 $k$ 个历史向量，然后使用这 $k$ 架航班中晚点航班所占的比例，作为该特征向量为 $(x_1, x_2, \dots, x_7)$ 的航班晚点概率的估计值。另一种基于距离的估计方法是，选择历史数据库中所有位于 $(x_1, x_2, \dots, x_7)$ 固定距离之内的向量，然后使用这些航班中晚点航班的比例作为该特征向量为 $(x_1, x_2, \dots, x_7)$ 的航班晚点概率的估计值。

::: {#exm-16_4_1}
考虑 @exm-16_3_1 中的数据。使用固定距离 1，与 $(2, 1, 2, 2)$ 距离至多为 1 的特征向量有：$(2, 1, 2, 2)$、$(1, 1, 2, 2)$、$(2, 2, 2, 2)$、$(2, 1, 1, 2)$、$(2, 1, 3, 2)$、$(2, 1, 2, 1)$。由于数据集中具有这些特征向量之一的 20 架航班中有 7 架晚点，因此对 $(2, 1, 2, 2)$ 航班晚点概率的估计值为 $7/20 = .35$。 $\blacksquare$
:::

### 距离加权方法 {#sec-16_4_1}

另一种仅使用部分历史数据值进行估计的方法是使用全部数据，但对于那些特征向量最接近目标向量的数据值给予更大的权重。假设历史数据库中有 $N$ 个特征向量，我们想利用它们来估算特征向量为 $(x_1, x_2, \dots, x_7)$ 的航班晚点的概率。令 $d_j$ 为历史数据集中第 $j$ 个特征向量与 $(x_1, x_2, \dots, x_7)$ 之间的距离（对于 $j = 1, \dots, N$）。同时，令 $w_1, \dots, w_N$ 定义为：

$$
w_j = \frac{1}{1 + d_j}, \quad j = 1, \dots, N
$$

数量 $w_j$ 是我们在估算特征向量为 $(x_1, x_2, \dots, x_7)$ 的航班晚点概率时，给予第 $j$ 个历史数据值的权重。因此，一个特征向量与目标向量相同的历史数据值被赋予权重 1，一个向量距离为 1 的数据值被赋予权重 1/2，依此类推。估算出的特征向量为 $(x_1, x_2, \dots, x_7)$ 的航班晚点概率的最终结果，是所有晚点航班的权重之和除以所有航班的权重之和。具体而言，定义 $I_j$ 在第 $j$ 架历史航班晚点时等于 1，不晚点时等于 0，我们估算所需的概率为：

$$
\frac{\sum_{j=1}^N I_j w_j}{\sum_{j=1}^N w_j}
$$ {#eq-16_4_1}

::: {#exm-16_4_2}
@tbl-16_3 给出了 @exm-16_3_1 中的历史数据，以及每个向量相对于 $(2, 1, 2, 2)$ 的距离和相应的权重。利用这些数据获得 $(2, 1, 2, 2)$ 航班晚点概率的距离加权估计值。

| 航班向量 | 此类航班数量 | 晚点数量 | (2122) 距离 | 权重 |
| :---: | :---: | :---: | :---: | :---: |
| (1,1,1,1) | 2 | 1 | 3 | 1/4 |
| (1,1,1,2) | 2 | 0 | 2 | 1/3 |
| (1,1,2,1) | 2 | 0 | 2 | 1/3 |
| (1,1,2,2) | 1 | 0 | 1 | 1/2 |
| (1,1,3,1) | 3 | 1 | 3 | 1/4 |
| (1,1,3,2) | 3 | 0 | 2 | 1/3 |
| (1,2,1,1) | 4 | 1 | 4 | 1/5 |
| (1,2,1,2) | 3 | 1 | 3 | 1/4 |
| (1,2,2,1) | 5 | 2 | 3 | 1/4 |
| (1,2,2,2) | 3 | 1 | 2 | 1/3 |
| (1,2,3,1) | 3 | 1 | 4 | 1/5 |
| (1,2,3,2) | 4 | 2 | 3 | 1/4 |
| (2,1,1,1) | 4 | 2 | 2 | 1/3 |
| (2,1,1,2) | 3 | 1 | 1 | 1/2 |
| (2,1,2,1) | 5 | 2 | 1 | 1/2 |
| (2,1,2,2) | 4 | 1 | 0 | 1 |
| (2,1,3,1) | 3 | 1 | 2 | 1/3 |
| (2,1,3,2) | 2 | 0 | 1 | 1/2 |
| (2,2,1,1) | 3 | 1 | 3 | 1/4 |
| (2,2,1,2) | 4 | 1 | 2 | 1/3 |
| (2,2,2,1) | 5 | 2 | 2 | 1/3 |
| (2,2,2,2) | 5 | 3 | 1 | 1/2 |
| (2,2,3,1) | 3 | 1 | 3 | 1/4 |
| (2,2,3,2) | 3 | 0 | 2 | 1/3 |

: 历史航班数据（含权重） {#tbl-16_3}

**解答：**
在 79 架航班中，7 架权重为 1/5，23 架权重为 1/4，29 架权重为 1/3，16 架权重为 1/2，4 架权重为 1。所有 79 架航班的权重之和为 $7/5 + 23/4 + 29/3 + 16/2 + 4 = 28.8167$。另一方面，在 25 架晚点航班中，2 架权重为 1/5，9 架权重为 1/4，7 架权重为 1/3，6 架权重为 1/2，1 架权重为 1。因此，晚点航班的权重之和为 $2/5 + 9/4 + 7/3 + 6/2 + 1 = 8.9833$。由此得出特征向量为 $(2, 1, 2, 2)$ 的航班晚点的估计概率为 $8.9833/28.8167 = .3117$。 $\blacksquare$
:::

还有其他权衡历史数据结果的方法。例如，可以选择一个介于 0 和 1 之间的数字 $\beta$，然后对于与 $(x_1, \dots, x_7)$ 距离为 $d$ 的历史数据赋予权重 $\beta^d$；或者我们可以根据历史数据向量与 $(x_1, \dots, x_7)$ 的接近程度对其进行排序，然后对第 $j$ 个最近邻赋予权重 $\beta^j$。

### 分量加权距离 {#sec-16_4_2}

假设我们想估算特征向量为 $(x_1, \dots, x_7)$ 的航班晚点的概率。令 $X_i$ 为随机选择的历史特征向量的第 $i$ 个分量值。现在，如果无论 $X_i = x_i$ 是否成立，航班晚点的概率变化都不大，那么在尝试评估向量为 $(x_1, \dots, x_7)$ 的航班晚点概率时，似乎不需要给分量 $i$ 赋予太多的权重。令 $p_L(x_i)$ 为特征向量具有 $X_i = x_i$ 的历史航班中晚点航班的比例，而 $p_L(\bar{x}_i)$ 为特征向量中 $X_i \neq x_i$ 的历史航班中晚点航班的比例，令 $a_i = |p_L(x_i) - p_L(\bar{x}_i)|$ 为这两个比例之间的绝对差。因此，$a_i$ 是对 $X_i = x_i$ 这一事实对航班晚点概率产生影响的一个估计。考虑到这一点，我们可以定义待考查航班向量 $\mathbf{x} = (x_1, \dots, x_7)$ 与历史向量 $\mathbf{y} = (y_1, \dots, y_7)$ 之间的**分量加权距离**（*component weighted distance*）为：

$$
d(\mathbf{x}, \mathbf{y}) = \sum_{i=1}^7 a_i I\{x_i \neq y_i\}
$$
