## 评估方法 {#sec-16_5}

我们现在讨论如何评估上述所提出的各种确定航班晚点概率的方法。为了评估任何一种方法的价值，我们从历史数据库开始，并从中随机选择一个数据子集，称为**测试集**（*testing set*），该子集将用于评估该程序。例如，假设我们有 3000 架航班的记录。我们应当从中随机选择一个大小为 1000 的子集构成测试集，然后看看每个程序在使用剩余 2000 架航班的数据作为历史数据来估算测试集中航班晚点概率时的表现。这一过程的结果将是 1000 个测试集航班晚点的估计概率，以及关于其中每一个航班是否实际晚点的信息。也就是说，结果将是 1000 个对 $(p_i, l_i)$，$i = 1, \dots, 1000$。其中 $p_i$ 是对测试集中第 $i$ 架航班将要晚点的概率的估计值，而 $l_i$ 如果该航班实际晚点则等于 1，否则等于 0。

为了评估每一个程序，我们给每一对赋予一个“损失”，其中给予对 $(p_i, l_i)$ 的**损失**（*loss*）为：

$$
L =
\begin{cases} 
(1 - p_i)^2, & \text{若 } l_i = 1 \\
p_i^2, & \text{若 } l_i = 0 
\end{cases}
$$

换句话说，损失就是未发生事件（要么不晚点，要么晚点）被赋予的概率的平方。也就是说，如果该方法得出的晚点估计概率等于 $p$，那么如果该飞机晚点，产生的损失为 $(1 - p)^2$，如果没有晚点，产生的损失为 $p^2$。例如，如果估计的晚点概率为 0，那么如果晚点则损失 1，如果不晚点则损失 0；如果估计的晚点概率为 .2，那么如果晚点则损失 .64，如果不晚点则损失 .04；如果估计的晚点概率为 .5，那么无论是否晚点，都损失 .25。无论正在考虑哪种程序，其总损失之和最低的程序就被认为是最好的程序。

要理解上述损失规则的原理，假设某架特定飞机晚点的实际（尽管未知）概率为 $\alpha$，令 $L$ 表示当估计晚点概率为 $p$ 时所产生的损失。因为如果飞机晚点（概率为 $\alpha$），损失为 $(1 - p)^2$；如果飞机不晚点（概率为 $1 - \alpha$），损失为 $p^2$，由此得出期望损失为：

$$
\begin{align}
E[L] &= \alpha(1 - p)^2 + (1 - \alpha)p^2 \\
&= \alpha - 2p\alpha + p^2 \\
&= \alpha + (p - \alpha)^2 - \alpha^2
\end{align}
$$

因此，使 $E[L]$ 尽可能小的估计值 $p$ 是 $p = \alpha$。也就是说，当估计概率等于实际概率 $\alpha$ 时，期望损失最低，且随着估计概率 $p$ 越偏离 $\alpha$，期望损失也随之增加。因此，在 1000 个测试案例中产生最低总损失和的程序，最有可能就是估算晚点概率的最佳程序。

虽然上述方法可用于比较朴素贝叶斯、$k$-最近邻和固定距离方法，以观察哪种方法在特定应用中表现更好，但它仍然没有解决这些方法中是否有任何一个是真正好用的这一问题。检查这一点的一种方法是将这些程序的测试数据产生的平均损失，与一项忽略特征向量并始终通过历史数据集中所有航班中晚点的比例来估计测试案例的晚点概率的策略的平均损失进行比较。为了推导该数值，假设 3000 架航班中晚点的比例为 $\beta$，并假设每架航班的预测晚点概率均为 $\beta$。那么，当航班晚点时损失为 $(1 - \beta)^2$，当不晚点时损失为 $\beta^2$，由于晚点航班的比例为 $\beta$，所以平均损失为：

$$
\beta(1 - \beta)^2 + (1 - \beta)\beta^2 = \beta(1 - \beta)
$$

::: {#exm-16_5_1}
为了了解平均损失比忽略特征向量的策略能减少多少，假设已知特征向量下的历史晚点概率可以被视为独立的连续型均匀分布 $(0, 1)$ 随机变量的值。由于历史航班中有 1/2 会晚点，始终估计晚点概率为 1/2 的规则将具有平均损失 1/4。另一方面，假设我们有一个始终给出正确概率的最佳估计程序。由于当为发生概率为 $p$ 的事件给出估计值 $p$ 时产生的平均损失为 $(1 - p)^2 p + p^2 (1 - p) = p - p^2$，因此该最佳程序的平均损失为 $\int_0^1 (p - p^2) dp = 1/6$。 $\blacksquare$
:::

**注：** 假设有 $N$ 个数据值。当 $N$ 不太大时，我们可以通过观察每个估计器在将其他 $N - 1$ 个值用作历史数据点时对每个单独数据值的处理效果来对其进行评估。
