## 当特征向量是定量的时候 {#sec-16_6}

在本节中，我们再次假设我们有兴趣估算特征向量为 $(x_1, \dots, x_n)$ 的实验成功的概率，但现在我们假设向量 $(x_1, \dots, x_n)$ 的元素在性质上是**定量的** (*quantitative*)，而不是定性的。也就是说，例如，$x_1$ 可以代表个人的体重。在 @sec-16_6_1 中，我们将展示如何使用最近邻规则，在 @sec-16_6_2 中，我们考虑逻辑回归模型。

### 最近邻规则 {#sec-16_6_1}

与定性特征向量的情况一样，在估算具有定量特征向量 $(x_1, \dots, x_n)$ 的实验结果成功的概率时，最近邻规则会对那些特征向量最接近 $(x_1, \dots, x_n)$ 的历史数据给予更多的权重。因此，首先我们需要定义两个特征向量（例如 $\mathbf{x} = (x_1, \dots, x_n)$ 和 $\mathbf{y} = (y_1, \dots, y_n)$）之间的距离。虽然使用欧几里得距离 $\sqrt{\sum_{i=1}^n (x_i - y_i)^2}$ 或 $\sum_{i=1}^n |x_i - y_i|$ 似乎很自然，但我们必须首先考虑到向量的分量指的是不同的实体，因此它们将具有不同的单位，这会影响它们的值。例如，假设我们有兴趣估算某件物品因爆炸而受到严重损坏的概率，且 $x_1$ 指的是该物品与爆炸点之间的距离。如果距离以英尺为单位测量，那么 $|x_1 - y_1|$ 将是如果以码为单位测量时的 3 倍，从而改变了哪些历史特征向量 $(x_1, \dots, x_m)$ 最接近 $(y_1, \dots, y_n)$。为了修正这一异常现象，我们首先对数据进行标准化。令 $m_i$ 和 $s_i$ 分别为所有历史特征向量第 $i$ 个分量值的样本均值和方差（$i = 1, \dots, n$），重新定义所有历史特征向量以及当前正在考虑的向量，使得特征向量 $(x_1, \dots, x_n)$ 变为 $(\frac{x_1 - m_1}{s_1}, \dots, \frac{x_n - m_n}{s_n})$。通过这种方式，我们对历史向量和待考查向量进行了标准化，使得每个分量值的样本均值为 0，样本方差为 1。现在，利用这些标准化后的向量，定义 $\mathbf{x} = (x_1, \dots, x_n)$ 和 $\mathbf{y} = (y_1, \dots, y_n)$ 之间的距离为其欧几里得距离 $\sqrt{\sum_{i=1}^n (x_i - y_i)^2}$。（虽然欧几里得距离最常用，但有时也会使用距离函数 $\sum_{i=1}^n |x_i - y_i|$。）

用于估计 $p(x_1, \dots, x_n)$（即特征向量为 $(x_1, \dots, x_n)$ 的实验产生成功结果的概率）的 **$k$-最近邻规则** 会找到 $k$ 个特征向量最接近 $(x_1, \dots, x_n)$ 的历史数据，然后取其中产生成功结果的数据所占的比例作为估计值。

虽然用于估计 $p(x_1, \dots, x_n)$ 的 $k$-最近邻规则仅使用 $k$ 个最近的历史数据值的结果，并给予所有这些数据相等的权重，但一种改进方法是使用所有历史数据的结果，给予那些特征向量最接近 $(x_1, \dots, x_n)$ 的数据更多的权重。假设有 $N$ 个历史数据结果。一种可能性是令 $I_j$ 在第 $j$ 个最近的历史结果成功时等于 1，否则等于 0，然后通过下式估计 $p(x_1, \dots, x_n)$：

$$
\frac{\sum_{j=1}^N \beta^{j-1} I_j}{\sum_{j=1}^N \beta^{j-1}} = \frac{1 - \beta}{1 - \beta^N} \sum_{j=1}^N \beta^{j-1} I_j
$$

其中 $0 < \beta < 1$ 是待选参数。也就是说，该规则分别为与 $(x_1, \dots, x_n)$ 最接近、次接近等实验的结果赋予连续的权重 $1, \beta, \beta^2, \dots, \beta^{N-1}$。

### 逻辑回归 {#sec-16_6_2}

逻辑回归也可以用来估计 $p(x_1, \dots, x_n)$，即特征向量为 $x_1, \dots, x_n$ 的实验产生成功结果的概率。该模型假设对于某些常数 $b_0, b_1, \dots, b_n$（需要进行估算），有：

$$
p(x_1, \dots, x_n) = \frac{e^{b_0 + \sum_{i=1}^n b_i x_i}}{1 + e^{b_0 + \sum_{i=1}^n b_i x_i}}
$$ {#eq-16_6_1}

R 可用于估算参数 $b_0, b_1, \dots, b_n$。例如，假设 $n = 5$，且有 6 个具有特征向量：

(3, 7, 9, 4, 12)
(8, 10, 4, 5, 16)
(14, 9, 11, 10, 15)
(18, 20, 12, 8, 7)
(2, 9, 13, 8, 17)
(7, 13, 21, 15, 19)

的实验分别产生了结果 (1, 0, 1, 1, 0, 1)，其中 1 表示成功，0 表示失败。（因此，具有特征向量 (8, 10, 4, 5, 16) 和 (2, 9, 13, 8, 17) 的实验结果为失败，而其他的均为成功。）要使用 R 估算参数，对于 $i = 1, \dots, 5$，令 $vi$ 为 6 个已运行实验的特征向量第 $i$ 个坐标的连续值，然后键入以下内容：

```R
> v1 = c(3, 8, 14, 18, 2, 7)
> v2 = c(7, 10, 9, 20, 9, 13)
> v3 = c(9, 4, 11, 12, 8, 15)
> v4 = c(4, 5, 10, 8, 8, 15)
> v5 = c(12, 16, 15, 7, 17, 19)
> y = c(1, 0, 1, 1, 0, 1)
> model = glm(y ~ v1 + v2 + v3 + v4 + v5)
> model
```

按回车键后会产生以下输出：

```text
Call: glm(formula = y ~ v1 + v2 + v3 + v4 + v5)

Coefficients:
(Intercept)      v1       v2       v3       v4       v5
  -5.25116    0.09965  0.04360  0.45959 -0.49604  0.29124
```

也就是说，逻辑回归模型中的 $a$ 和 $b$ 估计值为：

$$
p(x_1, \dots, x_6) = \frac{\exp\{-5.25116 + 0.09965x_1 + 0.04360x_2 + 0.45959x_3 - 0.49604x_4 + 0.29124x_5\}}{1 + \exp\{-5.25116 + 0.09965x_1 + 0.04360x_2 + 0.45959x_3 - 0.49604x_4 + 0.29124x_5\}}
$$
