## 选择最佳概率：多臂老虎机问题 {#sec-16_7}

假设有两种不同的药物可以治疗某种疾病，每种药物 $i$ 的使用都会导致成功（即治愈），其概率为 $p_i$，$i = 1, 2$，其中 $p_1$ 和 $p_2$ 是未知的。假设开出某种特定药物的结果（治愈与否）可以立即获知，问题在于如何根据之前所有的选择结果，顺序地决定为后续的每位病人开出哪种药物。由于此类问题的早期论文常涉及到一个有两个摇臂（左臂和右臂）的赌场老虎机（这种机器常被称为“两臂老虎机”），玩家在每次博弈时可以选择拉动哪个摇臂，因此这类问题被称为**多臂老虎机问题**（*bandit problems*）。由于 $p_1$ 和 $p_2$ 是未知的，每次选择使用哪种药物都涉及到一种权衡：是选择目前看起来最好的药物，还是选择一种药物以收集更多关于其成功概率的信息。我们现在提出一种在绝大多数情况下表现非常出色的策略，它能选出较好的药物。该策略是随机化的，即在每个阶段它都会指定使用药物 1 的概率。该策略如下：

*   每种药物先使用一次。
*   假设在药物 $i$ 已被使用 $n_i$ 次且总共治愈 $s_i$ 次（$i = 1, 2$）的情况下做出决策。令：
    $$
    f_1 = \frac{s_1 + 1}{n_1 + 2}, \quad f_2 = \frac{s_2 + 1}{n_2 + 2}
    $$
    并令：
    $$
    r = \frac{f_1 - f_2}{\sqrt{f_1(1 - f_1)/n_1 + f_2(1 - f_2)/n_2}}
    $$
    设 $\Phi$ 为标准正态分布函数，令：
    $$
    x = \Phi(r)
    $$
    现在以概率 $x$ 使用药物 1，以概率 $1 - x$ 使用药物 2。

例如，假设在某个阶段，药物 1 已使用了 9 次，治愈了 5 次；药物 2 已使用了 5 次，治愈了 2 次。在这种情况下，$n_1 = 9, s_1 = 5, n_2 = 5, s_2 = 2$，得到 $f_1 = 6/11, f_2 = 3/7$。因此，

$$
r = \frac{6/11 - 3/7}{\sqrt{\frac{30}{121 \times 9} + \frac{12}{49 \times 5}}} = .4225
$$

得出：
$x = \Phi(.4225) = .6637$。

因此，该程序要求以 .6637 的概率使用药物 1，以 $1 - .6637 = .3363$ 的概率使用药物 2。这可以通过计算机生成的均匀分布 $(0, 1)$ 随机变量 $U$（称为随机数）来实现。因为对于 $0 < x < 1$，均匀分布 $(0, 1)$ 随机变量小于 $x$ 的概率为 $x$，所以如果 $U < .6637$，则该程序将使用药物 1，如果 $U \geq .6637$，则使用药物 2。

**注：**
1.  R 可用于确定每个阶段的操作。因为命令 `runif(k)` 会生成 $k$ 个均匀分布 $(0, 1)$ 随机变量的值，所以在药物 $i$ 使用了 $n_i$ 次并产生 $s_i$ 次成功结果（$i = 1, 2$）时，我们可以执行以下操作来获取下一步行动：
    ```R
    > f1 = (s1 + 1) / (n1 + 2)
    > f2 = (s2 + 1) / (n2 + 2)
    > r = (f1 - f2) / sqrt(f1 * (1 - f1) / n1 + f2 * (1 - f2) / n2)
    > x = pnorm(r)
    > x
    > runif(1)
    ```
    倒数第二个输出给出 $x$，最后一个输出给出随机数的值。如果随机数小于 $x$，则下一步应使用药物 1；如果不是，则应使用药物 2。
    例如，假设药物 1 已使用 9 次，成功 5 次；药物 2 已使用 5 次，成功 2 次。要确定下一步操作，请执行：
    ```R
    > f1 = 6/11
    > f2 = 3/7
    > r = (f1 - f2) / sqrt(f1 * (1 - f1) / 9 + f2 * (1 - f2) / 5)
    > x = pnorm(r)
    > x
    [1] 0.6636754
    > runif(1)
    [1] 0.2600016
    ```
    因为 .2600（随机数的值）小于 $x = .6637$，所以下一步应使用药物 1。
2.  值 $f_1$ 和 $f_2$ 是对使用每种药物获得的成功比例的轻微变体，实际比例被稍作修改，以使其值不等于 0 或 1。
3.  上述考虑的老虎机问题类型除了药物测试外还有许多应用。例如，广告商可能希望在两种不同的互联网广告之间进行选择，广告注册为“成功”的前提是用户点击了它。
4.  老虎机问题的结果可以推广到有两种以上可能选择的情况。
