## 习题 {#sec-16_8}

1. 一家保险公司在设定其汽车保险费率时，会为每位保单持有人保留一个特征向量 $(x_1, \dots, x_7)$。在该向量中：
    *   $x_1$ 指保单持有人的性别，1 表示男性，2 表示女性；
    *   $x_2$ 指年龄，1 表示 25 岁以下，2 表示 25 到 40 岁，3 表示 40 到 60 岁，4 表示 60 到 70 岁，5 表示 70 岁以上；
    *   $x_3$ 指最喜欢的音乐类型，1 表示古典，2 表示乡村或轻音乐，3 表示说唱或重金属；
    *   $x_4$ 指教育程度，1 表示未高中毕业，2 表示高中毕业但未大学毕业，3 表示大学毕业但无更高学位，4 表示研究生学位；
    *   $x_5$ 指身体质量指数（BMI），1 表示 22 以下，2 表示 22 到 27，3 表示 27 到 33，4 表示 33 以上；
    *   $x_6$ 指身高，1 表示 5 英尺 2 英寸以下，2 表示 5 英尺 2 英寸到 5 英尺 8 英寸，3 表示 5 英尺 8 英寸到 6 英尺，4 表示 6 英尺以上；
    *   $x_7$ 指每年驾驶里程，1 表示低，2 表示中，3 表示高。

    以下是仅与上述特征向量的前 2 个坐标相关的历史随机样本。对于每个向量 $(x_1, x_2)$，它给出了具有该向量的保单持有人人数，以及其中在过去一年中至少发生过一次事故的人数。

    | 向量 | 保单持有人数 | 发生事故人数 |
    | :---: | :---: | :---: |
    | (1,1) | 240 | 9 |
    | (1,2) | 1050 | 18 |
    | (1,3) | 1400 | 20 |
    | (1,4) | 457 | 15 |
    | (1,5) | 145 | 12 |
    | (2,1) | 226 | 5 |
    | (2,2) | 940 | 12 |
    | (2,3) | 1420 | 14 |
    | (2,4) | 420 | 11 |
    | (2,5) | 142 | 13 |

    (a) 使用朴素贝叶斯方法估计一位 36 岁的女性在未来一年内发生事故的概率。
    (b) 使用朴素贝叶斯方法的改进版本来估计一位 36 岁的女性在未来一年内发生事故的概率。
    (c) 使用朴素贝叶斯方法估计一位 26 岁的男性在未来一年内发生事故的概率。
    (d) 使用朴素贝叶斯方法的改进版本来估计一位 24 岁的男性在未来一年内发生事故的概率。

2. 在前一个问题中，使用加权距离法估计以下人员在未来一年内发生事故的概率：
    (a) 一位 36 岁的女性；
    (b) 一位 26 岁的男性。

3. 使用 @sec-16_5 的损失函数方法，评估哪种技术（朴素贝叶斯法或加权距离法）最适合估计以下人员的概率：
    (a) 一位 36 岁的女性在未来一年内发生事故；
    (b) 一位 26 岁的男性在未来一年内发生事故。
    在所有情况下，请使用除当前考虑的个体数据值以外的所有数据，来估计具有该特征向量的人发生事故的概率。

4. 对于上表（习题 1 的表格）中给出的 6440 个数据值中的每一个，请确定当其事故概率是通过使用其他 6439 个值的数据通过以下方法估计时所产生的损失：
    (a) 朴素贝叶斯法；
    (b) 加权距离法。
    (c) 在本例中哪种方法效果更好？

5. 虽然 @sec-16_5 中提出的损失函数假设在发生估计概率为 $p$ 的事件时会产生损失 $(1 - p)^2$，但另一种流行的损失函数假设在发生估计概率为 $p$ 的事件时会产生损失 $-\log(p)$。证明后一种损失函数也具有如下性质：如果事件发生的实际（虽然未知）概率为 $\alpha$，那么当 $p = \alpha$ 时，期望损失最小。

6. 收集定量的真实数据，并研究逻辑回归或最近邻规则是否能产生更好的结果。

7. 假设药物 1 已被使用 55 次，其中 36 次成功；药物 2 已被使用 22 次，其中 12 次成功。@sec-16_7 的程序下一步使用药物 1 的概率是多少？使用 R 进行随机选择。
