## 双样本问题 {#sec-14_4}

某公司建立了两个独立的工厂来生产真空管。公司假设工厂 I 生产的真空管寿命服从均值为 $\theta_1$ 的指数分布，而工厂 II 生产的真空管寿命服从均值为 $\theta_2$ 的指数分布。为了检验这两个工厂是否存在差异（至少在它们生产的真空管寿命方面），公司从工厂 I 抽取了 $n$ 个真空管，从工厂 II 抽取了 $m$ 个真空管，并测量了它们的寿命。那么，他们如何确定这两个工厂生产的真空管是否确实相同呢？

若令 $X_1, \dots, X_n$ 表示工厂 I 生产的 $n$ 个真空管的寿命，并令 $Y_1, \dots, Y_m$ 表示工厂 II 生产的 $m$ 个真空管的寿命。当 $X_i$ ($i = 1, \dots, n$) 是来自均值为 $\theta_1$ 的指数分布的随机样本，且 $Y_i$ ($i = 1, \dots, m$) 是来自均值为 $\theta_2$ 的指数分布的随机样本时，问题就转化为检验假设 $\theta_1 = \theta_2$。此外，假设这两个样本是相互独立的。

为了开发关于 $\theta_1 = \theta_2$ 的检验方法，我们首先注意到 $\sum_{i=1}^n X_i$ 和 $\sum_{i=1}^m Y_i$（作为独立同分布指数随机变量之和）是独立的 **伽马** (*gamma*) 随机变量，其参数分别为 $(n, 1/\theta_1)$ 和 $(m, 1/\theta_2)$。因此，根据伽马分布与卡方分布的等价性可知：
$$
\frac{2}{\theta_1} \sum_{i=1}^n X_i \sim \chi_{2n}^2
$$
$$
\frac{2}{\theta_2} \sum_{i=1}^m Y_i \sim \chi_{2m}^2
$$

由 **$F$-分布** (*F-distribution*) 的定义可以得出：
$$
\frac{\frac{2}{2n\theta_1} \sum_{i=1}^n X_i}{\frac{2}{2m\theta_2} \sum_{i=1}^m Y_i} \sim F_{2n,2m}
$$ {#eq-14_4_1}

也就是说，如果 $\bar{X}$ 和 $\bar{Y}$ 分别是两个样本的均值，那么 $\frac{\theta_2 \bar{X}}{\theta_1 \bar{Y}}$ 服从自由度为 $2n$ 和 $2m$ 的 $F$-分布。

因此，当假设 $\theta_1 = \theta_2$ 成立时，$\bar{X}/\bar{Y}$ 服从自由度为 $2n$ 和 $2m$ 的 $F$-分布。这启发了如下关于 $\theta_1 = \theta_2$ 的检验方法：

**检验：** $H_0: \theta_1 = \theta_2$ 对抗备择假设 $H_1: \theta_1 \neq \theta_2$

**步骤 1：** 选择显著性水平 $\alpha$。

**步骤 2：** 确定检验统计量 $\bar{X}/\bar{Y}$ 的值 —— 设其值为 $v$。

**步骤 3：** 计算 $P\{F \leq v\}$，其中 $F \sim F_{2n,2m}$。如果该概率小于 $\alpha/2$（这发生在 $\bar{X}$ 显著小于 $\bar{Y}$ 时），或者大于 $1 - \alpha/2$（这发生在 $\bar{X}$ 显著大于 $\bar{Y}$ 时），则拒绝原假设。

换句话说，检验数据的 **$p$-值** (*p-value*) 由下式给出：
$$
p\text{-值} = 2 \min(P\{F \leq v\}, 1 - P\{F \leq v\})
$$

::: {#exr-14_4_1}
在显著性水平为 5% 时，检验如下假设：两个工厂生产的物品具有相同的指数寿命分布。已知来自第一个工厂的 10 个样本的总寿命为 420 小时，而来自第二个工厂的 15 个样本的总寿命为 510 小时。
:::

::: {#sol-14_4_1}
检验统计量 $\bar{X}/\bar{Y}$ 的值为 $42/34 = 1.2353$。为了计算自由度为 20 和 30 的 $F$ 随机变量小于该值的概率，我们使用 R 语言：
```r
pf(1.2353, 20, 30)
# [1] 0.6553309
```
由于 $p$-值等于 $2(1 - 0.6553) = 0.6894$，我们不能拒绝 $H_0$。
:::
